:PROPERTIES:
:ID:       20220508T172522.388109
:ROAM_REFS: @deryLateralityAuditoryFeedback
:END:
#+title: Notes on Dery, Mukamel, Laterality of Auditory Feedback in Motor Learning and Cross-Education

* summary and short reference
Behavioral study. Task: learn to play a piano sequence in R or L hand.

Found in previous study, [cite:@buaronVoluntaryActionsModulate2020], that actions that create sensory outcomes modulate the activity in perception areas: they include information on the motor action that created the sensory information (e.g which hand turned on the light)

in this study they want to show that it goes the other way too - that motor tasks encode the sensory modality through which they were learned

they don't go so far as to show encoding: it's a behavioral study.

They do show that learning rate improves differently through learning  the right or left hand

better for learning with right ear (for right hand playing?)


* general notes

(the ideomotor theory): action and perception are linked in a bidirectional mannerre a common representation of information at behavioral *and physiological* levels


AON - action observation network: extension of mirror neuron idea to human fMRI

- auditory singnals can modulate motor activity:
        listening to music you learned how to play activates the motor activation in the actual muscles that do the action
        efference copy:  In physiology, an efference copy or efferent copy is an internal copy of an outflowing, movement-producing signal generated by an organism's motor system (wikipedia)

        In theory - sent from motor areas to sensory areas, to prepare/modulate the perception in the sensory  areas to perceive the sensory consequences of the action
        usually inhibitory of self generated stimuli
        sensory modulations: differences in perception of self generated stimuli vs other generated

different effect of ipsi- and cotra-lateral affector (e.g hand) that creates the stimulus (e.g noise)
when sounds are generated with the hand ipsilateral to the stimulated ear, the monaural auditory threshold is lower than for sounds generated with the hand contralateral to the stimulated ear

stronger neural activation when active motor and auditory cortices are in the same hemisphere

cross education: training one side affects performance of the untrained side

- hypothesis: within hemisphere (sensory & motor) is better for learning, and cross hemisphere is better for cross education

* related papers:
  - [[id:20211027T163423.679299][Sensorymotor integration]]
  - Koch, I., Keller, P., & Prinz, W. (2004). The ideomotor approach to action control: Implications for skilled performance. International Journal of Sport and Exercise Psychology , 2 (4), 362-375.
    - Wolpert, D. M., Ghahramani, Z., & Flanagan, J. R. (2001). Perspectives and problems in motor learning. Trends in cognitive sciences,
  - learning from observation:
    + Blandin, Y., Lhuisset, L., & Proteau, L. (1999). Cognitive processes underlying observational learning of motor skills
    + Badets, A., Blandin, Y., & Shea, C. H. (2006). Intention in motor learning through observation.
  - Hughes, G., Desantis, A., & Waszak, F. (2013). Mechanisms of intentional binding and sensory attenuation: The role of temporal prediction, temporal control, identity prediction, and motor prediction (self vs other)
  - the forward model: Wolpert, D. M., Ghahramani, Z., & Jordan, M. I. (1995). An internal model for sensorimotor
  - Cross, E. S., Kraemer, D. J., Hamilton, A. F. D. C., Kelley, W. M., & Grafton, S. T. (2009). Sensitivity of the action observation network to physical and observational learning.
  - cross education
    - Ruddy, K. L., & Carson, R. G. (2013). Neural pathways mediating cross education of motor function
    -Van Mier, H. I., & Petersen, S. E. (2006). Intermanual transfer effects in sequential tactuomotor learning: evidence for effector independent coding
  -





#+print_bibliography:

* see also:
- [[id:20211108T172724.895041][Ideomotor Theory]]
