:PROPERTIES:
:ROAM_REFS: @greenFamiliarInteractingObject2006
:END:
#+title: Notes on Green, Hummel, Familiar Interacting Object Pairs Are Perceptually Grouped.
* main points
* findings
* methods
* summary and short reference
* general notes

*** ERP studies:
***** N400 is about integrating the current word into the context
***** the more fitting the word - the smaller the response
***** some think it's also related to the ease of lexical access - so it can tell us something about how words are organized in memory, and is affected by how many cues there are in the current context for the current word
***** information structure: what information is accented and which is deaccented. N400 stronger for new information which is accented than for new information which is deaccented
***** N400 for "an" instead of "a" when it excludes the most probable continuation (supports lexical semantic retrieval)
***** R vs L hemispheres: maybe lexical retrieval is specifically a LH attribute (oranges<apples<carrots N400)
***** possible roles of N400 response:
******* world knowledge
******* they say that  based on their experiment (yellow trains), semantic validity, and truth value of a sentence are done at the same time, and thus they are part of the same process, and not two sequential processes
******* silent meaning processing
********* semantic processing can change based on the context, even for very basic properties like being animate/inanimate ("the peanut was in love")
********* semantic processing of information that is implicit in the sentence and depends on our knowldege of the world ("the journalist started the article")
******* integration of pragmatic information
********* same  for information that's related to the information we have about the speaker: we get an N400 (rather than later) effect for words that create a meaning that conflicts with what we know
******* syntax-semantics interface
********* P600 effect for syntactic violations
******* where syntax is correct but semantics are wrong in some basic sense, or the other way around - we'll get either N400 or P600 depending on which modality imposes a stronger constraint in that context: if semantics is too far off, even though syntax is alright we'll get an N400
*** fMRI studies
***** LIFC: same areas were active for semantic anomalies as for sentences that had ambiguous words, they say it shows that these areas are related to semantic unification - they work harder in both cases.
***** "In short, the semantic unification network seems to include at least LIFC, left superior/middle temporal cortex, and the (left) inferior parietal cortex."
***** ILFC as a hub of unification?
***** story comprehension: 4 sentences, the last either easiy connected or requiring more inference - harder sentences required more IFC, MTG (middle temporal) and MFG (middle frontal) activation
***** ILFC as "semantic selection"/ "controlled retrieval" (generalizing from language area )
******* more ativated when generating verbs for a noun that has many optional verbs (i.e harder to choose among options) than for a noun with a single associated verb scissors vs wheel
******* unification often *but not always* implies/requires selection: among different meanings of the same ambiguous word - *unification is a broader account of ILFC role*
* see also (notes, tags/ other papers):
