:PROPERTIES:
:ID:       20220303T115646.825006
:ROAM_REFS: @jamesLetterProcessingAutomatically2006
:END:
#+title: Notes on James, Gauthier, Letter Processing Automatically Recruits a Sensory Motor Brain Network

* general notes
fMRI study - mainly interested in letters specifically as opposed to shapes in general.

They found activation of premotor areas while watching letters. And also activation of visual/perceptual areas while writing letters.

They found a network of 5 areas that were selectively active when watching letters:
- [[id:20220303T133505.883525][fusiform gyrus]]
- dorsal and ventral precentral gyrus
- inferior frontal gyrus
- cuneus

ROI 4: the ventral precentral gyr responded to perceiving both letters and shapes.
It's also close to the [[id:20220303T134015.382386][frontal eye field]]- maybe there's a connection to the eye movement we do when we follow the contour? Maybe it's an artifact caused by the way subjects actually look at the shape.

ROI 5: the [[id:20220303T135158.424474][cuneus]] was also activated for letters and shapes - while imagining them. (More activated compared to faces and objects)


The areas were engages in different degrees for different tasks.

* summary and short reference
* see also (notes, tags/ other papers):




#+print_bibliography:
