:PROPERTIES:
:ID:       20220608T103731.381603
:ROAM_REFS: @koulActionObservationAreas2018
:END:
#+title: Notes on Koul, Cavallo, Cauda, Costa, Diano, Pontil, Becchio, Action Observation Areas Represent Intentions From Subtle Kinematic Features

* General notes
* Annotations from PDF:

“recording 17 naïve participants grasping a bottle with the intent to drink or pour”

“Kinematics parameters of interest (n = 16, see Supplementary Methods) were computed throughout the reach-to-grasp phase of the movement (based on reach onset and grasp offset) at intervals of 10% of the normalized movement time.”

“Stimuli Selection and Video Editing”

“Cavallo et al. (2016) demonstrated that intention discriminability covaries with movement kinematics on a trial-by-trial basis”

“and relates directly to the expression of discriminant features in the observed movements.”

“we used the CaRT model generated by Cavallo and colleagues (Cavallo et al. 2016) to quantify intention-specifying information and select a set of 90 movements (45 grasp-to-pour and 45 grasp-to-drink) with a high predicted classification accuracy”

“Experiment Design and Timing”

“Intention Discrimination Session”

“3 runs”

“Each trial started with the static image of the hand for 600 ms, followed by the video of the grasping movement and a compensatory interstimulus interval (white fixation cross)”

“each trial lasted 2500 ms”

“each block containing 5 videos in a row of the same intention”

“instructed to look carefully at each video clip and try to discriminate”

“in 20% of the trials, after viewing all the video clips in a block, they were also asked to report the intention of the observed movements by means of a button press (“response” block).”

“Three predetermined block sequences”

“(kept constant across subjects) were chosen for the 3 runs.”  why not randomize per run?

“Localizer Session Subsequent to the main experiment”

“Trials were delivered in blocks, with each block containing both reach, grasp, and pour action sequences and reach, grasp, and drink action sequences.”

“TR = 2500 ms”

“EPI images for different runs were first realigned to the mean image,”

“then resliced with allowed motion limited to 3 mm”

“then coregistered to the participants’ high-resolution anatomical T1 images”

“The T1 images were segmented using SPM segmentation function, and normalization parameters to MNI were calculated”

“used to normalize resliced functional images.”

“the normalized images were spatially smoothed using an 8-mm FWHM Gaussian kernel”

“For the localizer session, the model included 2 regressors of interest: action sequence and rest blocks.”

“To investigate group level effects for the localizer session, we entered contrast images of the effects of the regressors of interest for each participant into a random-effects analysis, where we performed the contrast action sequence > rest. The resulting group-level activation map threshold of P < 0.001 (uncorrected) served as the action observation localizer.”

* summary and short reference
* see also (notes, tags/ other papers):




#+print_bibliography:
