:PROPERTIES:
:ROAM_REFS: @laceyMetaphoricallyFeelingComprehending2012
:ID:   20211123T123959.836037b :END:
#+title: Notes on Lacey, Stilla, Sathian, Metaphorically Feeling: Comprehending Textural Metaphors Activates Somatosensory Cortex


* main points

This study deals with the way the brain understands metaphors. They localiz ed the areas that process sensations and visual cues of texture, and then compared brain activation while listening to texture-containing metaphorical and control sentences having the same meaning. They controlled well for the length of the sentences, almost always replacing word for word.
They found higher activation in textural sensory (but not visual) areas for the metaphors, and say that this supports, or is at least consistent with the notion that groundedness/embodiment/sensory simulation is used for understanding metaphors.
It's a very small study - 7 subjects - so they're not making far reaching claims about the meaning of the findings.

For further research it would be interesting to do the same with metaphors using other specific  kinds of sensations like taste (sweet nature, sour face, bitter failure etc.) which are also processed in well known areas. First to see if the finding for domain specific activation replicates, and also to see if there's a joint area that is active across domains and may relate to metaphor understanding in general.
