:PROPERTIES:
:ID:       20220623T175506.517583
:ROAM_REFS: @reznikLateralizedEnhancementAuditory2014a
:END:
#+title: Notes on Reznik, Henkin, Schadel, Mukamel, Lateralized Enhancement of Auditory Cortex Activity and Increased Sensitivity to Self-Generated Sounds

* summary and short reference
 Behavioral + fMRI study, task: play a piano sequence with either RH or LH, auditory feedback either R or L ear inside the magent.

ניסוי התנהגותי, מטלה: נגינה על פסנתר, ביד ימין או ביד שמאל, עם פידבק לאוזן ימין או שמאל.

Main results:

  1. הנחתה בפעילות בעיקר באיזורים פרונטליים
  2. הגברת פעילות בעיקר באיזורים אודיטוריים STG
  3. ההגברה הייתה יותר משמעותית בקורטקס הקונטרלטרלי ליד
  4.
  5. בהתאם - סף השמיעה היה נמוך (=טוב) יותר באוזן האיפסילטרלית ליד (ככה שהקורטקס האודיטורי יוצא קונטרה ליד)
  6. חיבוריות (functional connectivity) ־ ה STG הקונטרלטרלי היה האיזור שהיה הכי מחובר לקורטקס המוטורי בזמן נגינה.

* english

    1. Attenuation activity mostly in frontal areas (such as the superior and middle frontal gyri (SFG and MFG)) bilaterally.

    2. Activity is enhanced in auditory cortices (bilateral STG) during the active condition.

    3. Enhancement was stronger when the hand was contralateral to the auditory cortex.

    4. The hearing thershold was lower (=better) when the hand and the ear were ipsilateral.



* general notes
Generally - previous behavioral studies show a reduced response to self-generated stimuli
fMRI studies are less equivocal - some show enhancement, some attenuation, some both

 self produce sounds enhanced  auditory cortex activity more than externally produced sounds

* Annotations(5/9/2022, 4:52:43 PM)

Performing actions with auditory consequences modulates the response in auditory cortex to otherwise identical stimuli passively heard.

functional magnetic resonance

bilateral enhancement in the auditory cortex to self-generated versus externally generated sounds

this enhancement is stronger when the sound-producing hand is contralateral to the auditory cortex

binaural hearing thresholds are lower for self-generated

monaural thresholds are lower for sounds triggered by the hand ipsilateral to the stimulated ear.

is reported as being less loud9


Our results show that sensory attenuation is mostly found in frontal regions such as the superior and middle frontal gyri (SFG and MFG) bilaterally.

activity in auditory cortices (bilateral STG) is enhanced during the active condition.

this enhancement is stronger when the performing hand is contralateral to the auditory cortex

further supported at the behavioural level as manifested by lower hearing thresholds to sounds evoked by the hand ipsilateral to the stimulated ear



* see also (notes, tags/ other papers):

#+print_bibliography:
