 :PROPERTIES:
:ID:       20220509T161923.194392
:ROAM_REFS: @reznikLateralizedEnhancementAuditory2014
:END:
#+title: Notes on Reznik, Henkin, Schadel, Mukamel, Lateralized Enhancement of Auditory Cortex Activity and Increased Sensitivity to Self-Generated Sounds

* summary and short reference
" Given the premise that efference copies are sent from the motor regions generating the action and the robust laterality effects of both the motor and sensory systems, it has been suggested that the degree of sensory modulations would be significantly different depending on the identity of the stimulus-generating effector. In a previous study conducted in our lab, Reznik et al. (2014) showed that when sounds are generated with the hand ipsilateral to the stimulated ear, the monaural auditory threshold is lower than for sounds generated with the hand contralateral to the stimulated ear. At the physiological level (using fMRI), they also demonstrated stronger enhancement of neural responses to self vs. externally generated stimuli in the superior temporal gyrus (STG) that resides within the same hemisphere as the active motor cortex "

 Behavioral + fMRI study, task: play a piano sequence with either RH or LH, auditory feedback either R or L ear inside the magent.

ניסוי התנהגותי, מטלה: נגינה על פסנתר, ביד ימין או ביד שמאל, עם פידבק לאוזן ימין או שמאל.

Main results:

  1. הנחתה בפעילות בעיקר באיזורים פרונטליים
  2. הגברת פעילות בעיקר באיזורים אודיטוריים STG
  3. ההגברה הייתה יותר משמעותית בקורטקס הקונטרלטרלי ליד
  4. בהתאם - סף השמיעה היה נמוך (=טוב) יותר באוזן האיפסילטרלית ליד (ככה שהקורטקס האודיטורי יוצא קונטרה ליד)



* general notes
Generally - previous behavioral studies show a reduced response to self-generated stimuli
fMRI studies are less equivocal - some show enhancement, some attenuation, some both

 self produce sounds enhanced  auditory cortex activity more than externally produced sounds

* see also (notes, tags/ other papers):




#+print_bibliography:
