 :PROPERTIES:
:ID:       20220509T161923.194392
:ROAM_REFS: @reznikLateralizedEnhancementAuditory2014
:END:
#+title: Notes on Reznik, Henkin, Schadel, Mukamel, Lateralized Enhancement of Auditory Cortex Activity and Increased Sensitivity to Self-Generated Sounds

* summary and short reference
 Behavioral + fMRI study, task: play a piano sequence with either RH or LH, auditory feedback either R or L ear inside the magent.

Main results:
       1. Attenuation activity mostly in frontal areas (such as the superior and middle frontal gyri (SFG and MFG)) bilaterally.

       2. Activity is enhanced in auditory cortices (bilateral STG) during the active condition.

       3. Enhancement was stronger when the hand was contralateral to the auditory cortex.

       4. The hearing thershold was lower (=better) when the hand and the ear were ipsilateral.



* general notes
Generally - previous behavioral studies show a reduced response to self-generated stimuli
fMRI studies are less equivocal - some show enhancement, some attenuation, some both

 self produce sounds enhanced  auditory cortex activity more than externally produced sounds

* see also (notes, tags/ other papers):




#+print_bibliography:
