:PROPERTIES:
:ID:       20221030T134948.903864
:ROAM_REFS: @rosenblattBetterthanchanceClassificationSignal2021
:END:
#+title: Notes on Rosenblatt, Benjamini, Gilron, Mukamel, Goeman, Better-than-Chance Classification for Signal Detection

* general notes



* summary and short reference
Roy's paper about a directional MVPA analysis with Roee Gilron.


Abstract:
"Multivoxel pattern analysis (MVPA) has gained enormous popularity in the neuroimaging community over the past few years. At the group level, most MVPA studies adopt an “information based” approach in which the sign of the eﬀect of individual subjects is discarded and a non-directional summary statistic is carried over to the second level. This is in contrast to a directional “activation based” approach typical in univariate group level analysis, in which both signal magnitude and sign are taken into account. The transition from examining eﬀects in one voxel at a time vs. several voxels (univariate vs. multivariate) has thus tacitly entailed a transition from directional to non-directional signal deﬁnition at the group level. While a directional group-level MVPA approach implies that individuals have similar multivariate spatial patterns of activity, in a non-directional approach each individual may have a distinct spatial pattern. Using an experimental dataset, we show that directional and non-directional group-level MVPA approaches uncover distinct brain regions with only partial overlap. We propose a method to quantify the degree of spatial similarity in activation patterns over subjects. Applied to an auditory task, we ﬁnd higher values in auditory regions compared to control regions"

* see also (notes, tags/ other papers):





#+print_bibliography:
