:PROPERTIES:
:ROAM_REFS: @steinDissociatingConsciousUnconscious2021
:ID:   20211107T115658.041175
:END:
#+title: Notes on Stein, Peelen, Dissociating Conscious and Unconscious Influences on Visual Detection Effects
* general notes
They make a compelling case for the absence of UC processing of semantic knwoledge from pictures for both CSF and BM. I went to the original paper, and saw that the effect there, while significant was very small - only 8-9 ms out of 500ms, which also take me back to your paper talking about independence from consciousness and comparing the actual performance with and without awareness.
So this study seems to show that that effect was really not very significant after all.
I'm not sure I understand why is it that prime and target need to be in different formats - I agree it makes for a stronger case, because it ensures the effect, if found, goes through the actual meaning of the prime and not through its appearance, but it may also be that the unconscious part of semantic processing is limited to a modality-specific processing, so in face, only primes from the same modality will be expected to have an effect.

[cite:@maozNeuralPrecursorsDecisions2019]
