:PROPERTIES:
:ROAM_REFS: @wangTwoFormsKnowledge2020
:ID:       20220110T105424.558837
:END:
        #+title: notes on: Wang, X., Men, W., Gao, J., Caramazza, A., & Bi, Y. (2020): Two Forms of Knowledge Representations in the Human Brain
*** main points
Bottom line:
There are two areas that are responsible for color knowledge, one which is embodied, and one abstract: there's a region where semantic knowledge about colors resides which is not related to sensory information - so it's not embodied in that respect.
Justification:
There is a region in the dorsal L ATL which is active in both blind and sighted when they are thinking about and matching colors. In the sighted there's an additional area that is part of the higher visual system in the L post fusiform gyr which is also activated. Since this area is activated in a similar way in the blind, who have no sensory experiences, they deduce that it's not reliant on sensory information in sighted also.

"object-color knowledge in the typically developed brain is distributed over distinct regions that represent sensory-based and abstract conceptual information" ()
*** findings
*** methods
*** summary and short reference
*** general notes ( Extracted Annotations (1/10/2022, 10:44:56 AM) )

            "a region in the left dorsal anterior temporal lobe supports object-color knowledge in both the blind and sighted groups" ([cite:@wangTwoFormsKnowledge2020])

            "Thus, there are (at least) two forms of object knowledge representations in the human brain: sensory-derived and languageand cognition-derived knowledge, supported by different brain systems." ([cite:@wangTwoFormsKnowledge2020])

            "one prominent theory assumes that such knowledge is stored in sensory association cortices, derived from sensory experiences (i.e., seeing the colors of roses) (Barsalou et al., 2003; Martin, 2016; Simmons et al., 2007). The alternative possibility is that even sensory-derived knowledge is also represented at an abstract conceptual level distinct from sensory representations (Leshinskaya and Caramazza, 2016; Mahon and Caramazza, 2008; Shallice, 1987, 1988; Wang et al., 2018; Xu et al., 2017)." ([cite:@wangTwoFormsKnowledge2020])

            embodied vs disembodied (/grounding by interaction)
            (note on p.384)


            "understanding sensory-independent representations" ([cite:@wangTwoFormsKnowledge2020])

            "providing a unique opportunity to test how and where such knowledge is represented in the brain" ([cite:@wangTwoFormsKnowledge2020])

            אבל איזה מין ידע זה בעצם? איך הוא קשור לידע של אנשים רואים על צבעים? (note on p.384)




            Fig. 1
            less variability in blind subjects: I think because their knowledge of color is more schematic, more patterns - they have no experiences of variations in the colors of the different fruit (note on p.385)




            "Object-color knowledge" ([cite:@wangTwoFormsKnowledge2020])

            "object-color knowledge in the typically developed brain is distributed over distinct regions that represent sensory-based and abstract conceptual information" ([cite:@wangTwoFormsKnowledge2020])

            שורה תחתונה
            (note on p.385)




            "expected from theories that assume that color-knowledge representations in the sighted are rooted exclusively on sensory experience." ([cite:@wangTwoFormsKnowledge2020])

            they're going to want to say that for SC group at some point the knowledge becomes abstract - maybe like the frequentist approach (note on p.385)




            "The behavioral results showed that the object-color-knowledge similarity space of the EBs, who never experienced colors, was highly similar to that of SCs." ([cite:@wangTwoFormsKnowledge2020])

            how come their spaces look the same? this means that the knowledge about the relation between colors is the same in both groups? the knowledge of relations betwenn colors of specific fruit? (note on p.385)




            "RSM" ([cite:@wangTwoFormsKnowledge2020])

            RSM - representation simi;arity matrix

            (note on p.385)




            "listened to names of 24 fruit and vegetable items and judged whether the color of each item is red/reddish in the real world" ([cite:@wangTwoFormsKnowledge2020])

            the fMRI task
            (note on p.386)




            "with no significant effects of group or group by item interaction on either response time or response types" ([cite:@wangTwoFormsKnowledge2020])

            similar behavioral results for EB and SC
            (note on p.386)




            "two types of analyses in parallel" ([cite:@wangTwoFormsKnowledge2020])

            why more responses overall for SC? (note on p.387)




            faster response times for blind - again - cemented knowledge, no need to choose between varying experiences (note on p.387)




            ""Color-Perception Regions": Sighted but Not Blind Individuals Represent Object-Color Knowledge in Ventral Occipitotemporal Color Perceptual Regions" ([cite:@wangTwoFormsKnowledge2020])

            הם ראו שבאנשים רואים יש תגובה לשאולת על צבעים גם באיזורים ראייתיים ב fusiform gyrus (note on p.388)




            "Whole-Brain Searchlight Results" ([cite:@wangTwoFormsKnowledge2020])

            they ran a whole brain analyais as a validation - not to be confined by the ROIs, and got similar results to the ROI results (note on p.389)




            "indicate that there are two distinct types of knowledge representation in a typically developed human brain, even for sensory-related properties. one based
            on sensory-derived codes (seeing the colors of roses) and one
            based on language- (and cognitively) derived codes. In the
            sighted, but not in the blind group, these two sets of nodes are
            intrinsically, functionally connected." ([cite:@wangTwoFormsKnowledge2020])

            is this the only explanation?
            (note on p.390)




            "no evidence for altered dependence in the blind on other object features in representing object-color information" ([cite:@wangTwoFormsKnowledge2020])

            how did they actually test this? they just show that EB snd SC are compareable in those tasks
            (note on p.390)




            "Our results that color knowledge was not found to be encoded in the vicinity of these regions in the case of visual deprivation is in favor of the view that these areas encode visual-experience-derived representations" ([cite:@wangTwoFormsKnowledge2020])

            finding: dorsal OT areas which are known to process colors are also involved in color-knowldege` (note on p.391)




            "this overlap with the sighted indicates that even when color knowledge can be obtained through vision, the language/cognition-derived knowledge representation is also present" ([cite:@wangTwoFormsKnowledge2020])

            "In other words, while in sighted people object-color knowledge can be acquired through vision, non-sensory-derived representations of color knowledge are present in dorsal ATL just as in blind people." ([cite:@wangTwoFormsKnowledge2020])

            finding: color-knowledge is encoded in lATL for both blind and sighted - this relates to the lATL role we saw for semantic integration (note on p.391)




            "This non-sensory, language/cognitionderived knowledge representation cluster aligns well with the ATL regions showing stronger activation for abstract relative to concrete words (e.g., justice > cup) (Binder et al., 2009; Wang et al., 2010, 2019), and words referring to objects that are not perceptible relative to those that are (e.g., rainbow versus rain for congenitally blind, Striem-Amit et al., 2018), and regions showing adaptation effects for perceptual similarity judgment of color words in early blind (Bottini et al., 2020)" ([cite:@wangTwoFormsKnowledge2020])

            why do all these match their finding? (note on p.391)




            "uncorrected" ([cite:@wangTwoFormsKnowledge2020])

            "the hypothesis that abstract concepts rely more on dorsal ATL due to their heavier reliance on the language system, while concrete concepts rely more on sensory-motor modalities" ([cite:@wangTwoFormsKnowledge2020])

            "but the level of abstractness of the knowledge coding" ([cite:@wangTwoFormsKnowledge2020])

            "coding" ([cite:@wangTwoFormsKnowledge2020])

            "that determines whether it is represented in dorsal ATL." ([cite:@wangTwoFormsKnowledge2020])

            They say that the dorsal ATL is concerned with representing knowledge that is abstract in the sense that it doesn't rely on sensory experiences to be learned.

            In contrast to knowledge that is abstract in the sense that its content is non-concrete.

            so we would expect the same to be true of deaf people's concepts of sound, and if we teach healthy people som new, un-sensable characteristic of objects. (note on p.391)




            "rsFC" ([cite:@wangTwoFormsKnowledge2020])

            resting state functional connectivity (note on p.391)




            "dorsal ATL is strongly connected with the regions implicated in language processing (Figure 5A), which require a high degree of generality and abstractness" ([cite:@wangTwoFormsKnowledge2020])

            what does it mean - the ATL is connected with areas in language areas that specifically deal with very abstract information? (note on p.391)




            "If knowledge referring to perceptible properties and entities is also represented in this region, in a language- (and cognitively) derived format, then why the abstract advantage?" ([cite:@wangTwoFormsKnowledge2020])

            maybe because it's not about abstractness per se, but about the way the knowledge is learned? (note on p.391)
        * see also (notes, tags/ other papers):
