#+TITLE: Notes on: Wolpert, D. M., Ghahramani, Z., & Flanagan, J. R. (2001): Perspectives and problems in motor learning

* summary and short reference
* general notes
  - in a sense, all perception and cognitive processes my be viewed as inputs for deciding what's the next motor action.
  - it's the only way we have of interacting with the world
  - motor learning - co-adaptation of the brain and the body to allow the former to control the latter
    + there are changes to both in the process of learning
  - motor control: transforming sensory information and internal representations of the movement into motor commands that act on ensembles of muscles
  - motor learning: adapting and mastering these transformations
  - two types of transformations:
    + kinematic - relation between joint angles etc. to the position of body parts
    + dynamic - relating to the forces, directions etc. that are required to create movement.
  - definition of directions:
    + forward: from motor action to sensory consequence (what will be the consequence of this action?)
    + inverse: from desired consequence to motor command
  - internal model: the representation of the movement != the movement in the real world.
    + the model is used represent these transformations (kinematic, dynamic) x (forward, inverse)
  - we need an inverse model of our actions for planning actions that get us to a particular goal
  - (do we?) We may need a forward model for predicting the sensory consequences of motor commands - e.g. to ignore sensations that come from self-movement
  -

* see also (notes, tags/ other papers):
