:PROPERTIES:
:ID:       20210627T195217.352083
:END:
#+TITLE:Monday, 29 June 2020

* Fleeting notes
** 08:00

אולי אני יכול פְְפשוט לצפות מעצמי לפחות? לצפות מעצמי לסטנדרט יותר נמוך של רגש, של
עוצמה וכנות של רגש בכל זמן? לשמוח כשאני שמח, להתלהב כשאני מתלהב, ופשוט לקבל את
זה שאני לא כשאני לא?
הייתה לי הרגשה עכשיו שאם אני אעשה את זה אני אולי אופתע מהדברים שכן יעלו, מאיך שכן
יהיה רגש פתאום ואיך הוא ירגיש.

** 23:45
* Journal
** 23:52

היה לי כיף עם דגן הערב. מודה שקצת הרגשתי לא בנוח כמו שהייתי רוצה, שזה מצחיק כי
בעצם דיברנו ממש על מחשבות מהסוג הזה :))
כן הצלחתי לפתוח איתו לפחות קצת את הקשיים שיש לי לגבי מחויבות ופוקוס לפני החתונה,
ומשיכה לנשים אחרות, וכן דיברנו קצת על היחסים שלו עם רים. ממש מצא חן בעיני הטקס
שהם עושים כל שנה, שהם מביאים שאלות או נושאים שהם רוצים שיעלו, ומדברים עליהם.
נראה לי שהייתי ממש פתוח איתו בסהכ, וזה מעניין איך זה מרגיש אחרת מאשר לדבר על
הדברים עם ינאי.. כאילו הייתי צריך למצוא את הדרכים המתאימות לרמוז את מה שהיה לי
קשה לומר ישירות, והן היו אחרות מהדרכים שהיו מתאימות עם ינאי.

מצא חן בעיני מאוד מה שהוא אמר על לרצות "להתרגל", שהוא רוצה שרים תהיה הבית שלו, ה
baseline, וזה גרם לי לחשוב על זה שאני לגמרי מרגיש שאילת היא הבית שלי, ושזה מה
שאני רוצה, וגם שאני מרגיש שזה יכול להיות עוד יותר ככה, שכמה שאני אהיה יותר חופשי
להיות אני במלואי איתה, אני ארגיש יותר שזה הבית שלי, ומקום בטוח בשבילי שאני יכול
להרגע בו.

