:PROPERTIES:
:ID:       20210627T195253.003826
:END:
#+TITLE: Notes on interview with Karl Friston
- source :: https://www.youtube.com/watch?v=NIu_dJGyIQI

* notes
*** intro
***** the brain is an "inference machine", it's always busy collecting data and constructing explanations about it.
***** starting from very basic assumptions, we can construct the idea of the free energy principal
***** it doesn't only deduces it also chooses which data to use for its predictions out of the multitude that it collects.
***** any system that exists will act as if it has a model of the world, and will try to gather evidence for it.
*** to even begin to talk about any specific "thing" we first need to acknowlede that there have to be a boundary between thath thing ans the rest of the world. there is "the thing", and "not the thing"
*** markov blanket:
***** that boundary is called a "markov blanket" in statistics - it's just a way to separate the world into things/states that are internal to the system, that belong to it, and those that are external to it.
***** "the system" can be anything - it's an abstraction - a cell, the brain, a culture, this planet etc. at any scale
***** the blanket has two faces - internal and external - and is comprised of "states"
***** *sensory stated* influence internal states (= stated of the system) but not the outside world. they mediate information about the world to the system.
***** *active states* are  the other way around - they are dependent on internal states of the system, but not by the outside world. they influence external states (=states of the world outside).
*** existing over time:
***** the fact that a system exists over time means that it is resisting entropy. it does not disperse.
***** the flow of the molecules of the system exactly counters the dispersive forces
***** it can be mathematically shown that this flow is the same as moving uphill on the probability distribution of where the molecules should be.
***** that distribution ins also the same Bayesian model evidence.
***** the defining feature of any system that does not disperse is that its states flow in such a way as to maximize model evidence.
***** so if a system exists it will appear to be maximizing its model evidence. appear as if it has a model of its world.
***** its states must equivalently maximize marginal likelihood, and minimize free energy. *why?*
***** this maximizing includes actions and sensations (all active and sensory states) - so we can say that our actions and our sensations are subject to the same principal
***** since the brain is a non-dispersing system, it's states are maximize the bayesian  model evidence of (itself?), and therefore we can say that it must contain (seem to contain?) a model of the world around us.
***** what about other things that don't disperse? like trees, insects? what about inanimate objects?  a concrete wall disperses more slowly than a person, no?

*****

* see also:

 *

