:PROPERTIES:
:ID:       20210627T195154.711955
:END:
#+TITLE: Sunday, 10 May 2020

* יומן
** 2020-05-08

  had breakfast with ayelet, I talked a litlle about the feeling I have that
  it's something big that we're doing - that it's just the two of us, in a way,
  from now on, and that I need/want to (still...) to learn how I can rely on
  her, and the fact that it kind of scares me little, in a way.

** 00:44
*** tired and cold. finished reinstalling emcas + all the configurations. I was pretty devastated when I realized that the .spacemacs file was gone, but it took me less time and effort than I anticipated.
*** I must remember to write in my journal tomorrow about the conversation that I had with Ayelet this morning - that she sometimes (often?) feel alone. And my understanding that I really have a problem feeling "together" or "with" another person. That I never really learned how to do it. Thinking about it now, I connect it to the feeling of unease I have with Hagai sometimes.

   

