:PROPERTIES:
:ID:       20210627T195225.162646
:END:
#+TITLE: פוסט משטרה


יש לי וידוי קטן. לא הרבה אנשים יודעים, אבל סבא שלי - יחזקאל סהר, אז עדיין
סחרוב - היה מי שהקים את משטרת ישראל, ושימש כמפכ"ל הראשון שלה.
לא במקרה זו עובדה שאני לא בקלות מספר - כבר שנים, לפחות מאז 2011, שאני פשוט
מתבייש בזה. שברוב האינטראקציות שהיו לי עם שוטרים, בעיקר בהפגנות אבל לא רק, אני
בעיקר מרגיש מאוים, ומוצא את עצמי מהצד השני של המתרס מהם.
כשסבא שלי הקים את המשטרה


המשטרה אמורה לשרת את המדינה, כלומר את האזרחים, ואת החוק - לא את השלטון ואת
העומדים בראשו.
זה כל כך ברור הרי - ביבי לוחץ על אוחנה ואוחנה לוחץ עליכם, וכולנו קראנו את
הציטוטים שהודלפו מהפגישה שלכם - למצוא תירוצים לבטל או להזיז את ההפגנה? להיטפל
למפגינים עם קנסות על מסכות? "לאתגר את פסיקת בג"ץ"? נפלתם על הראש??

התבלבלתם - המפגינים הם לא האויב, אנחנו האחים והאחיות, והחברים ובנות הזוג שלכם,
וכל עוד אנחנו לא שורפים את בית ראש הממשלה ולא בוזזים חנויות, התפקיד של המשטרה
הוא להכיל את הסיטואציה, לוודא שההפגנה ממשיכה להיות לא אלימה, ובעיקר להגן עלינו
מפני חוליגנים מופרעים שבאים לפגוע בנו.
זכות ההפגנה היא אחת הזכויות הכי בסיסיות וחשובות בדמוקרטיה (סליחה, כן, אבל יותר
חשובה מהזכות לישון בשקט, עם כל אי הנעימות האמיתית שזה גורם לתושבי השכונה), וזה
מטורף בעיני שהמשטרה עשתה למטרה לעצמה להתעמר ולהפחיד אזרחים בנסיון לגרום להם לא
להגיע


 דמנו ודם הדמוקרטיה שלנו בראשכם.

