:PROPERTIES:
:ID:       20210627T195156.724223
:END:
#+TITLE: malach lecture in ELSC - summary
- tags ::  
- see :: [[file:agenda.org::* watch Malach's lecture at ELSC][watch Malach's lecture at ELSC]],[[file:labs.org][Labs]] 

* Preliminary results

  - There are "waves" or fluctuations of neuronal activation that touch all
    areas of the brain.
  - they are seen when subject lie in an FMRI without stimulus.
  - in this lecture he talks about visual cortex mostly, and also about
    some decision making area.
  - they are slow compared to task-oriented neuronal activation

* Hypothesis:

  This baseline activity is in some way encoding the prior knowledge that the
  subjects came with, their "selves", their training etc.

* Method:

  If the fluctuations are related to prior knowledge/training then changing the
  prior knowledge by training subjects in a task should influence the
  fluctuations.
 
  specifically they assume a [[file:2020-05-12-hebian_learning_model.org][Hebian Learning Model]], and want to show that the
    correlation between different areas changes with training (rises if both
    areas participate in the task, decreases if they are unassociated)
    
  they ran two tasks:
    1. asking subjects to activate their [[file:2020-05-12-anterior_cingulate_cortex.org][Anterior Cingulate Cortex]] by thinking
       about actively deciding and taking initiative. this was done through
       [[file:2020-05-12-neuro_feedback.org][Neuro-feedback]]
    2. (these were preliminary results) they asked subject to recognize
       faces/buildings appearing out of a black and white mask.
       - they controlled for various artifacts by having a "resting task" that
         required only the auditory cortex, and by training some of the subjects
         outside of the fMRI.

* Results

  They found good correlation between the co-activation of different areas with
  the target during the task performance phase (on the one hand), and the
  "random" correlation in activation during the resting "fluctuations" state (on
  the other).

