:PROPERTIES:
:ID:       20210627T195249.554947
:END:
 #+TITLE: Class notes: intro to neurobiology (0455223701)
#+STARTUP: latexpreview

* Oct 19 :ankified:
*** administration:
***** There will be a test
***** bonus for attending classes
*** the brain is 60% fat (lipids) - of it's dry weight.
*** 90% water in vivo
*** brain is surrounded by layers: :ankified:
***** CSF
***** archanoid
***** dura
***** several more
*** the cerebrum is divided into regions "lobes" that are responsible for different functions :ankified:
***** frontal lobe - executive functions, problem solving
***** parietal lobe - integration of sensory information
******* motor cortex and sensory cortex - input/output to/from specific body parts/regions
***** temporal lobe - derive semantic meaning from sensory information
******* 
***** occipital lobe - vision
*** the cortex contains many functional areas, each comprised of thousands of "columns" (0.5 mm in diameter) arrayed "into" the cortex, perpendicular to the cortex's surface. :ankified:
*** the brain is comprised of 3 main structures: :ankified:
***** forebrain

            divides into:

******* cerebral cortex
******* white matter
******* basal ganglia
******* thalamus
******* hypothalamus
******* subthalamus
******* epithalamus
***** midbrain
******* relays sensory information from sense organs to the brain
***** hindbrain

consists of:

******* pons:

controls respiration and heart rate

******* medula oblongada:

controls respiration and heart rate

******* cerebellum:

helps control movement and timing

*** the lymbic system: :ankified:
***** Structures that are critical to memory formation, pleasure and various emotional processes.
***** more recent than core of brain (only mature in mammals)
***** includes:
******* hippocampus

              much involved in memory

******* amygdala
*** sympathetic and parasympathetic nervous systems:
***** the sympathetic system is dominant in stress response: heart rate breathing, pupils dialation, blood flow to muscles
***** the parasympathetic does the oposite - relaxes, conserves energy.
***** both systems are active - the end result of effect on the body is by the balance of signals from the two.
*** 3 types of neurons:

        1. sensory
        2. relay (interneurons)
        3. motor

*** glia (support) cells
***** Three main functions:

            1. supply neurons with nutrients and oxygen
            2. clean up dead neurons
            3. first line of defense during stress (what does it mean?)

***** roughly the same number as neurons (at least)
***** two groups:
******* macroglia
********* astrocystes
******* microglia
* Oct 20 :ankified:
*** astrocystes - elaborated :ankified:
***** have different structures and functions in different brain areas:

            - Radial - found in spinal chord and cerabelum
            - marginal - close to the surface of the brain
            - protoplamic - in the gray matter, makes a lot of contact with neurons
            - velate - in the cerebelum, where there are densely packed neurons
            - fibrous - in white matter, parallel to axons, provides direction during development
            - perivascular - unattached to neurons, a lot of contact to blood vessels.

***** functions:
******* in development - neurons migrate along the body of radial astrocystes. the astrocystes form the skeleton of the shape of the developing brain.
******* metabolic support for neurons - transferring glucose directly, and also energy in other forms.  also keep glycogen as reserve
******* support the BBB (blood brain barrier)
******* neurotransmitter reuptake and release - express some membrane transporters for NT
******* regulation of ion concentration
******* release of neurotropic factor - protection and neurogenesis
******* vasomodulation - neuronal regulation of blood flow
******* promote myelination of oligodendrocytes
******* essential for neurogenesis
******* mediate progenitor neuronal cells (neural stem cells) migration and diversification
***** research refers to the  "neurovascular unit" a neuron + the blood vessels and astrocystes
***** aging astrocystes look like neonatal astrocystes in some ways - they lose many dendrites/axons.
***** maybe an effect on cognition
******* improved cognitive abilities (memory) with human astrocystes implanted in mice.
********* Han et al cell 2013
******* A. Einstein's brain was richer in astrocystes in some areas related to mathematical thinking
***** looks like there's communication between astrocystes via calcium signals
***** help protect the brain from trauma by forming a physical barrier - scars (astorgliosis) between areas, and allowing for contained inflammation.
*** oligodedrocytes :ankified:
***** have extensions that wrap around the axons - that's actually all of the myelin in the CNS
***** myelin acts as an insulator for neuronal transmission
***** makes for much smaller, more efficient transmission, and allows for the great number and density of neurons in human brain.
***** myelin is the *white matter*
***** the neuron cell body is the *gray matter*
***** increased myelination is associated with memory and learning
* Oct 26 :ankified:


*** oligodedrocytes cont. :ankified:
***** can wrap around several neurons, but tend to wrap around a single cell when the myelin becomes thicker - which happens as the specific axon becomes more active.


***** can be divided into 4 types according to how many neurons they can wrap around, and how thickly
*** schwann cells: :ankified:
***** also create myelin, but wrap around one axon only
***** occur in the peripheral nervous system


*** satellite cells :ankified:
***** also occur in the peripheral nervous system


***** act like astrocytes in the CNS - provide support for neurons' cell bodies.


*** impaired myelin: :ankified:
***** will cause a smaller signal to arrive at the synapse
***** can be caused by inflammation attacking the myelin. this is a disease that develops along one's life -  demyelination
***** dysmyelination - a genetic impairment, defective structure and function of the myelin
*** microglia :ankified:
***** soma size < 10 umeters


***** about 20% of glial cells


***** belong to the immune system
***** maintain the sanitation and health of the brain's environment


***** can be activated and then proliferate and migrate to areas of injury or infection
***** microglia proto-cells "move into" the brain before the erection of the BBB, and then rest there and produce the microglia of the adult brain.


***** currently looks like all the markers on the surface of microglia cells are also on the surface of macrophages.
***** "microglia are like the macrophages of the brain"
***** the normal state of the microglia is "surveying"
***** when activated they undergo morphological changes, and produce various factors
***** they can also act like macrophages - swallowing up pathogens and destroying them
***** there's constant communication between the microglial cells and the neurons. the microglial cells "scan" the cells of the CNS to check for problems and pathogens.
***** can produce free radicals (ROS reactive oxygen species) when activated - in order to fight pathogens


***** have important roles in maintenance as well:
******* release neurotrophic factor (like growth factors)
******* clean up dead neurons
******* clean up "garbage" produced by cells
***** several levels of activation:


******* low level, recoverable
******* higher levels may cause  irreversible changes to the cell and they will later die and be replaced by new ones.
***** in development - microglia prune excessive synapse creation.
***** ramified = cell has many "arms"  - the healthy condition


***** deteriorate with age - become less ramified. possible connection to neurodegenerative diseases.
*** ependymal cells: :ankified:


***** create the cerebrospinal fluid - CSF


***** line the different ventricles of the brain.


***** the CSF is very important:


******* absorbs physical shock
******* entry point for substances into the brain
*** the BBB - brain's connection to the periphery (=rest of body) :ankified:
***** four main parts:
******* endothelial cells - line the inside of the blood cells
******* pericytes - cells that provide support on the outside of blood vessels.
******* astrocytes that interact with blood vessels  - perivascular
******* tight junctions - in the endothelial cells, in the archanoid layer, and in the choroid plexus that produces the CSF.


***** entry into the brain - using 400-800 D fluorescent dies.


* Oct 27 :ankified:


*** brain development (embryonic) :ankified:
***** CNS :ankified:
******* brain
******* spinal chord
***** PNS :ankified:
***** from the inside out, three layers of precursor layers: :ankified:


          1. endoterm
          2. mesoderm
          3. ectoderm

***** the nervous system develops from the ectoderm :ankified:


******* process called neurolation


******* on the dorsal part of the embryo
******* at the end of the gastrula phase
******* creation of neural tube - later becomes brain and spinal chord


******* the closing of the tube begins in the middle and proceeds bidirectionally towards the head and tail
******* somites surrounding the neural chord will later develop into the axial skeleton (spine) *and* the attached muscles.


******* all of the various cells of the brain develop from the neural crest (dorsally to the neural tube) - those that don't migrate into it like the microglia
***** dorsal - close to the back, ventral - close to the front/stomach :ankified:
***** forebrain: :ankified:


******* higher cognition
******* telencephalon develops into the two hemispheres of the forebrain - all of the cortex
******* diencephalon develops into the thalamus and the hypothalamus
***** midbrain :ankified:


******* vision, hearing motor control, sleep and wakefulness, arousal, temperature regulation
******* tectum and tegmentum


***** hindbrain :ankified:
******* cerebelum (small brain)
********* reflexes and movement control, balance
******* pons - transfers information between cerebelum and medula
******* medula obolongata - sensory information, autonomous/reflexes
***** the brain has 4 ventricles, 3rd and 4th are connected by the aqueduct: :ankified:


******* 2 lateral ventricles


***** 3rd is below them
***** spinal chord


******* the lowest part of the 3/5-vesicle stage
******* the chord itself is comprised of gray matter (cell bodies), surrounded again by white matter (axons) of neurons traveling down from the brain - protected by the bones of the spine
******* sensory input - more dorsal :ankified:


******* output - more ventral :ankified:
******* ganglions - connections into the spinal chord in different places.
********* they are located on the dorsal root coming out of the dorsal part of the spinal chord.


********* hubs collecting and sending information to/from different areas of the body
******* CNS: the brain & spinal chord
******* PNS peripheral nervous system:
********* 12 nerves going put of the brain directly (cranial)
*********** connecting directly into the brainstem
*********** related to visual, olfactory, facial, vagus, several more.
********* 31 pairs (left and right) of nerves going out of the spinal chord
********* notchord - precursor of the bones and muscles of the spinal column
* Nov 2 :ankified:
*** Nurogenesis :ankified:
***** the overall number of neurons is pretty much constant


***** there are new connections being created, as well new whole neurons
***** brain stem cells develop into progenitors which go on to develop into one of 3:


            1. neurons
            2. macroglia
            3. oligodendrocytes

***** markers for tracking neurogenesis:


******* BrdU - a thymidine analog
********* incoroporates into the DNA when cells divide.
********* used in cancer patients for following tumor growth, led to finding neurogenesis in regular cells in their brains as well. first discovery of neurogenesis in humans.
******* doublecortin DCX - associated with microtubules


********* expressed only in immature neurons


********* neuronal precursors start expressing it shortly after leaving the cell cycle
********* continue for 2-3 weeks
***** found in birds when learning their songs
***** enhanced neurogenesis in an environment rich with stimuli - in mice.
***** unclear of all the new cells are fated to be neurons


***** "Nature reviews" are recommended
***** astrocytes are involved in neurogenesis
******* send signals that cause cells to divide, then preliminary differentiation, migration and then final differentiation.


******* the signals they send are neurotrophins - a type of growth factor.


******* several kinds of these
******* e.g. BDNF brain derived neurotrophic factor


******* most neurotrophins *don't* cross the BBB
******* 4 amino acids is the upper limit of size for going through the BBB


***** a lot of neurogenesis occurs near blood vessels


***** some GFs affect neurogenesis and angiogenesis as well. angioneurins


***** these processes affect existing neurons as well! sprouting of new axons, increased myelination etc.


***** vascular nich  - TODO expand
***** some bone marrow can possibly change into neuronal progenitor cells
***** most stem cells injected into tissue end up differentiating into glial cell rather than neurons


*** Neurotransmitters :ankified:


***** movement of chemicals across the synapse :ankified:
***** activate receptors on the post-synaptic terminal :ankified:
***** activated receptor cause changes in ion flow in/out of the cell at that area. :ankified:
***** deploarization -> more likely to cause action potential :ankified:


***** hyperpolarization -> less likely to cause action potential :ankified:


***** small molecular weight :ankified:
***** fast acting :ankified:
***** multiple types can be active in the same synapse :ankified:
***** more than one receptor sub-type :ankified:
***** the response is tissue specific :ankified:
***** can be excitatory, inhibitory, or both :ankified:
***** overall neurons are negatively charged :ankified:
***** neurotransmitter activity: :ankified:

            1. release
            2. bind
            3. transduction (firing along the dendrite)
            4. reuptake

***** inactivation of NTs - mechanisms: :ankified:


******* reuptake by the releasing neuron - to be reused later.
******* diffusion - out of the synaptic cleft
******* degradation by enzimes that prevent th NT from binding to its receptor
********* e.g. acetylcholinesterase breaking down acetylcholine into choline and acetyl
******* reuptake by glial cells
***** mechanism of action: :ankified:


******* bind to a receptor on an ion channel and cause it to open
******* bind to a receptor that has G-proteins bound to it on the inside:
********* they become phosphorilated and start a chain reaction that ends in ion flow as well.


********* much slower than directly binding to ion channels.
***** pharmacology: :ankified:
******* most drugs that work on the CNS work on neurotransmitters
******* can alter many aspects (synthesis, packaging, release, reuptake, receptor function)


******* can be divided into blockers and modulators
******* endogeneous ligand vs agonis vs antagonist ligands
* Nov 9 :ankified:
*** Glutamate :ankified:


***** the most common NT in the brain
***** it's an amino acid! (it can go through the BBB)


***** five pathways of activation: the cortico-cortical pathways


******* connection within the cortex
******* modulation of activity deeper in the brain
***** many diseases are related to deficiency in glutamate related mechanisms.
***** excitatory NT.


***** small
***** affects very quickly
***** must also be evacuated quickly from the synaptic space
***** two kinds of receptors, both are ion channels:


******* nmdar


******* ampa
******* mGluR (metabotropic glutamate receptor) - coupled to G-proteins


********* G-proteins trigger cascade that activates ion channels
********* some mGluR are activating, and some are inhibitory
********* these receptors are also found on the pre-synaptic neuron


************* to help remove glutamate from the synaptic space
***** open-channel blockers


***** astrocytes have the ability to absorb glutamate, converting it to glutamine which is absorbed by neurons to be converted back to glutamate


***** it's important to absorb glutamate quickly, because over excitation can cause too much calcium to enter the cell, which can trigger apoptosis


***** astrocytes can also release the glutamate in order to create controlled damage to cells around in case there's a pathogen like a virus that infects neurons.


***** several drugs affect glutamate, mostly for dealing with glutamate toxicity - to prevent over-excitation.
******* release blockers
******* receptor blockers
*** GABA :ankified:


***** it's an amino acid!  (it can go through the BBB)
***** the main inhibitory NT in the CNS


***** makes the neuron more negative - allowing more chloride to enter the cell.


***** glutamate is a precursor to GABA. another way to get rid of too much glutamate


***** GABA can also be converted to glutamate through the citric acid cycle
***** the conversion beteen the two is dependant on vitamin B6


***** 2 kinds of receptors:


******* GABA A  - ion channels


******* GABA B - bound to G-proteins - which opne ion channels eventually
***** when glutamate and GABA are out of balance it may cause increased anxiety


***** benzodiazepines such as valium bind GABA receptors - that's how they operate as relaxants (they're GABA Agonists)


***** alcohol can also bind and activate GABA receptors.
*** Acetylcholine - Ach :ankified:
***** excitatory and inhibitory effects


***** CNS *and* PNS
***** it's an acetic acid!


***** along with glutamate - the most common NT in the brain
***** the most common NT in the PNS


***** related to skeletal muscles


***** related to the sympathetic and parasympathetic systems
***** produced in the brain from acetyl-CoA (from glucose metabolism) + cholin which is transported over the BBB especially.


***** synthesized by
***** inactivated by acetylcholinesterase (hydrolyses it)
***** 2 kinds of receptors: (named after toxins that selectively activate them)
******* nicotinic - ion channel
******* muscarinic - G-protein


* Nov 10 - fill
* Nov 16 :ankified:
*** Alzheimer's disease :ankified:


***** 80%-90% precision  in diagnosis
***** a severe loss of gray matter in the hippocampus


***** AD hurts the cells' *soma* not dendrites
***** hurts "place cells" as well - hence a problem with orientation in AD patients
***** no cure so far - only a slowing down
***** decrease in glucose metabolism
***** not a genetic disease per se.
***** there are genetic factors that increase likelihood of early onset (30-40 years)
***** there are also genetic factors that increase the risk of late onset
***** molecular symtoms/causes:
******* Amyloid beta
********* may be due to beta amyloid (Abeta) forming oligomers/plaques which sink and accumulate into deposits in neurons - which have been show as toxic


********* increase in cleaving proteins creating the Abeta from the beta precursor which is a part of the cells membrane and is important for synapse creation.


********* why is Abeta bad?
*********** these deposits can increase the rate of entry of calcium into the cells - causing apoptosis eventually
************* by binding to glutamate receptors
************* or by preventing glia cells from reuptaking glutamate from the synapse
*********** may hurt the cells membrane
*********** may bind to receptors and change the signal trasnduction and change the effects inside the cell
******* TAU protein - also implicated


********* creats scaffolds for microtubule tracks that go out into axons, and also stabilize the cell's structure


********* hyper-phosphorylation of TAU disintegrates the microtubules


******* cholinergic pathway
********* cholin acetylesterase is less active in AD than in healty patients -> less ACh being evacuated from the synapse


********* reduction of cholinergic neurons
******* Glutamate
********* increased glutamate in synapses


********* NMDA receptors
***** treatment?
******* acetylcholinesterase inhibitors - used to stop Ach destruction thus -> create more ACh


*** Dopamine - parkinson's disease :ankified:
***** affects the CNS and the PNS as well


***** tyrosine (amino acid) is a precursor
***** tyrosine synthesized from phenylalanine


***** created outside the brain
***** travels to the brain and there used as a precursor to dopamine
***** dopamine can later be transformed into other NTs
***** tyrosine -> L-Dopa -> dopamine


***** that's why they give L-Dopa to parkinson patients
***** 2 receptor types


******* D1 - stimulatory
******* D2 - inhibitory
******* both are G-proteins


***** 80% of dopamine is in the pars compacta (in substantia nigra) in the brainstem


***** cells are dark (nigra) because of neuromelanin - a dopamin polymer
***** motor control in the striatum thought to depend on a balance between cholinergic cells (stimulatory) and cells with D2 receptors (inhibitory)
***** Parkinson's disease


******* decrease in the amount of cells manufacturing dopamin
******* hurts motor function in various ways
******* not genetic per se
******* some relation to family history
* Nov 23 :ankified:


*** ions
***** recommended  books:
******* neuroscience: exploring the brain/mark f. barry
******* Principles of neural science/eric r. kandel
***** relevant pages for this lecture:
******* chp. 3 - barry
******* chp. 6,7 - kandel
***** since the membrane is made of lipids, ion can't get through without channels.
***** different amounts of ions on both sides create an electrical potential difference.
***** the inside of the cell id more negative than the outside
***** we take the outside potential to be zero. and so the inner potential is -65mV -  -70mV


***** potassium, K+:
******* has a much higher concentration _inside_ the cell than out.


******* is positive, so when it leaves the cell due to concentration gradient, the membrane potential becomes negative, and pulls it back in.


***** sodium, Na+:
******* has a much higher concentration _outside_ the cell than in.


******* is positive, so when it enters the cell due to concentration gradient, the membrane potential becomes positive, and pushes it back out.


***** Nernst equation


        $E_{ion}  = \frac{58mV}{z} * log([ion]_{out}/[ion]_{in})$
         - where z is the charge of the ion

***** Goldman-hodkin-katz equation:


        $V_{membrane} = 58mV * log(\frac{K_{out} + (P_{Na}/P_K)Na_{out} + (P_{Cl}/P_K)Cl_{in}}{K_{in} + (P_{Na}/P_K)Na_{in} + (P_{Cl}/P_K)Cl_{out}})$

***** permeability ratios (physiological):   $P_k:P_{Na} = 1: 0.04$


***** the concentration gradient is maintained by Na/K pump:
******* lets 3 Na ion out, and lets 2 K+ ions in.


******* it hyperpolarizes the membrane - making it overall 1 charge more negative per every transfer.


******* Oubain is a natural toxin that stops the pumps and _depolarizes_ the membrane


******* requires ATP!
***** the resting potential of an ion is determined by the concentration gradient and permeability (also the charge)


***** overall, the membrane potential is determined mostly by potassium and sodium (chlorine has. a small effect)
*** currents
***** patch clamp
***** $I = \Delta V*\gamma$
***** positive current = positive ions going out of the cell = negative ions going into the cell = current that hyperpolarizes the membrane


*** IV curves
***** how current through the membrane changes with the membrane potential
***** linear
***** what can we learn from IV plots?


        - conductance ($\gamma$): this is given by the slope of the line.
        - reversal potential, $V_r$, what's the voltage at which the current that goes through the channel becomes positive/negative?
          + this is an indication of which ions pass through it.
          + e.g. if $V_r = 0$ we can deduce that both positive and negative ions pass through it, so it's non-selective.
          + we can test if a specific ion goes through it by putting it in an environment with a lot/a little of that ion, and checking if it changes $V_r = 0$
        - $V = 0$ is actually the voltage at which the current is $0$  - which is the resting potential (if the channel is specific to one ion) or the averaged resting potential (if several ions can go through)

* Nov 30 :ankified:
*** channels
***** voltage dependent
******* $\alpha$ subunit


******* Sodium channels
********* 4 domains, each 6 transmembrane segments, connnected by cytoplasmatic parts
********* "P-loops" - connect segments 5 and 6 - wholly contained in the membrane
********* the 4 P-loops are what constructs the hole itself
********* segment 4: "voltage sensor" many Arg+ and Lys+ AA (charged amino acids)
*********** rises up (out) when the voltage rises from -65 to -40
******* Calcium channels
********* 2 AA changes to Ca+ channels
******* Potassium channels
********* same $alpha$ subunit, but not connected


***** rate of depolarization
******* what determines the rate of depolarization?
********* passive electrical properties
********* properties of voltage-dependent channels
********* cell geometry
******* square current -> exponential (root) increase in voltage


******* membrane as a capacitor
******* channels as resistors
******* in the beginning of the current the membrane becomes progressively more charged, until some maximal potential is reached (the membranes capacitance)
******* for larger membranes, the rate of changes is *slower* - it takes longer to accumulate more charges, that are required to charge more membrane area.


******* so smaller cells respond quicker than larger ones.


******* the capacitance of the membrane decreases the rate at which the cell responds
******* time constant $\tau$: the time required to reach 63% of the maximal voltage.


********* $\tau = R * C$
********* R is the channels' resistance
********* $V_t = IR(1-e^{-t/\tau})$
******* propagation of current along dendrites/axons (passively) - channels are leaks, the more channels/the longer the distance, the less voltage change at its end.
***** Action potential
******* it's a current of Na+, sodium, ions into the cell.
******* causing massive depolarization
******* ~1-2 ms long


******* -65 mV -> ~ +40 - +50 mV


******* resting -> rising -> ovrshoot (above zero mV) -> falling -> undershoot  (after-hyperpolarization)
******* hodgkin Na+ experiment - TODO elaborate
******* hodgkin voltage clamp - Ionic currents following depolarization pulse
********* with TTX - no 1st phase of inwards current (i.e. it meant that is a sodium current)
********* TTX affects only the voltage dependent sodium channels - doesn't affect the resting potential.


********* with TEA - no outwards current, it's a potassium current.


******* downwards current = negative current = Na+ current inwards = depolarizing current.
******* upwards current = positive current = K+ current outwards = hyperpolarizing current.
******* in the 1st phase the conductance of the membrane to sodium rises (so the the current grows), then drops, and the current drops with it.
* Dec 1 :ankified:
*** voltage clamp vs current clamp


***** clamp == the thing we can set to a desired value.
***** why is there an inside current when we give a deploarizatory voltage?
***** voltage clamp lets us see which channels are being opened at which voltages.
*** currents during AP:
***** Na current inside
***** then K current outside
*** inactivation of Na channels (cf. *de*-activation):
***** ball and chain mechanism - cytoplasmatic ends of the channel move into the channel and close it off after some time.


***** after inactivation the channel returns to "deactivated" (=normally closed) state
***** rate of AP in the brain: 10 - 100Hz -> we need each AP to be over and done with as fast as possible. that's the reason for the channels' inactivation.
***** (absolute) refractory period: Na channels are still inactivated, and another AP is not possible.
***** (relative) refractory period - shortly after the first AP some of the Na channels are still closed, so the excitability of the cell is still low - we can get small and short APs
***** the excitability recovers slowly, not linearly
*** AP is a positive feedback loop:  depolarization -> open Na channels ->inward Na current -> deploarization


*** what determines AP threshold?
***** both Na and K channels open when the voltage rises


***** Na channels open at a greater rate than the the K+ channels, the higher the voltage, the greater the difference between the number of Na and K channels.
***** at the beginning, the balance between Na and K currents and channels is such that at low voltages the overall current is hyperpolarizing.
***** the point at which inwards Na current is greater than outward K current - so the overall effect is actually depolarizing and starts the positive feedback loop.
*** AP propagates along the axon - from myelin segment to the next == saltatory conduction
*** nodes of ranvaier between myelinated areas. high concentration of channels


*** lack of myelin - such as multiple sclerosis - causes a massive reduction in AP, so by the time it gets to the synapse, it doesn't activate it strongly enough for the signal to pass well.


* Dec 7 synapses, NT release, Ca+ channels & blockers :ankified:
*** CNS synapses:
***** synaptic cleft ~50 um
***** active zone in the pre synaptic membrane
***** PSD - post synaptic density: area of dense receptors and other proteins on the post synaptic side, which form a semi rigid structure.


*** AP causes calcium to enter the synaptic trerminal area, which causes the vesciles to travel to the membrane and fuse with it.
*** the duration of release of NT depends on the rate of calcium leaving the synaptic endplate/button/bouton


*** NMJ - neuromascular junction
***** the post synaptic side is not flat, has invaginations


***** they reach deep into the cell to enable calcium to enter quickly into the area of cell where the actin and myosin fibers are (those are being activated by the incoming calcium - causing the muscle to contract)


***** nicotinic Ach receptors are located at the top of the invagination.
***** voltage dependent channels are located at the bottom, nearer to the cell's center.
***** the activation of the voltage dependent channels depends on the Ach receptors
***** Ach is removed from the synaps by Ach-esterase
******* breaks it into acetic acid and esterase
******* cholin being transported back into the pre synaptic neuron
***** nerve gas binds to AchEsterase - too much Ach in the synapse - causes spasms


***** atropine works on the other receptor - the muscarinic receptor.


******* this receptor is present in the lungs, causes fluid to be secreted into the lungs. atropine blocks that receptor, to prevent drowning
***** Curare blocks the nicotinic receptor - used by native american hunters on their arrows


*** Vesicle life cycle:
***** NT uptake


***** translocation to the active zone
***** docking at the membrane
***** priming (before fusion) the vesicle is now "fusion competent"
***** once Ca+ enters the synapse, fusion competent vesicles fuse with the membrane and NT is released.
***** after vesicles fuse, they undergo endocytosis, to be recycled
***** this also keeps the membrane in the same shape.
***** these steps are all *reversible*.
*** vesicle pools:
***** RRP Readily Releasable Pool (of vesicles)


******* small number maybe ~5%


***** recycling pool ~10% - will be fused
***** most vesicls are in the resting(reserve) pool
******* will only fuse under extream (very high frequency) stimulation
***** sucrose (high concentration) causes fluids to leave the cell, shrinking the actual terminal button, causing the RRP vesicles to fuse (used to meausre the size of the RRP)


***** omega-conotoxin blocks voltage dependent calcium channels, stopping vesicle release, and the connection to the next neuron/muscle


***** Aga IV A also blocker of calcium channels - of another type


*** calcium channels are slower than Na channels, like K+
*** calcium is also highly concentrated outside. once Ca channels open, there's an influx of Ca+, depolarizing the membrane/
*** TEA blocks K+ channles (both voltage dependent and K/Na pumps) - making the falling phase of the AP much slower (the return to membrane potential)


*** Ca resting potential is very positive (>100mV)


* Dec 8 - methods and tools :ankified:
*** electrophysiological
***** capaitance of the membrane using a patch clamp
******* tear the membrane at the patch connection - now the inside of the cell and the inside of the pipette are at the same potential
******* when a vesicle fuses with the membrane. the surface area of the cell grows - and the capacitance grows accordingly
******* after all vesicles in the RRP are released we can measure the overall amount of these vesicles.
******* capacitance over time graph (after stimulus) - the first, steep part is the RRP being emptied. the following slow rise is due to the other pools slowly being primed and released.
******* 
*** optical - fluorescnet method
***** dynamic, we can see it in real time
***** membrane recyclying - FM dyes
***** different dyes have  different attributes
***** all dyes have a hydrophobic end, and a polar head - so they imbed themselves in the outside of the membrane. it's not total, though - there's an equilibrium of dye molecules embeded and floating in the medium
***** the dye gets into the vesicels while they are fused, and carried in with them when they undergo endocytosis
***** we have to wash the color from the environment to see the colored areas
***** summary of protocol - FM dyes:

              - dye the medium
              - intensive stimulus to stain ~all of the vesicles in the terminal (all pools)
              - wash FM out for predetrmined amount of time
              - short stimulus (10 AP/sucrose) - release all the RRP vesicles
              - measure the released amount of vesicles by the amount of dye

* Dec 14 - methods and tools cont :ankified:
*** vesicles undergo enodocytosis and recycling.
*** the RRP vesicles can release and be recycled in a matter of a few seconds (combined electrophysiological and fluorescent tests)
*** molecular mechanisms of vesicle release
***** SNARE complex: docking, priming, fusion
******* 3 protein, zipper like, 1 on the vesicle, 2 on the membrane.
******* tetanus and botulinum - neurotoxins that cleave the SNARE proteins
********* botulinum works on PNS motor neurons - NMJ - preventing contractions commands from going through - creating flaccid paralysis
********* tetanus works on the CNS - hurting inhibitory synapses that would relax the muscles - creating spastic paralysis
********* tetanus enters through the NMJ, transported along the axon, and jumps into the inhibitory synapse from the spinal chord.
***** synaptotagmin - Ca binding, Ca concentration sensor
******* C2 sites - Ca binding areas. when Ca is bound the protein undergoes conformation changes. becomes more tightly inserted into the membrane, and pulls the SNARE protein into the membrane with it.
******* another option: it bends the membrane, lowering the energy required for fusion
******* interacts with SNARE
* Dec 15 - synaptic integration :ankified:
*** synaptic integration - basics of neuronal computation
***** neurons actually do a sort of computation - summing all the inputs from dendrites, and deciding whether or not to fire an AP.
***** 3 types of inputs:
******* excitatory - glutamate
******* inhibitory - GABA and more
******* modulation - 5HT, dopamine, nueropeptides and more.
***** usually a neuron releases just one kind of NT. so it belongs to only one of the above.
***** all neurons have receptors for all kinds of NTs
*** inhibitory synapses are symmetric :ankified:


*** excitatory synapses are asymmetric :ankified:


*** excitatory synapses are found on dendritic spines: bulges and branches on the main dendritic trunk
*** the spines serve to modulate the signal - longer spines mean a greater chance for the signal to decay until it reaches the soma.

***

*** inhibitory synapses:
***** much regulation on GABA receptors:
******* ethanol & valium modulate it so that the channel stays open longer
******* receptors let Cl- into the cell
******* Cl resting potential is ~-66mV
******* internal cl concentration is ~ 10mM
******* during epileptic seizures the internal concentration goes up to 25 mM, which changes the resting potential: it goes up to -40mv, making Cl *leave* the cell, making the synapse deploarizing, i.e. excitatory!
******* so a synapse can move from inhibitory to excitatory depending on the concentrations
*** in NMJ synapses - every AP creates muscle contraction
*** in the CNS we need 50-100 synapses firing into our dendritic tree - each contributing ~ 1mV
*** spatial vs temporal summation
*** large time constant makes summation more probable to create an AP (since the membrane potential falls more slowly, and there's more opportunity for the next EPSP to join it)
* Dec 21 :ankified:
*** pre vs post synaptic inhibition :ankified:


***** temporal summation of E/IPSPs  - if the time constant $\tau$ is greater/the capacitance is greater, then the discharge will be slower and summation will be more effective


***** the duration of AP in the pre synaptic cell is just 1-2 ms


***** timing is important - simultaneous vs 5ms after AP
*** synaptic plasticity
***** STP - short temp plasticity :ankified:
******* time scale: up to a minute


******* single synapse
******* (paired pulse) facilitation
********* change in EPSP between two stimuli


********* origine: presynaptic
********* 20-500 ms


********* Pr - release probability of a given vesicle in response to an AP:


*********** determine whether a synapse will be facilitating or depressing.
*********** high Pr --> depressive


*********** low Pr --> facilitating
********* mechanism:
*********** the total amount of influx is pretty much constant, and the release of Ca has a first short phase and a longer slow 2nd phase.
*********** this causes residual Ca from the first AP during the 2nd AP


*********** this causes a greater overall  Ca+ concentration in the synapse during the 2nd AP.
*********** --> greater release of NT into the cleft
*********** the longer we wait - the less facilitation we see, since there will be less residual Ca.
******* depression
********* gradual weakening of the EPSP


********* 5-100 ms  = higher frequency stimulation
********* presynaptic mechanisms:


*********** depletion of vesicle pool
*********** inactivation of Ca channels
*********** release probability
********* postsynaptic mechanisms:


*********** saturation/desensitization of receptors
*********** higher freq stimuli -> more depression


******* more Ca in the synapse also make it more probable for vesicles to release - effectively increasing the Pr.
********* a lot of calcium can turn the response from paired pulse facilitation into depression.
******* augmentation
***** long term plasticity .
******* LTP - long term potentiation
********* the long term/long lasting  strengthening of a synaptic connection
********* in the hippocampus
*********** important for the transfer from STM to LTM = making new memories
*********** also important for spacial navigation - "place cells"
********* fire together wire together - new links (synapses) between cells during learning
********* synapse specific
******* LTD - long term depression
***** homeostatic plasticity

*

* Dec 28 - LTP cont. :ankified:
*** NMDR receptors (Na+ & asdas Ca+ channels) usually blocked by Mg.
*** activated by repeated APs in the postsynaptic cell, created through the activity of the other kind of glutamate receptors: AMPA (an Na+ channel)
*** NMDA receptors mediate entry of calcium which triggers two kinds of processes:
***** local changes in the synapse
***** activation of protein kinases, which trigger a cascade of processes in the cell
*** both these processes create changes in transcription, which lead to long term changes in the synapse:
***** more AMPA receptors (=AMPARs)
***** addition of AMPARs in "dormant" synapses which have only NMDR receptors
***** increase the conductuance of AMPARs
***** increase in release probability
***** increase in the number of synapses
*** the effects of calcium entry into the cell:
***** early LTP:
******* changes that occur in and around the synapse, they are *not* long term in themselves, they will subside over time without the support of late LTP processes.
******* rapid changes in the structure of the dendritic spines, making them more reponsive
******* activate enzymes (PKC, calmodulin)
******* channel regulation
***** late LTP:
******* calcium dependant protein kinases (CREB) which are transcription factors, and are being transported into the nucleus

*******

*** NMDAR without the blocking Mg has the same IV curve as an AMPAR.
*** the inward current during negative membrane potential is Na+ current, the outward current in positive potential is K+ current.
*** memory formation stages:
***** short term
******* low capacity
******* short lived
***** long term
******* life-time
******* infinite capacity(?)
***** retrieval
******* after retrieval, a memory can be modified

*****

*** from LTP to behavior
***** NMDAR knockout in specific areas in adult animals
******* cre/loxP
******* (in one mouse) insert LoxP sequences around NMDAR
******* cre cuts everything in between the loxP sequences
******* homologous recombination
******* (in another mouse) enter the Cre under the regulation of brain-area-specific promoter  (means this gene will only be expresses in that area)
******* so only in the area where the promoter regulates the cross mouse will have no Nomads
******* wading pool with platform
******* memory of where the platform's location was impaired in transgenic mice
***** new synapses - dendritic spines as the basic unit of memory
******* motor task - grabbing food through slit - check for new synapses
******* new synapses within an hour of learning. changes in spines in motor cortex. many more spines and synapses.
******* the learning was retained even after 4 months without the task (stability)
******* a new task caused the creation of new spines - without disrupting the old ones (shows specificity)
* Dec 29 :ankified:
*** neurogenesis
***** physical activity/exercise correlated with increased neurogenesis after learning
* Jan 4 :ankified:
*** young (= adult) born cells have enhanced LTP, are integrated into the existing neural network, and have a significant part in learning and in memory


*** why do some neurons "belong" to a certain memory, and others to another?


***** if a cell is more excitable than it's more likely to be a part of the memory engram
***** CREB makes the neurons more excitable.
***** making a cell less excitable: adding K+ voltage-dependent channels, makes the threshold when Na+ currents are larger than K+


***** inhibiting Na+ voltage - dependent channels also makes a cell less excitable, for the same reason

*****

*** the visual system:
***** eye --> thalamus lateral geniculate nucleus --> V1


***** the retina:
******* light sensitive cells - photoreceptors


******* connected to bipolar cells
******* connected to ganglion cells
******* connected to the optic nerve


******* there are horizontal cells connecting at the intersections between the layers


******* the light passes through all the layers, hitting the photoreceptors *last*
********* except at the fovea, in the center


******* rods and cones - rods are much larger than the cones, more sensitive to low light.


******* light is absorbed by retinal (source: vitamin A), activates (rhod)opsins - in cones there are three kinds, one for each RGB


******* the fovea
********* in the fovea there's an opening/a depression that exposes the photoreceptors, so light hits them directly
********* mostly cones in the fovea
******* the spatial resolution at the fovia is higher than in the periphery:
********* the connections at the fovea allows for spatial separation: there's a 1:1 connection between a photoreceptor and a gangilion cell, so the information flows into the brain at the maximum resolution available
********* in the periphery, 4-5 photoreceptors are connected to the same gangilion, so we lose resolution
******* receptive field: the area of the world which a given cell responds (alters its firing rate) to
********* circular - a central activating area, and a peripheral inhibitory area around it.
********* the inhibition goes through the horizontal layers either right after the receptors or before the gangilions.
********* this allows for a great resolution/specificity of the cells
* Jan 5
*** receptive field - a measure relating to the nerve, to the activation of ganglion cell.


*** receptive field - the area of the world where a stimulus would elicit a response in a retinal neuron
*** receptive fields in the retina are *round*, and neurons there respond best to points of light.
*** same in the LGN and going into the cortex (layer IV)
*** blind spots: where all the ganglion cell outputs merge into the nerve and leave the eye. at that point
*** optic tracts - information from the left(right) *visual field* goes through the right(left) optic tract.
*** binocular vision starts only after layer IV of the visual cortex - a single cell in level III receives inputs from both cells that are activated by the left visual field and by the right.


*** cells in level IV itself are divided into "occular dominance columns" - areas that are only activated by one side of the visual field.


*** responding to lines:     simple cells


***** they are  not activated by points of light, but by elongated shapes =lines in a specific orientation.
***** this is caused by a line activating specifically the 'on center' area of three retinal cells.
***** are found in layers II & III
***** different angles are distributed along the layer
***** this is perpendicular to the occular dominance columns. so all occular columns (for both eyes, from all areas of space) have a segment that responds to a given orientation.
* Jan 11
*** vision system - cont.
***** neurons in layer IV of the cortex, occipital lobe, V1 are enrvated from LGN (thalamus) neurons
***** "simple cells" in V1 respond to (do summation on-) input from 3 adjacant cells on the retina - that's ho they recognize lines.
***** cortical module: 2 x 2 x 2 mm that has all the information(both eyes, orientation of lines, colors) from a specific small area of the visual field.


***** critical period - great plasticity of the visual system early in development (post natal)
***** if only one eye is active at that period then the entire layer IV of the cortex will gradually become dedicated to input from that eye.


***** at the beginning - information arrives from both eyes in a mix to layer IV, and the separation between the eyes (into columns) develops with time


***** the areas in the cortex respond to synchronized activity from neurons in the same retina - this activity is spontaneous at the very beginning of vision. first from one eye, than from the other.
***** applying TTX (Na channel blocker) to the eyes prevents segragarion, because it inhibits the spontaneous activity that creaets the hebbian (fire together witre together) plasticity in layer IV


*** brain disorders
***** there's no cure for any of the known brain diseases - why?
***** many surrounding problems (regulation, BBB, lack of biomarkers)
***** major issues:
******* lack of in depth understanding of the disorders
******* lack of human-relevant models for research
******* not enough cooperation between academia, industry and politics.
******* 2 types:
********* neurodegenerative - massive cell death (Alzheimer's, ALS, parkison's)
********* neuropsychiatric - social behaviour abnormalities (autism, schizofrenia, bipolar disorder)
******* usually the synapses are the first to be hurt
******* neurodegenerative diseases:
********* aggregation of a monomer, a part of a protein, into an oligomer/aggregate that becomes toxic, or otherwise to hurt the cell
********* at what point does the oligomer becomes toxic, when is it still normal?
********* in Alzheimer's it looks the aggregates are a marker, but not a cause.
******* Parkinson's
********* death of > 50% of the dopamine releasing cells in the substantia nigra
********* aggregates of alpha-synuclein: a synaptic protein
********* the hope is that the aggregates begin a long time before the massive cell death, so we can catch the disease in time.
********* super resolution microscopy
*** Test
***** multiple choice
***** ~40 questions
***** 15 danny, 18 uri
***** a little like the ones in the polls
***** no need to remember equations, no need to enter numbers
***** need to understand the influence of changes in concentration on ion driving forces and internal mechanisms.

*

