:PROPERTIES:
:ID:       20210627T195208.195751
:END:
#+TITLE:Thursday, 04 June 2020 

* טיפול עם נטע :personal:

חתונה, ברית.
זמן של בדיקה אם כל החלקים שלי יכולים להשתתף. 
זה שער.
זו הזדמנות לעשות את הבדיקה הזאת ואולי לעזור לכל החלקים למצוא דרך לבוא גם.
אפשר וחשוב לדבר עם הספק ולשמוע עד הסוף לאן הוא הולך, מה יש לו לומר. לא לפחד לתת לאפשרות ש"זה לא זה" להיות נוכחת כאפשרות אמיתית, לבדוק מה יקרה אם נבטל את החתונה, אם ניפרד.. מה אז? ולשאול תוך כדי - מה מזה קשור באמת לאילת ומה קשור אלי, מה קשור למה שקורה עכשיו ומה למדתי מתישהו בעבר?

* 19:11 אימייל לד"ר ברנשטיין

  שלום ד"ר ברנשטיין, 
  אני מקווה שאני מוצא אותך בטוב. 
  הייתי רוצה להתייעץ איתך, אם אפשר, לגבי התחלת מחקר ומציאת מעבדה להצטרף אליה.
  יש לי תואר ראשון בביואינפורמטיקה מהטכניון (סיימתי ב 2016/17), ואני חושב על
  תואר מתקדם באחד מתתי התחומים של
  מדעי המוח כבר תקופה ארוכה. לאחרונה החלטתי שזה מה שאני רוצה להשקיע בו את השנים
  הקרובות (לפחות) - לעשות MA או למצוא מסלול ישיר לדוקטורט, ואני מנסה להכווין את עצמי למקום שיהיה מתאים לתחומים שמעניינים אותי
  ומלהיב אותי לחקור.
  רוב התחומים האלה נמצאים על איזשהו תפר בין neuroscience פרופר לפסיכולוגיה -
  - תודעה, מה היא, ומה והמקור שלה\איך היא מתבטאת במוח
  - נוירופסיכואנליזה, גם בהקשר של התודעה עצמה, וגם בהקשר של מבנים נפשיים ופנומנולוגיה.
  - מצבי תודעה שונים - במיוחד כאלו שנהיים זמינים באמצעות מדיטציה וחומרים פסיכדלים
  - תחושת העצמי כיישות רציפה וקוהרנטית, האגו והקשר שלו ל default mode network,
    מצבים שבהם תחושת העצמי מתרופפת
  - היחס של העצמי והתודעה בכלל לגוף - אולי גם בהקשר של שיטות סומטיות
  - תופעות פסיכוסומטיות, וההפך - ההשפעה של תנועה ועבודה עם הגוף על מצב התודעה
  - אינטואיציה
  - נוכחות, היות ברגע - וההפך תחושה של ניתוק, או עמימות כלפי המציאות

  עברתי על רשימת הפרסומים באתר של המעבדה שלך, ונראה שיש כל מיני השקות בתחומי
  העניין. חשבתי שאולי יהיה מתאים שאצטרף למעבדה, וגם אם לא, אשמח לדבר ולהתייעץ
  לגבי התחום בארץ.
  תודה רבה, וסליחה על המייל הארוך out of the blue.

  יונתן

* Notes (fleeting)
