:PROPERTIES:
:ID:       20210627T195211.929767
:ROAM_ALIASES: DMN
:END:
#+TITLE: Default mode network
#+ROAM_ALIAS:The Default Mode Network is a network of several areas in the brainstem. 

* Structure

It's composed of multiple areas, with 3 functional hubs:
1. Posterior cingulate cortex (PCC) & precuneus: Combines bottom-up (not
   controlled) attention with information from memory and perception. The
   ventral (lower) part of PCC activates in all tasks which involve the DMN
   including those related to the self, related to others, remembering the past,
   thinking about future, and processing concepts plus spatial navigation. The
   dorsal (upper) part of PCC involves involuntary awareness and arousal. The
   precuneus is involved in visual, sensorimotor, and attentional information.
2. Medial prefrontal cortex (mPFC): Decisions about self processing such as
   personal information, autobiographical memories, future goals and events, and
   decision making regarding those personally very close such as family. The
   ventral (lower) part is involved in positive emotional information and
   internally valued reward.
3. Angular gyrus: Connects perception, attention, spatial cognition, and action
   and helps with parts of recall of episodic memories
([[https://en.wikipedia.org/wiki/Default_mode_network#Anatomy][Source: Wikipedia]])

* The DMN may be the "seat of the Ego"

  [[file:2020-06-16-robin_carhart_harris.org][Robin Carhart Harris]] claims that it's the neural correlate of the Ego.
  He gives several justifications:
  - It's active in theory of mind scenarios, in ruminations, and mental time
    travel (source?) [[file:2020-05-14-self_consciousness.org][Self-consciousness]], [[file:2020-06-16-neural_correlates_of_the_self.org][Neural correlates of the Self]]

* The DMN and psycadelics

  - The connectivity within the DMN deteriorates under psylocybin, e.g. the
    connection between the mPFC( medial prefrontal cortex) and the PCC (posterior
    cingulate cortex)

  - decreased blood flow in PCC under psylocybin, with level of decrease in
    direct correlation to magnitude of experience

  - competition between DMN and TPN (task positive network) breaks down and
    they become more syncronized -> maybe this underpins the collapse of
    self/object differentiation.

