:PROPERTIES:
:ID:       20210627T195256.375897
:END:
#+TITLE: Notes from Feldenkrais classes

* כדי להרגיש רעננים\צעירים צריך שתהיה לנו את התחושה שאנחנו דואגים לעצמנו\אחראים לעצמנו כמו שההורים שלנו היו אחראיים לנו כשהיינו קטנים
* לא אכפת לך אבל אתה מקשיב
* לא לתת לגב התחתון להפריע לתנועה
* עדיף לעשות פעם אחת טוב, גם אם לאט מאוד מאשר 20 פעם לא טוב - כי אז אפשר לעשות עוד פעם אחת טוב, אחרת גם הפעם ה21 תהיה גרועה
* כדי להרגיש רעננים, עוזר לשכוח עוד ועוד דברים
* ממש חשוב להגיע למקום\לתחושה שלא אכפת לנו ממה שמסביב , מהאנשים ומה שהם חושבים עלינו וכו' - זה הכרחי ללמידה.
* לומדים איך להגיע לשם, זה לא מובן מאליו - אפילו לאילת יש רק דקות ספורות של להיות שם בתוך FI.
* לא להתאכזב מזה שצריך להתאמץ ולהגיע לשם, ושזה לא הולך בקלות, עדיף לשמוח מעצם היכולת להיות שם לפעמים.
* דוגמא לזה שתנועות הן התחלות של הרבה תנועות אחרות - הסיבוב של הראש של התינוק כשהוא מחפש את השד קשור לתנועה של התגלגלות אל הבטן
* התנועה של הליקוק שמשתמשים בה בשיעור נועדה לעזור לנו לשחרר כל מיני החזקות - בלסת, בגרון, בצוואר, בבסיס הלשון שמתחבר לעצם החזה
* ה"אי דיוקים" או הסטיות שקורות לנו בזמן שאנחנו מנסים לעשות תנועה מסוימת הם ממש חשובים - ככה אנחנו לומדים דברים חדשים בצורה אורגנית, שמתחברת אל עצמנו ומה שאנחנו כבר יודעים.  ככה אנחנו מגלים דברים חדשים
* מתי דברים לא מתחברים? כשלומדים אותם מבחוץ, כשמישהו מסביר לנו - ככה וככה צריך לעשות כדי להגיע לתוצאה מסוימת.
* לפעמים בתוך FI אנחנו רוצים לתת לתלמיד לעשות את התנועה בעצמו ורק לעקוב אחריו ("להיות דבק")
* לפעמים אנחנו רוצים טיפה להקדים אותו, ואז אנחנו משהו בין לעקוב ולהוביל
* מצד אחד ברור שצריך כוח רצון\אנרגיה\ריכוז\מאמץ נכון בשביל לעשות דברים, מצד שני אנחנו לא רוצים to abuse את זה, הרבה פעמים לעשות משהו בכוח הרצון גורם לנו לא להיות קשובים לעצמנו
* בתנועה הפיכה\רברסיבילית, אפשר לחשוב על זה שכל נקודה בדרך היא בעצם התחלה קטנה, אנחנו כל הזמן מתחילים, ומתחילים ומתחילים, ובכל נקודה אפשר לצאת להרבה סוגים של התחלות
* בזמן FI התקווה שלנו היא שתשומת הלב שלנו, ההבחנה שלנו במשהו, יביאו להגדלת ההבחנה של התלמיד
* כדי להביא את התלמיד להבחנה דקה יותר אנחנו לא עושים חזק יותר - אפשר לעשות כל מיני דברים אחרים. למשל, להביא אותו להתאמץ פחות ולהחזיק פחות, או להדגיש חלק בתנועה שהוא עושה טוב ובקלות כבר כרגע.
* צריך לתת אמון במוח של התלמיד, שהוא יכול ללמוד. ככה גם נמנעים מלדחוף אותו חזק מדי. התלמידים לא טיפשים, ולא יעזור "לצעוק" עליהם. האמון בתלמיד מביא אותו לאמון גדול יותר בעצמו
* צריך לסמוך על עצמנו שמה שאנחנו מרגישים ובוחרים לעשות הוא מספיק טוב.
* יש חוקים - ויש מעבר להם, את מה שחשוב
* חלק מהלמידה הוא ללמוד מתי אנחנו רווים, למדנו מספיק, או שאנחנו סתם צריכים מנוחה.
* זה ממש בסדר לעשות טעויות - וזה הרבה יותר טוב מאשר לא לעשות כלום מפחד שנטעה.
* גם בתוך תנועה שנראה שבסך הכל אין בה הפרדה (דיפרנסיאציה), תמיד יש איזשהו מקום עדין שבו כן יש הפרדה, אפילו טיפה. אפשר לפצוח לתלמיד דלת להגדיל את ההפרדה בתנועה שלו אם נלך ונהיה _עם_ התנועה שלו, _איתו_, שם במקום שיש קצת משהו בכל זאת.
