:PROPERTIES:
:ID:       20211216T123000.771994
:END:
#+title: הספד פייסבוק על אמא

אמא שלי, דומיניק לוי (סהר) איזנברג, נפטרה לפני שבוע וארבעה ימים. היא הייתה חולה מזה כשנה. התפרצה אצלה מחלה ניוונית של המוח, והמצב שלה הלך והדרדר במהירות מעוררת חלחלה בחודשים ובשבועות האחרונים.
אהבתי אותה אהבת נפש, בצורה הכי מלאה ושלמה ולא מסובכת שהכרתי בעצמי.
כל כך הרבה ממה שיש בי קיבלתי ממנה  - בדברים ובתכונות שאני אוהב ומעריך, במה שמעורר בי חוסר סבלנות, בסדרי העדיפויות לגבי מה חשוב בחיים (להנות ממה שאפשר, לאכול טוב, ללמוד, להעריך דברים טובים ויפים, לשתות תה בכל שעה), ואיך טוב ונכון להיות כאדם (להיות נדיב, רך, לא מתנשא, לא ביקורתי מדי, לא דוגמטי ,לראות קודם כל את הטוב והאנושיות באנשים אחרים), וכמובן לאהוב ולהעריך אומנות. בחלק מהדברים יש לי עוד דרך ארוכה לעשות, ורק עכשיו שהיא כבר לא פה אני מבין כמה הרבה עוד בעצם היה לי ללמוד ממנה, ועד כמה היא השאירה לי כוכבים ללכת לאורם.

אני כותב, ואני כל הזמן מודע לזה שאני עוד לא באמת מתמודד או מכיר בהיעדר שלה, קשה לי לאפשר לעצמי להתמסר לעצב שמרחף מעלי ומאחורי, למרות שיש בי חלקים  שבאמת רוצים בזה.
אני מבקש להודות מקרב לב לכל החברים ששלחו הודעות, וצלצלו, ובאו ללוות אותנו בלוויה ובשבעה - מעולם בחיי לא הרגשתי עטוף ואהוב כל כך, וזו הייתה תמיכה עצומה שהייתם שם. אני מרגיש שהתברכתי בנוכחות שלכם, ואני אוהב אתכם ואתכן מאוד מאוד.

אמא שלי הייתה חוקרת מבריקה של תולדות האומנות והפילוסופיה של האסתטיקה ומעשה היצירה, ומרצה אהובה מאוד. זה היה מרגש ומשמח לשמוע כמה מהתלמידים שלה שהגיעו לשבעה מספרים על הקשר שהיהי להם איתה. אם הכרתם אותה ותסכימו לכתוב עליה כמה מילים מזכרונכם, או להפגש ולדבר, או אם יש לכם הקלטות כלשהן שלה משיעורים שהעבירה, אני אשמח ואודה אם תצרו איתי קשר. יש בי רצון לאסוף את החומרים האלה לדף או אתר שיהיו זמינים כדרך לזכור אותה.
אפשר לשלוח למייל: jonathan.sahar@gmail.com, או ליצור קשר בפייסבוק או בטלפון: 0543517049.
