:PROPERTIES:
:ID:       20211025T130617.692999
:END:
#+title: טיפים להעברת שיעורי פלדנקרייז
- tags :: [[id:20210627T195219.786272][tag: פלדנקרייז]]

* שיעורי ATM
*** אנחנו מקווים, במקרה הטוב, שהבנאדם ירגיש יותר טוב מתוך העשייה שלו בשיעור - אבל זה לא "על" המורה. המורה לא שם כדי להציל אותו.
*** לא כדאי להתחיל שיחה עם תלמיד חדש בבירור של מה לא בסדר איתו ודורש התייחסות מיוחדת
    זה גורם לו להתרכז במה שלא עובד, וזה בדיוק הפוך ממה שאנחנו רוצים, וגם כי זה יוצר אולי ציפייה שאנחנו הולכים לתקן אותו.

*** (אם יש תלמיד עם תנועה שקשה\כואב לו לעשות):
:PROPERTIES:
:ID:       20211115T111632.454196
:END:
    כדאי למצוא שיעור שיש בו הזדמנות לעשות תנועה דומה, קרובה, משהו מסביב - אבל לא אותה בדיוק
*** לא לעשות המון מאותו דבר:
        לא לעשות או לגרום לתלמידים לעשות יותר מ 20-25 פעמים את אותה תנועה - זה משעמם ומעייף שכלית, וגורם לעשייה עם פחות ופחות תשומת לב ועניין. במקום - לעודד אותם לעשות וריאציות, למצוא מיקומים אחרים לידיים\רגליים, לעשות בדמיון
*** איך יודעים שמישהו התחיחל להתחבר ולהתעניין? הוא מתחיל לעשות לאט
*** להסביר דרך דוגמאות
    כדי להסביר משהו למישהו הכי טוב למצוא דוגמא קונקרטית שקשורה אליו ולתנועה שלו כרגע שיש בה מן העניין שרוצים להסביר
*** להתחיל ממה שיש:
    זה ממש עקרוני לבוא אל המקום שבו האיש נמצא ואל מה שהוא עושה באופן טבעי וקל כרגע
    לא להיות ביקורתיים כלפי כל הדברים שהוא עושה "לא טוב" - הם כנראה משמשים אותו יפה בסהכ רוב הזמן
    להשתמש במה שהוא עושה בקלות כדי ללמד אותו על מה זו קלות ואיך היא מרגישה
*** ללמוד איך זה מרגיש שמשהו הוא קל, ולהשתמש בזה כדי להפוך עוד תנועות לקלות.
*** לא לתת שיעורים עם פיתולים לאנשים עם פריצות דיסק בגב התחתון!
*** רצף להתחלת שיעור:
    - לשכב על הגב ולשים לב באופן כללי למה מרגישים ואיך שוכבים
    - לשים לב לעקבים, למנח שלהם על הרצפה, להשענות שלהם
    - לעשות תנועות קטנות סביב האמצע - לראות איך [[id:20210627T195203.782380][תנועה עוזרת לתחושה]]
    - לשים לב לנקודת האמצע\הנייטרלית איפה שהיינו באופן טבעי
    - לחפש מקום בגב שנשען או משהו ולראות איך הוא משתנה עם תנועת העקב
    - לעשות אותו דבר עם הראש - להקשיב איפה הוא נשען ואז לעשות תנועה קלה מסביב לזה.
      - לבדוק שוב את המקום בגב, איך הוא משתנה ביחס לראש

* שיעורי FI
*** מאמר שאומר שתנועה פסיבית לגמרי יותר טובה מתנועה אקטיבית כדי ללמוד תנועה מסוימת [cite:@wongCanProprioceptiveTraining2012]

* אנטומיה\כללי:
***  אפשר להשעין את הירך לתוך המפרק שלה, לתוך האגן, לתת לו לקחת את המשקל שלה, כשרוצים להרים את הרגל
*** מה עושה הראש בזמן שמעבירים משקל מרגל לרגל (עולה ויורד), ואיך השכמות מחליקות על הגב?
