:PROPERTIES:
:ID:       20211108T172724.895041
:END:
#+title: Ideomotor Theory
Ideomotor approaches intend to explain how people are able to perform goal-directed movements without having direct conscious access to or any conscious knowledge about their own motor system (Shin, Proctor, & Capaldi, 2010; Stock & Stock, 2004).
The ideomotor principle that is thought to provide this explanation claims that carrying out movements is accompanied by a learning process that integrates the motor patterns driving the movement with the sensory information that the movement generates, such as the proprioceptive experience ofmoving and the visual changes of hand position, or the kinesthetic and auditory effects of touching a piano key.
Note that part of the integrated re-afferent information refers to the movement itself, i.e., the bodily experience, while another part refers to the way the movement changes the environment.


So actions can be considered to be represented by codes of the sensory effects they have been experienced to produce.

Note that the active use of such past knowledge for the control of future action can be taken to turn the knowledge into a prediction (or at least some kind of expectation that the previously produced action effect will again be produced by carrying out the action), which renders the ideomotor approach functionally equivalent to present predictive-coding models.

* See also
[[id:20220509T170423.463536][Forward model]]
