:PROPERTIES:
:ID:       20210627T195301.723323
:END:
#+TITLE: Notes: Lab Meetings

* 18.5.21
*** Shanks paper about errors in unconscious effect studies
***** Reliability
******* reliability affects the observed correlation
******* reliability measure: split-half reliability
********* divide the data in two in some way and check that the correlation is high between the measure that you're testing in both halves
******* reliability measures the consistency of the data we got
******* crucially, for *objective measures* we need the measures to have some variability to begin with, otherwise there won't be a change that can be correlated.
******* we measure reliability on the entire range of conditions (e.g. from very short SOA to very long), so we get variable responses. and we use that as a good enough measure of reliability in the range of conditions that we actually care about.
***** critique of reliability in "contextual cueing" experiments
******* conscious/unconscious vs explicit/implicit measures

*******

* 25.5.21
** lucid dreams
* 8.6.21 - ASSC preps
*** questions that may appeal to liad:
***** Is consciousness needed for X?
***** dissociating access and phenomenal consciousness
:PROPERTIES:
:ID:       20210608T171046.401239
:END:

*****

* 21.6.21 - paper about unconscious priming
*** really strange that they refer to the sensitifity of subjects to the prime in the _indirect_ task, when the prime is long gone
*** the general claim: in UC processing studies there are actually two phases of reasoning:

      - the effect of the congruency of the prime is evidence that it's processed with greater sensitivity in the indirect task
      - this greater sensitivity is evidence of UC processing
      And they claim that congruency effects are not actually an evidence of greater sensitivity

*** does their argument amount to "we need more power in testing that the prime is really invisible"?
*** is it less relevant to us, since we don't rely on response times (RT)?

***

