:PROPERTIES:
:ID:       20210627T195305.397142
:END:
#+TITLE: Reading thesis papers (how-to + ideas)


* Keep questions in mind
- what are the prominent theories?
- what are the main areas of interest?
- what are the major questions?/ What is this paper asking about laterality in the AC?
- Who are the important researchers?
- What are the main methodologies?
- How is this question related to laterality in the AC?

* what do I want to know?
- which parts of the auditory processing pathway have a laterality dominance?
- processing which types of auditory content show a laterality dominance?
- what's the effect (motor control) producing a sound on the perception (experience) of that sound.
- what's the effect (motor control) producing a sound on the processing (brain activity) of that sound.
- is there a differece in the processing (in the AC) between the cases where the ear is on the same as the hand and where the it's on the opposite side?
- what else was done with MVPA in this area? Did anyone else try to decode something from AC activity?
-
