:PROPERTIES:
:ID:       20211013T102247.620711
:END:
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+title: Class notes: Consciousness, behavior, and brain (1071473701)

* 13.10.21 - intro
*** admin
- a day before the class send notes about paper - to force us to read actively
  - *not* an abstract
  - can be a point we disagree with/, a thought it brought up, or something we didn't understand.
  - a serious methodological problem (*not* something like - there weren't enough subjects etc.)
- an straightforward exam - 6/8 open questions about terms and ideas from the course.
  ***

*** general/history
- states of consciousness
- hans berger - EEG of different sleep states
- background consciousness - level/state (wakefulness/dreamin/drugs, hypnosis)
- contents of awareness - conscious perception. This is what most research is about.
- differentiate conscious vs unconscious perception.
- mostly vision studies - best understood, most developed in terms of brain realestate
- crick and kph manifesto 1995
- divorce from philosophy, intuitive definition is not enough.
- they identified two problems: lack of good definition, and no access to another person's consciousness (observability of consciousness)
- we can't count on introspection - like not seeing something I need to clean around the house
- if we rely on report for studying consciousness we always have the problem of memory - consciousness as remembered present
- johansosson's choice blindness - consciousness creates a story that explains the current situation
- NCCs - subtractive method - the brain while consciously processing vs UC processing
  - assuming that consciousness is "added" to the rest of activity
  - more things change in the brain when consciously viewing something (attention, memory)
    ***

  - a localizationist  approach to consciousness
- we are conscious only of representations, not reality
*** many theories of consciousness - try to explain what happens when we are aware and when we are not aware.
- how do we measure consciousness?
- what is the function of consciousness?
- NCC
*** basic problems in demonstrating UC processing
- need two measures:
  - was there processing?
  - was it conscious?
* [[https://drive.google.com/open?id=1K7DEN-HCwwgwt4Xv0oW_jPHVAg8-ILm9&authuser=jonathan.sahar%40gmail.com&usp=drive_fs][overgaard paper]]
*** notes:
- do they mean to say that there is no UC processing for stimuli that's truly not seen?
- they saw that for all scores above "nothing seen at all" the guesses about which form where significantly above chance.
- they say themselves that there were actually very few instances of nothing seen at all in terms of colors and positions
- it looks like in previous experiments (binary seen/unseen) the proportion of "glimpsed" trials brought up the performance of the "nothing seen" to make it seem as if there's UC processing to a larger degree than there actually was.
- what is the definition of UC? Is a glimpse enough to be considered consciously aware?
- they claim that many studies (binary) about UC processing are therefore invalid
- argue against dichotomic deinition of conscious perception - and for a "more elaborate measure of subjective states"
- contrastive analysis - asking a subject if he saw the stimulus
- creates dicotomy - they suggets giving more freedom than yes/no
- shift from subjective report to behavioral consequeces
- problem with behavior as "objective measure": it only reflects a certain, maybe small, unknown, part of the conscious experience
- subjects usually do report some sort of experience if given tjhe chance to say so
- sidis' experiments is th gold standard for a nuanced measure of consciousness
- the article is mostly about the authors system for testing awareness in a more nuanced way
- UP works even in anaesthesia (word completion after waking up)
- generally - UP works, that is, stimuli that are not perceived consciously do reliable affect behavior
- even in brain injury/disease
- blindsight
- orientation of rectangle in binoccular rivalry - kolb and braun seem to measure metacognition and not awareness
- residual phenomenality - a graded measure of awarness, of having an experience (after an injury)
- we need to distinguish between clearness of the stimuli and the certainty we have about the contents
- they did an experiment of masking different shapes and colors, and let subjects label for themselves how clearly they saw them.
- then they interviewed the subjects, and understood what their labels were, and generalized the 4 point scale from there.
***  my take on it:
        The first thing that struck me was that the authors spent a very large part of the paper explaining the justification for the new scale they proposed. I thought that the idea of consciousness (of a stimulus) being "all or nothing" is clearly an oversimplification that would benefit from more "resolution": even as a matter of day to day personal experience, it's very common to have a notion of "glimpsing" a sight or sound, and to have the vague content of that something float around in our mind, or to have a fleeting thought, idea, or intention not quite in the conscious front of our minds.
        I also think that it's a question of definitions - what do we consider unconscious processin? Is it really required that subjects be completely unaware of seeing anything at all? I would argue that, since conscious experience is by definition a matter of phenomenology, we have no choice but to take the subjects' word for what they saw: if they don't recall their experience having any content (relating to the stimulus) at all, then to my mind, they did not consciously process it. In that respect I'm not sure I agree with the writers' criticism of the papers previously published in their field - saying that they did not really demonstrate UC processing, because trials with glimpses bumped the score for trials labled as unconscious.
    It's interesting to investigate what kinds of more complex information we can process at the two lower levels, and where do they differ - can we read, do math, infer context? If we present stimuli that are more crucial for our survival, are they processed better at lower levels than regular stimuli? Do they penetrate consciousness better - i.e are they experienced more strongly at the same display duration?

* 20.10.21
*** SDT
- describes desicions in the face of uncertainty
- there are internal and extrnal noise sources: stimulus is noisy, and internal background activity noise.
- sensitivity - d`
  The difference betwen the peak of noise and noise+signal curves
  The smaller the number - more overlap - the harder to tell the difference between noise and signal.
  A measure of "hits" vs "false alarms".
  Sensitivity is a measure of where my criterion of decision (=beta) is located
- using SDT as a measure awareness - if the subject can discriminate in force choice, then he was aware
- want to get rid of the criterion = subjectivity (if we only report being aware based on stringent categories)
*** measuring awareness:
- if we use d' as a measure of awareness (which is what we used to use for a measure of UCP), we need to find another measure for UCP
- indirect measures: using primes, after them stimuli, and tasks regarding the stimuli only.
- to show UCP: we need to see effect of priming *and* get d' = 0 (no discrimination in force choice)
*** dissociation:
- between awareness and processing
- need two separate measures: one for each. Need one to show there was no awareness and one to show processing has occured
*** objective meaures:
- advantage: the most sensitive for conscious awareness - if there's just a little bit, it will show it
- disadvantages:
  - the exhaustivness problem: it tests the availability of information to conscious decision, but only specific aspects of the stimulus. What if we process different aspects in different times?
    - we could ask if subjects saw anything at all - and check d'
  - we need a lot of samples to get d'=0 reliably
  - the basic idea is that the task block and the awareness block are the same - so the awareness block is a good measure:
    - but the state of mind is not the same: less engagement in the awareness block, mixed exposure showed far greater awareness of the prime than traditional way
    - in the mixed experiment they couldn't get an effect in the task when the priming was short enough to get people not to see it in the mixed awareness block
*** direct/indirect mismatch
- we want not to make the criterion of awareness too hard in relation to the level of information we are testing in the indirect measure: if we want to check the effect of the meaning of words shown, then it's too much to set the criterion as "not seeing anything at all", its enough that subjects can't discriminate between something that has to do with with the meaning - like ?was it positive/negative?""
- defining awareness of a stimulus as information being accessible (though not available!) To conscious processing/decision making.
- PAS
* [[file:/mnt/g/My Drive/Msc neuroscience/semester 1 2021/Consciousness and the brain/week 3 -Lamy_Alon_Carmel_Shalev_2015.pdf][Lamy 2015]]
*** main underlying idea:
Independence from consciousness -it's not the same as  showing that a process can be done with no awareness of the stimulus. We need to show that it's done as well without awareness as it is done with it.
*** task:
      - search for T shape in a specific color, colored prime can be same or different color
      - search for T shape in color among gray shapes prime can be same or different color
*** main findings:
      - same location benefit is "truly" independent of consciousness - you get the same improvement in RT with or without perceiving the prime consciously
      - same location cost it dependent on consciousness - you only get the cost if you consciously perceive the prime
*** main conclusions:
      - the same location cost is a good way to indirectly and objectively measure awareness
      - same location benefit is a bona fide example of a process that is independent of consciousness
*** questions:
- is it a specific enough measure? By measuring performance we're measuring a lot of other processes that happen after we've "consciously processed" the stimulus
- what can we do with the new indirect measure of conscious perception (testing for same location loss)?
*** my take:
    I liked the idea of defining independence from awareness in a way that fits our intuition and common sense better than "some performance" but I'm not sure how to dissociate this better performance from other types of processing that go on after "mere perception" - maybe conscious perception adds more benefits, like learning from experience, which  preparing for motor action and anticipation of where to look, both of which can also be products of the longer processing time that is another byproduct of the longer exposure that makes the prime consciously perceived.

    This makes me think that  an interesting (though unrelated) experiment would be to have a fixed relation between the prime and the target - say the target is always opposite the prime - and check if we can learn this connection without awareness.

    I'm not sure I understood how you would use same location cost as a measure of awareness - would that be instead of forced choice blocks, in order to verify the invisibility of the prime? Is that an improvement because it's even more direct?
* 27.10.21
***  Q1: "to what extent does a certain mental operation depend on sconscious perception?"
- Liminal prime paradigm (Lamy)
- it's better to compare UC processing to conscious processing.
- independence of consciousness like in the paper.
- we're asking - if it's a small effect without awareness and a much larer effect with awareness - is it still true that we can "process" this stimulus without awareness?
- we need to use a liminal stimulus - otherwise we're not comparing apples to apples (the stimulus strength is greater for longer stimuli)
- intra-subject paradigm
- most subjects are either 20%-80% or 80%-20% aware-unaware of the prime
- we look at the aware and unaware trails separately  - we have different amounts of trials per subject, so we need mixed-linear statistical models, ANOVA would give distorted results because it won't assign the correct weight to each subject
*** Q2: are conscious and unconscious processing qualitatively different
      - we want to see double dissociation
      - "process dissociation procedure"
        - critisizes the idea that task and process are the same: until now we treated objective measures for unconscious processes and subjective measures for conscious processes, but actually both tasks benefit from both kinds of processess
        - this is called a "fascilitation paradigm"
        - we need a procedure in which each process affects oppositly the performance in each task
        - not finding an effect can always mean that the measure is not sensitive enough - the interesting question is "is there an alternative explanation if we do find an effect"
        - we mwasure UC processing by "failing" the exclusion task
        - this makes sure that we are not aware to such a degree that we can't choose not to use the information.
        - the baseline is the proportion of subjects choosing the word e.g "taboo" without the prime
*** divided attention vs full attention task:
    - adding numbers that are not masked
    - see that attention affects conscious perception but not unconscious perception
    - look at the bottom table only (table 4)
    - not enough for double dissociation they did not find a manipulation that affects unconscious perception but no conscious perception
    - available information (affects our behavior, processed without awareness) vs accessible information (accessible to consciousness, may be recalled, we can choose whether to use it or not)
* 3.11.21
*** how do we interpret semantic processing
        - want to know - how high/complex is unconscious processing?
***** Marcel et al.:
        1. Test stimulus display time for conscious perception
        2. Prime with some word and test the probability of completing a stem with a word that is in the same semantic field.
        3. not a stable effect, did not reproduce
***** greenwald:
      - semantic priming too, but just need to respond yes/no or pleasant/unpleasant about the target
      - quicker response, short response window
      - results: shorter RT for congruent prime and target (e.g both pleasant)
***** 3rd experiment - want to distinguish between spreading of activation and other possible mechanisms:
        - word vs word/non word
        - manipulations:
          - when both are words, can be related or unrelated
          - check RT with congruency (both words or both nonwords)
        - check response priming vs semantic priming:
          - congruent -> fast response = response priming
          - semantically related -> fast response = semantic priming
          - results: strong response priming, no semantic priming
***** Dehaene et al. 98
        - check semantic categorization for ad-hoc rules without awareness
        - decide if target is < or > 5, target is a digit/number, prime is also digit/number
        - shorter RT for congruent condition regardless of digit/number coupling
        - early motor activation - ERP
        - --> we conclude it must be semantic priming: we apply the task (greater or smaller than 5) to the unconscious prime
        - highly reproduced
*****  David et al. - criticism of Dehaene:
        - same experiment with words that are not semantically related, task - press with R/L hand if target is large/small
        - a problem with Dehaene - there is a small number of stimuli, so we *learn* the association between the low level features of each stimulus and the appropriate motor response, instead of processing the meaning.
        - this means we should be seeing an effect of practice: there should be more of a difference between congruent and incongruent conditions (the motor effects of the prime become stronger because they become better at recognizing its features.) - which they did find!
        - --> when the target set is small we rely on low level features, when it's large, we must use semantic processing.
        - in a different experiment they primed with CAPITAL LETTERS and a large set, and showed that letters are processed abstractly - we have the concepts of the letters, lower-case 'a' is the same as upper-case 'A'.
***** Van den Bussche et al. 2009
        - animal vs nonanimal
        - compare large and small target set
        - results: for the small set there was *no* semantic priming - because the processing was perceptual/low level
        - for the large set there *was* semantic priming - because they forced semantic processing
        - problem: very small effect!!! (average difference of 8-9 ms
***** conclusion:
        - currently very weak evidence for unconscious semantic priming
