:PROPERTIES:
:ID:       20220527T174708.570708
:END:
#+title: שיעורי פלדנקרייז


* 16-4-1 שכיבה-גב-בטן - חיבוק עצמי

* 2-2-4 שכיבה-גב שעון - הכנה לשעון
רגליים עומדות בפיסוק נוח, ניצבות כמו עמודים, בלי כוח
לגלגל אגן אחורה וחזרה
לשים לב לתנועת הראש - הראש הולך עם האגן

לגלגל אגן קדימה וחזרה - נוצרת קשת בגב, אפשר להכניס בה יד.
להעביר את יד ימין ואת יד שמאל מתחת לגב ככה
עמוד השדרה נמשך כלפי מטה

להסביר על השעון - 12 למטה לכיוון עצם הזנב, 6 למעלה לכיוון החגורה

לעשות 6 - 12 דרך המרכז הרבה פעמים ולשים לב לראש

לנוח

רגליים עומדות

להשעין את האגן על שעה 3, ככה שהמותן השמאלית מורמת, ואז לעבור ל 9
לעושת את זה הלוך וחזור
לשים לב שברך אחת הולכת קדימה יותר מהשניה כל פעם
תנועה של גלגול והטיית האגן סביב ציר עמוד השדרה
לשים לראש שעושה אותו הדבר

לנוח

לעשות מעגל מלא מסביב לשעון, להתחיל משעה 6 למעלה וללכת שמאלה נגד כיוון השעון
ללוות אותם במילים, בקצב התנועה
ולהפוך את כיוון הסיבוב
להקשיב לראש
להקשיב לאף

לנוח

לשבת עם ברכיים הצדה וכפות רגליים נוגעות זו בזו, ידיים אחורה
לגלגל את הגן 6-12
לשים לב לשבת על עצמות הישיבה
לתת לבטן לצאת ולבלוט חגיגית כשעוברים ל 12
ובחזור הבטן נכנסת

לעשות את התנועה ימין ושמאל
כל פעם ברך אחרת מתקרבת לרצפה
והראש בלי תנועה
להיעזר בידיים

לנוח

לחזור לאותה תנוחה
לעשות מעגלים מלאים
עוברים על עצם הישיבה השמאלית מסביב ועל עצם הישיבה הימנית מסביב
יותר ויותר קל ופשוט

לנוח

לעשות מעגלים בכיוון השני

לנוח

להתרומם על מרפקים ואמות
רגליים כף אל כף
לעשות 6-12 במצב הזה
לעשות מעגלים
לנוח רגע
לעשות מעגלים בכיוון השני
לנוח רגע

מרפקים ואמות, רגליים עומדות מפוסקות.
לעשות מעגלים בשני הכיוונים, ולהקשיב לדרך שהאגן נח בה על הרצפה
בכמה מקומות הוא נוגע ברצפה
לתת לראש להצטרף

לנוח

להשאר בשכיבה ולעשות מעגלים ככה
להיעזר בעקבים אם צריך
כפות הרגליים גם עושות מעגלים
לשים לב שיש שעות על השעון שנהיו פחות נוחות, לשים לב אילו הן
לאפשר לראש לנוע
לשים לב לשעות שלא מגיעים אליהן בנוחות


להעמיד חזרה את הרגליים ולראות אילו שעות חוזרות להיות יותר ברורות
ושוב לפשוט את הרגליים ולראות מה נהיה קשה

ושוב להעמיד את הרגליים ןולעשות מעגלים בכיוון ההפוך
ולישר אותן לראות מה נהיה פחות ברור

לשכל רגל ימין מעל שמאל ולעשות מעגלים ככה
זה יהיה שונה מאוד מקודם, לשים לב מה שונה
יהיה חלק במעגל שבו זה קשה במיוחד - איזה חלק? למה קשה שם?

להחליף רגלייפ ולעשות שוב

להעמיד שתירגליים מפוסקות ולעשות מעגלים ככה
לשים לב כמה זה יותר נוח, ואיפה מרגישים פתאום תנועה ברורה

להצמיד את הסוליות ולעשות בשני הכיוונים

לנוח

להשאר בשכיבה ולהעמיד רגל אחת
לעשות מעגלים ככה ולהקשיב להבדל
להחליף כיוון
רגל שניה

ולנסות שוב עם רגל אחת שכולה מעל השניה, בשני הכיוונים

ולעשות פעם אחרונה עם שתי הרגליים עומדות

ולשכב במנוחה, ולהקשיב לדרך שבה האגן מונח, והחזה

לקום לטייל

* 10-3-2 שכיבה-גב שיכול ברכיים ופיתול גו ואגן

* 18-4-4 שכיבה-גב שיכול ברכיים ותנועות עיניים תואמות

לשכב על הגב, לשים לב לאיזורים בגב שנוגעים ברצפה

רגליים עומדות, לשכל את ימין מעל שמאל
להטות את הברכיים ימינה וחזרה
לתת לראש להצטרף לתנועה
לעצום עין שמאל ולהביט בעין ימין בזמן שמטים את הברכיים ואת הראש ימינה.
לשים לב למה רואים בדרך, ולשים לב לרציפות של התנועה: האם היא חלקה? האם יש איזורים שמדלגים עליהם?
לשים לסנכרון בין העיניים והראש: האם הן מקדימות או מאחרות אלרי תנועה הראש?

לעצום את עין שמאל להביט רק בימין.
להשמיך להטות את הברכיים ואת הראש, לעשות שהם ינועו בהתאמה.
לעשות ככה שהתנועה תהיה חלקה ונעימה - אם צריך, לעשות יותר לאט, יותר קטן.

לשים לב לתנועה של הגלגול של עמוד השדרה, איך הוא מתגלגל מצד לצד, לעקוב אחרי עמוד השדרה מלמטה למעלה - בגב, בחזה.

לנוח

לחזור לאותה תנועה, עם עין שמאל עצומה
לשים לב לעשות תנועה כמה שיותר אחידה וחלקה עם העיניים, להבחין איפה זה לא יוצא חלק.

עכשיו לעצום את עין ימין ולהביט בשמאל
להקשב ליחס בין העין והברכיים, לקשר בין המהירויות והזוויות שלהן.
להקשיב ליחס בין תנועת העין ותנועת הראש - האם העין מקדימה או מאחרת את הראש?
לעשות ככה שהעין תלך בדיוק עם הראש.

לחזור לשים לב לתנועה של עמוד השדרה, איך הוא זז אחרת ביחס לתנועה שהייתה עם עין ימין פקוחה?

להמשיך עם שתי העיניים פקוחות.
 לשים לב שהעיניים מסתכלות על אותה נקודה, ושהן מטיילות יחד עם הראש.
לנוח

להעמיד רגליים, ימים בשיכול מעל שמאל
להטות ברכיים ימינה ולתת לראש ולשתי העיניים להצטרף.
להחזיק עם יד ימין בפרק כף יד שמאל או במרפק ככה שיד ימין תוכל למשוך את יד שמאל איתה כשהברכיים נוטות ימינה.
להקשיב לצלעות
להקשיב לעמוד השדרה ולראש.
האם התנועה בעמוד השדרה קורית בכל החוליות בבת אחת או שיש בה הדרגתיות?

לנוח

לחזור לשכול ימין מעל שמאל ולהטות את הברכיים ימינה וחזרה, אבל הפעם להטות את הראש והעיניים שמאלה.
להבחין בהבדל בעמוד השדרה

לעשות אותו דבר, אבל רק עם עין שמאל פקוחה

לעשות אותו דבר רק עם עין ימין פקוחה
להקשיב להבדל מהעין השניה

לעשות אותו דבר עם שתי העיניים, ולשים לב לחלקות של תנועת העיניים, ולסנכרון שלה עם תנועת הראש.

לנוח

לעשות אותו דבר - עם שתי העיניים, וגם עם היד הימנית שמושכת את השמאלית כמו קודם.
יד הולכת עם כיוון הטיית הברכיים
להקשיב לצלעות בצד ימין.

לקום ולעשות סיבוב, לעמוד במקום ולהפנות את המבט ימין ושמאל.
להבחין בהבדלים בין הצדדים.
