:PROPERTIES:
:ID:       20220913T173829.326027
:END:
#+title: Time management for mortals

"What I really need to feel complete is..."" Is always waiting in the wing to remind me of all the activities, hobbies and pursuits that I'v been neglecting.

It's a version of FOMO

* The joy of missing out
Missing put is literally inevitable
it's baked into the human condition, it's guaranteed to miss out on most of the things that can be done.


* Accepting our finitude
every choice we make, is a also a choice to give up on all the othe choices that were possible (other
jobs, other partners, othe paths of life)

Taking responsibility for giving up on all of that is really anxiety-inducing.

We do all sorts of things to avoin\d feeling that anxiety,:
    - we make ourselves believe that we do what we do because we have to, because there's no other choice, because it's foolish and dangerous to change, etc.
    - we numb ourselves with distractions and stimuli
    - being obsessed with efficiency

      My/our obsession with efficiency is a way to not acknowledge our finitude, it's a way to believe that we actually /can/ do everything (or will be able to if we'll be efficient enough)

Better to treat life not like a huge Todo list, of things to do before we die - instead, like a menu of things we can choose from.

We're hanging onto the illusion of not being finite, and to fantasies of perfect outcomes, by keeping all our options open all the time, procrastinating, and not committing to things (which can fail once we commit to them).

Procrastinating etc. Are not fun, but they do give a (false) sense of controlling our time. We can't controlwhat the future will hold, whether we fail etc. But we can control what we are going to watch next on youtube...






* Deciding
Forget decision fatigue

practice desicions, decide more throughout the day

"making more desicions" = make more _conscious_ desicions

Making conscious desicions on a daily basis helps because it eaches us to enter more fully ino life, when we make a decision we have to give up on our fantasies and commit to something imperfect, but real.

Making desicions that  we can't back out of makes us happier, because it makes us live here and now, and lets us let go of thinking about all the other options that we might have chosen.

Not deciding is always a decision too!

* Task management
Why are we so drawn to multitasking?
Staying engaged in one thing often feels contraining, boring, or somehow painful.
We do it because it's another way to escape or finitude.

It's better to practice working /sequentially/ about things, stop yourself from jumping to other task, learn to tolerate the anxiety of working one thing only.

Limit your work in progress: choose one main goal in each major project (home, lab/studies, fitness)

It's always going to feel unpleasant

Work with two todo lists: one with /everything/ you need to do, and the other with just a few, which you are actually committed to doing. Lets say 10 items.
Can't add more items untill you free one by finishing it.

It's a basic condition of life - that most of what we want/need to do, we're not actually doing right now.
With this strategy we're just choosig consciously which of them are left outside.
