:PROPERTIES:.
:ID:       20220527T174708.570708.
:END:.
#+title: שיעורי פלדנקרייז
.
.
* 16-4-1 שכיבה-גב-בטן - חיבוק עצמי.
.
* 2-2-4 שכיבה-גב שעון - הכנה לשעון.
.
* 10-3-2 שכיבה-גב שיכול ברכיים ופיתול גו ואגן.
.
* 18-4-4 שכיבה-גב שיכול ברכיים ותנועות עיניים תואמות.
.
לשכב על הגב, לשים לב לאיזורים בגב שנוגעים ברצפה.
.
רגליים עומדות, לשכל את ימין מעל שמאל.
להטות את הברכיים ימינה וחזרה.
לתת לראש להצטרף לתנועה.
לעצום עין שמאל ולהביט בעין ימין בזמן שמטים את הברכיים ואת הראש ימינה.
לשים לב למה רואים בדרך, ולשים לב לרציפות של התנועה: האם היא חלקה? האם יש איזורים שמדלגים עליהם?
לשים לסנכרון בין העיניים והראש: האם הן מקדימות או מאחרות אחרי תנועה הראש?

לעצום את עין שמאל להביט רק בימין.
להמשיך להטות את הברכיים ואת הראש, לעשות שהם ינועו בהתאמה.
לעשות ככה שהתנועה תהיה חלקה ונעימה - אם צריך, לעשות יותר לאט, יותר קטן.

לשים לב לתנועה של הגלגול של עמוד השדרה, איך הוא מתגלגל מצד לצד, לעקוב אחרי עמוד השדרה מלמטה למעלה - בגב, בחזה.

לנוח

לחזור לאותה תנועה, עם עין שמאל עצומה
לשים לב לעשות תנועה כמה שיותר אחידה וחלקה עם העיניים, להבחין איפה זה לא יוצא חלק.

עכשיו לעצום את עין ימין ולהביט בשמאל
להקשב ליחס בין העין והברכיים, לקשר בין המהירויות והזוויות שלהן.
להקשיב ליחס בין תנועת העין ותנועת הראש - האם העין מקדימה או מאחרת את הראש?
לעשות ככה שהעין תלך בדיוק עם הראש.

לחזור לשים לב לתנועה של עמוד השדרה, איך הוא זז אחרת ביחס לתנועה שהייתה עם עין ימין פקוחה?

להמשיך עם שתי העיניים פקוחות.
 לשים לב שהעיניים מסתכלות על אותה נקודה, ושהן מטיילות יחד עם הראש.
לנוח

להעמיד רגליים, ימים בשיכול מעל שמאל
להטות ברכיים ימינה ולתת לראש ולשתי העיניים להצטרף.
להחזיק עם יד ימין בפרק כף יד שמאל או במרפק ככה שיד ימין תוכל למשוך את יד שמאל איתה כשהברכיים נוטות ימינה.
להקשיב לצלעות
להקשיב לעמוד השדרה ולראש.
האם התנועה בעמוד השדרה קורית בכל החוליות בבת אחת או שיש בה הדרגתיות?

לנוח

לחזור לשכול ימין מעל שמאל ולהטות את הברכיים ימינה וחזרה, אבל הפעם להטות את הראש והעיניים שמאלה.
להבחין בהבדל בעמוד השדרה

לעשות אותו דבר, אבל רק עם עין שמאל פקוחה

לעשות אותו דבר רק עם עין ימין פקוחה
להקשיב להבדל מהעין השניה

לעשות אותו דבר עם שתי העיניים, ולשים לב לחלקות של תנועת העיניים, ולסנכרון שלה עם תנועת הראש.

לנוח

לעשות אותו דבר - עם שתי העיניים, וגם עם היד הימנית שמושכת את השמאלית כמו קודם.
יד הולכת עם כיוון הטיית הברכיים.
להקשיב לצלעות בצד ימין.

לקום ולעשות סיבוב, לעמוד במקום ולהפנות את המבט ימין ושמאל.
להבחין בהבדלים בין הצדדים.

לשכב על הגב, רגל שמאל משוכלת על ימין
להטות את הברכיים שמאלה ולתת לראש להצטרף
לשים לב להבדל בין זה לכל מה שהם עשו קודם בצד השני
להקשיב לגלגול של הראש
לעשות קטן שיהי מתואם עם הברכיים
להקשיב לשקיעה של האגן לרצפה

לעצום עין ימין ולעשות אותו הדבר
לנסות שהיא תחליק על פני שדה הראייה בהתאמה עם הראש

לעצום עין שמאל ולעשות אותו הדבר
להקשיב להבדל

לנוח קרוב

לעשות אותו דבר עם שתי העיניים
להקשיב לעמוד השדרה

להפנות את הראש ימינה בזמן שהברכיים נוטות שמאלה
להקשיב לעמוד השדרה
לנוח

להעמיד שוב את הרגליים, שמאל על ימין
להחזיק ביד שמאל את מרפק או את פרק יד ימין
להטות את הברכיים שמאלה תוך כדי שמושכים בעדינות את המרפק, הראש מתגלגל שמאלה
להקשיב לצלעות העליונות על הרצפה

לעשות אותו דבר אבל לגלגל את הראש ימינה, הפוך לכיוון הגוף
לשים לב להבדל בצלעות

לנוח
לקום להסתובב

לנוח

לשכב על הגב, להעמיד את הברכיים
להרים את האגן באוויר ולהניח את כפות הידיים זו על זו איפשהו מתחת לחזה, מרפקים על הרצפה
לשכול רגל ימין מעל שמאל ולהטות את הברכיים ימינה
הראש מצטרף
להבחין בהבדל בתנועה עכשיו שהחוליות החזיות לא יכולות להשתתף - יש יותר תנועה בחוליות המותניות והצווארית
יש הפרדה בין התנועות של  החוליות
להקשיב לפיתול של עמוד הדרה באגן עם תנועת הברכיים ובעורף עם תנועת הראש

להחזיר את הידים מתחת לחזה ושוב להטות את הברכיים ימינה.
לשים לב לתנועת העיניים, שתהיה חלקה ומתאומת עם הראש
להקשיב לצלעות בצד ימין, איך הן נדחפות יותר למעלה מקודם
להקשיב לעמוד השדרה

לנוח

לעשות אותו דבר לצד השני ־ רגל שמאל שכולה על ימין

לנוח

לשכול רגל ימין על שמאל, לחבק את הגוף, ידיים על השכמות
להטות ברכיים וגוף ימינה, וראש ועיניים שמאלה
להחליף ידיים ורגליים ולהטות את הברכיים שמאלה


לנוח
לקום לטייל

* ממוקד
רגליים עומדו
