:PROPERTIES:
:ID:       20220510T093739.255872
:END:
#+title: Thesis knowledge base
- [[id:20220929T131701.371065][tag: thesis]]
* ניסוים קודמים במעבדה
*** הניסוי של רזניק מ 2014:
נגינה בפסנתר בתוך ה fMRI, כל פעם יד אחרת, פידבק לשתי האזניים. + תנאי פסיבי של הקשבה בלבד
  1. הגברת פעילות בעיקר באיזורים אודיטוריים STG בתנאי האקטיבי ביחס לפסיבי
       - ההגברה הייתה יותר משמעותית בקורטקס הקונטרלטרלי ליד (כלומר יד  איפסילטרלית לאוזן,  קורטקס אודיטורי איפסילטרלי לקורטקס המוטורי)
  2. בהתאם - סף השמיעה היה נמוך (=טוב) יותר באוזן האיפסילטרלית ליד (ככה שהקורטקס האודיטורי יוצא קונטרה ליד ואיפסי לקורטקס המוטורי)
  3. הנחתה בפעילות בעיקר באיזורים פרונטליים בתנאי האקטיבי ביחס לפסיבי
  4. חיבוריות (functional connectivity) - ה STG הקונטרלטרלי היה האיזור שהיה הכי מחובר לקורטקס המוטורי בזמן נגינה.
      חיבוריות נמדדה באמצעות [[id:20220623T181007.555618][PPI]].

מ [cite:@reznikLateralizedEnhancementAuditory2014] - ניסוי אודיטורי


*** הניסוי של רזניק מ 2015:
משתתפים לחצו על כפתור ביד ימין כדי לייצר צליל. קצב הלחיצות היה משתנה.
השוו את העיבוד בקורטקס האודיטורי בין התנאי האקטיבי לפסיבי וראו שיש הגברת פעילות בקורטס השמאלי בתנאי האקטיבי - כלומר יד איפסילטרלית לאוזן
ההבדל בין התנאים היה בקורלציה לקצב הלחיצות, ובלי קורלציה למידת הפידבק הסומטוסנסורי מהלחיצה (רצו לשלול את המעורבות של הקלט חושי מוגבר שגם הוא תוצר של הלחיצה, כמו הפעולה המוטורית עצמה)

מ [cite:@reznikEnhancedAuditoryEvoked2015]

*** הניסוי השני של רזניק מ 2015:
ניסוי התנהגותי.
מראה ש self generation של צלילים מייצר אפקט אחר כתלות בחוזק הצליל:
    - עבור צלילים שקרובים לסף השמיעה, מייצר אפקט של הגברה (amplification)
    - עבור צלילים מעל סף השמיעה מייר אפקט של החלשה (attenuation)
מ [cite:@reznikPerceivedLoudnessSelfGenerated2015]

*** הניסוי של בתאל מ 2020
ניסוי fMRI, הדלקת "אור" כל פעם ביד אחרת - פעולות מוטוריות שונות עם אותה תוצאה חושית (ויזואלית):
1. יש מודולציה של איזורים סנסוריים ושל התפיסה עצמה, עבור תוצאות חושיות של פעולות שלנו לעומת גירויים שנוצרים בצורה חיצונית.
2. המודולציה תלויה בלטרליות - האם הקורטקס המוטורי והסנסורי הם באותה המיספרה, או לא. המודלציה חזקה יותר בתנאי האיפסילטרלי
3. אפשר לזהות איזו יד גרמה להופעת הגירוי (הדלקת האור) לפי הפעילות בקורטקס הויזואלי
מ [cite:@buaronVoluntaryActionsModulate2020]

*** הניסוי של הדר:
ניסוי התנגותי - נבדקים למדו לנגן בפסנתר עם יד ימין אם עם יד שמאל, עם פידבק לאוזן ימין או לאוזן שמאל
1. עבור יד שמאל ראו למידה טובה יותר עם פידבק לאוזן הקונטרלטרלית ליד.
2. עבור יד שמאל ראו cross education טוב יותר בתנאי הקונטרלטרלי

מ [cite:@deryLearningAudiomotorSkill]

* עבודות אחרות
*** ניסוי של סאטו: [cite:@satoActionObservationModulates2008]
בא להראות שהאפקט של הנמכת התגובה האודיטורית קשור יותר להפתעה מאשר ל efference copy ע"י זה שמראה את האפקט גם ב action observation

*** תיאוריה: theory of event coding
    [cite:@hommelTheoryEventCoding2019]
    מתאר  מסגרת רעיונית סביב הideomotor theory שבה יש מבנים קוגניטיביים בשם event codes שמתארים כם פעולה וגם את ההשלכות החושיות שלה - כלומר פעולות והשלכות הם אזרחים שווי זכויות במודל הזה.
