:PROPERTIES:
:ID:       20221101T201114.552992
:END:
#+title: צריך לשים לב על מה משבחים ילדים

למשל: אם משבחים ילדים על זה שהם חכמים או מוכשרים - אלו דברים שאין להם שליטה עליהם, וזה גורם להם להתרכז  בהצלחה\אי ההצלחה שלהם כמדד לכמה הם טובים ואהובים, ולפחד מכישלון. לעומת זאת - אם משבחים אותם על המאמץ שהם השקיעו, על הנחישות שלהם על זה שהם נהנו מהתהליך וכו' - אלה דברים שיש להם שליטה עליהם, ובפעם הבאה שהם יתקלו באתגר, הם יתרכזו במסוגלות שלהם ולא בצורך להצליח.

כשלא עסוקים בכישלון, אז יש פתח למשחקיות ([[id:20211031T095718.918456][Playfulness]]), שהיא אחד הדברים הכי חשובים.

""תפקידו של השבח הוא להניח את היסודות לפעם הבאה שבה הם ירצו לנסות להשיג דבר מה. איזו מחשבה אנחנו רוצים שתעבור בראש של ילדינו כשהם יתמודדו עם אתגרים בעתיד: שהצלחה היא התוצאה היחידה שראויה להוקרה? או שאנחנו מעריכים את החוסן הנפשי, העבודה הקשה והנחישות שלהם?

* ערכים קשורים:
- [[id:20220906T115951.361603][הורות]]
- [[id:20221101T202054.799455][אנחנו רוצים לטפח דפוס חשיבה לא מקובע אצל ילדים]]

* מקורות:
- https://www.haaretz.co.il/family/howtotalkwithkidsabout/2022-11-01/ty-article/.premium/00000184-2e69-db86-a394-aeeda9290000

- Mueller, C. M., & Dweck, C. S. (1998). Praise for intelligence can undermine children's motivation and performance. Journal of Personality and Social Psychology, 75(1), 33–52. https://doi.org/10.1037/0022-3514.75.1.33

- https://youtu.be/J-swZaKN2Ic TED talk
