:PROPERTIES:
:ID:       20230108T225437.671128
:END:
#+title: שיעורי פלדנקרייז שעשיתי
- tags ::  [[id:20210627T195219.786272][tag: פלדנקרייז]]

* 17-4-4 שכיבה-גב - ברך מושכת את הכתפיים לישיבה מזרחית
שיעור של ענת מסגמנט ספטמבר 22'
ממש נהניתי. למדתי משהו על לתת לשקע שבין עצמות הבריח, מעל עצם החזה, לשקוע ולהיות רך. למדתי שם איזה קשר בין זה לבין היכולת של הראש להשען על עמוד השדרה, ואפילו יותר למטה עד הרגליים. כאילו הריכוך שם היה איזו חוליה חסרה באפשרות להעביר את המשקל של הראש כלפי מטה ולהישען.

*** הוראות:
- בישיבה מזרחית מרכינים ראש וזוקפים אותו.
    איך זה מערב את כל הגוף?
    איך זה מערב את האגן? איך הוא מתגלגל?
    איך עמוד השדרה בא לתמוך בראש בכל זווית\שלב בהרכנה?

- מגלגלים את האגן קדימה ואחורה.
    איך שאר הגוף מתארגן?
    איך הראש מגיב? איך עמוד השדרה תומך?

- בשכיבה על הגב כל פעם מעמידים רגל אחת, ומניחים עליה את הקרסול של הרגל השניה.
    מטים את כל המבנה הזה שמאלה וימינה, כאילו לקרב את הברך לרצפה וחזרה, ואז פעם את הברך ופעם את כף הרגל.
    להקשיב לעצמות הבריח

- בשכיבה על הגב כל פעם מעמידים רגל אחת, ומניחים עליה את הקרסול של הרגל השניה.
    עכשיו מרחיקים את הברך קדימה, הרחק מהראש.
    מה יותר קל, בשאיפה או בנשיפה?
    מה קורה בעצם החזה? בצלעות? יש שם הרבה שינוים והתאמות שצריכים להתרחש.
    איזו מן תנועה האגן עושה?
    איזו תנועה עושה המותן הנגדית לרגל כדי לתת לברך להתרחק?  והמותן של אותו צד?
    ועצמות הבריח שוב?

- בשכיבה על הגב כל פעם מעמידים רגל אחת, ומניחים עליה את הקרסול של הרגל השניה.
    מחזיקים ביד הנגדית את הרגל מתחת לברך והיד השניה מאחורי הראש.
    היד תלויה כמו חבל מהברך, ישרה, יש מתח רק באצבעות - כמו בטיפוס.
    מרחיקים את הברך קדימה, הרחק מהראש, ונותנים ליד ולכל הזרוע לבוא עם הברך.
    מה זה עושה עכשיו בכל המקומות?

- עכשיו קצת להרחיק וקצת לקרב את הברך כדי לברר עוד את התנועה בעצם החזה ובעצמות הבריח.

- מתחילים לחפש את המקום שבו הכי קל להרים את הראש עם היד.
    לחפש השענות של הראש על עמוד השדרה והצלעות.
    להקשיב לתנועה של עצמות הבריח, החיבור ביניהן ועצם החזה.
    לחפש את הרמז לראש להתרומם.
    אם נותנים לראש להשאר מאחור - אחכ יותר קשה להרים אותו, יש לו מסלול יותר ארוך לעשות. להתחיל מוקדם.

- עושים אותו דבר, אבל עם ידיים הפוכות ־ היד מחזיקה את הברך בצד שלה, לא הנגדית.

- בשכיבה על הגב כל פעם מעמידים רגל אחת, ומניחים עליה את הקרסול של הרגל השניה.
    מחזיקים את הרגל בשתי הידיים - אחת מתחת לברך והשניה בכף הרגל.
    עכשיו מרחיקים שוב את הברך קדימה, הרחק מהראש, ומחפשים איפה ואיך קל להרים אותו.

- עושים אותו הדבר, אבל מחזיקים עם שתי הידיים מתחת לברך.

- בשכיבה על הגב כל פעם מעמידים רגל אחת, ומניחים עליה את הקרסול של הרגל השניה.
    מחזיקים את הרגל בשתי הידיים - אחת מתחת לברך והשניה בכף הרגל.
    מטים את המקל הזה של הרגל ימין ושמאל, כאילו להעמיד את הרגל פעם על הברך ופעם על הכף
    בהתחלה עושים בלי להטות את הרגל העומדת, ואז עם להטות אותה.

- מנסים את ההרחקה של הברך וההרמה של הראש בכל מיני זוויות לאורך המסלול הזה.

- דגש לגבי הרחקת הברך ־ מרחיקים אותה כאילו רוצים לקרב אותה אל כף הרגל העומדת, ככה זה מונע ממנה ללכת הצידה\החוצה.

- מנסים שוב את ההרחקה של הברך כשיד אחת נתלית מהברך (זו שבאותו צד) והיד השניה מחזיקה מאחורי הראש.
