:PROPERTIES:
:ID:       20210627T195321.265088
:ROAM_REFS: cite:brownUnderstandingHigherOrderApproach2019
:END:
#+TITLE: Notes: Understanding the Higher-Order Approach to Consciousness
#+ROAM_KEY:
- tags ::[[file:2021-05-19-hot.org][ HOT]], [[file:2021-05-19-tocs.org][TOCs]]
- keywords ::

:PROPERTIES:
:Custom_ID: brownUnderstandingHigherOrderApproach2019
:AUTHOR: Brown, R., Lau, H., & LeDoux, J. E.

* Notes
*** a theory of phenomenal consciousness - aims to explain subjective experience. like [[file:2020-09-30-iit.org][IIT]].
*** a first order representation of something is not enough for a conscious experience
*** a first order representation can be used by the brain, but non-consciously
*** if we're not aware of being in some first order state - then we are definitely not aware of the contents of that state
*** to be conscious of something we need to have some minimal self-awareness of our mental functioning, we need a meta-representation of the first order representation, need to be aware that we are aware of something. - this is the *higher order representation*
*** GNW doesn't require this awareness - so it's a first order theory
*** various theories are "part" of HOT:
***** dispositional HOT: the mere availability of the first order to the higher order representation is enough for consciousness
***** HOTT (higher order thought theories): the higher order state is "thought like"
*** started out as a philosophical theory
*** empirical support:
***** differences in perception are more strongly correlated with "higher level" areas than with sensory areas
***** disruption of higher order activity with TMS/lesions alters subjective experience (but where? in what sense? it's very general)
*** seems to require having a concept /thought for every aspect of conscious experience
*** maybe higher order representations are something like "x is bluer than y"
*** the meaning of "thought" and "self" and "introspection": not a conscious self thinking "I see red", but something more subtle, maybe "subpersonal", i.e. not quite conscious
*** distinction between autonoetic (consciousness of the self) and noetic for maybe describing animal consciousness
*** consciousness != metacognition. we're aware of engaging in a metacognitive effort s.a. saying how confident we are, while higher order processes are not in themselves conscious
*** metagonitive tasks are used in OHT research because it was shown that disturbing PFC activity with TMS disturbs both conscious experience and metacognitive task performance
*** they suggest that metacognition evolved before consciousness and the underlying mechanism was later adapted for it. how does that even make sense? how is metacognition not a subset/requiring consciousness?
*** against GNW: global availability and consciousness are not the same - e.g. in a task requiring to remember several shapes for a period of time before answering a question about them, people who reported to have a visual image of the shapes, and people who didn't had the same rate of success.
***** but this doesn't necessarily mean anything - maybe their ongoing "broadcast" experience was of a different quality? maybe it was broadcast only for the question, and resided in working memory in some other way until then?
*** higher order states may be "inflated" - meaning that they may appear to have more information than the first order representation that created them.

    an example from the paper: having the experience of a very rich scene with many details, but not being able to report on (access) any of the details.

*** it's not actually well established what the connection between the sensory areas and the conscious experience that refer to the those modalities - it's not necessarily the case that experience is built from the first order material itself, and that the rest of the activity is "just  a reflection of post-percetual processing that allows access and report"
*** since first order representations are "re-represented" - according to some HOTs - HOT predicts that there would be cases where there will be a variable conscious experience "on top" of a constant underlying first order content
*** not postulating that consciousness has  a function, or that it has some evolutionary advantage in performing tasks
*** HOT says that any local processing activity can become conscious, if it gets/creates a higher order representation - c.f. GNW in which it must become globally available. They give the example of blindsight - where a patient can guess an object shown to her without consciously seeing it. In GNW that's more problematic because at least some of the network seems to be down
*** not about the PFC per se, but about the cognitive requirements for consciousness
*** PFC is a major contributor to consciousness
*** Lau and rosenthal: dorsolateral, polar and vetral-lateral areas of the PFC are specifically important for HOT
*** they said that the representations are not themselves conscious but they facilitate the experience of first order states via another, even higher level layer.
*** maybe higher order representations are  used to index first order ones
*** alternatively, in HOROR (higher order representation of a representation), the higher order state is itself a conscious state.
*** HOTT can be adjusted to include emotions, concepts and memories as first order representations - in which case, areas of the PFC (although higher-order cognitively and anatomically) are used as first order representations of the emotions etc. in question
*** also possible that the higher order network is not fixed, but is created from some number of areas, of which relevant ones are recruited based on the situation
