:PROPERTIES:
:ID:       20210627T195320.422301
:ROAM_REFS: cite:mudrikStudyingVolitionActions2020
:END:
#+TITLE: Notes: Studying volition with actions that matter: Combining the fields of neuroeconomics and the neuroscience of volition.
#+ROAM_KEY:
- tags ::
- keywords ::

:PROPERTIES:
:Custom_ID: mudrikStudyingVolitionActions2020
:AUTHOR: Mudrik, L., Levy, D. J., Gavenas, J., & Maoz, U.

* Notes:
*** where, what, and when to move/do - dissociated?
*** different areas suggested to be in charge of each
*** liad criticized libet's experiment saying that "the premise is dualistic" - what does this mean?
*** the W time measure is problematic?

        that is, the moment  when they
        felt the conscious urge to move or the conscious
        experience of deciding

*** neuroeconomics - valuation and choice
*** which brain areas estimate worth/value of a given choice
*** how do we learn to valuate choices in general, from our experience etc.
*** different models on how a decision is made in the brain: race-to-threshold, drift diffusion model
*** generally - the representation of a choice gains more power as more information points us towards it, until it passes some threshold
*** two main paradigms in neuroeconomics - one of them is a 2-alternative forced-choice, which is well known and used in neuroscience of volition as well.
*** the choices are used to create a rank of preferences of that subject, and that rank is regressed against the neural activity to look for neural correlates
*** the brain response can be used to predict the value given, even when no action is done around the decision - so the value exists in the brain regardless of the action
*** in the case of picking, it's possible that the decision is created by the accumulation of random noise in the system. maybe that's the brain's mechanism for making unimportant symmetry-breaking choices.
*** it was shown computationally that this is possible (to get a readiness potential through random noise)
*** advantages of using neuroeconomics methods:

    - expands the range of phenomena we can study in volition
    - more "ecological" i.e. natural - why is this better?
    - more relevant to the free will debate

