:PROPERTIES:
:ID:       20210627T195323.461772
:ROAM_REFS: cite:zuckerUnderstandingAssociativeVs2019
:END:
#+TITLE: zuckerUnderstandingAssociativeVs2019: Understanding associative vs. abstract pictorial relations: An ERP study
#+ROAM_KEY:- tags ::
- keywords ::

* Understanding associative vs. abstract pictorial relations: An ERP study
:PROPERTIES:
:Custom_ID: zuckerUnderstandingAssociativeVs2019
:URL:      
:AUTHOR:   Zucker, L., & Mudrik, L.
:NOTER_DOCUMENT: /mnt/c/Users/Jonathan/Google Drive/.notes/.bibliography/bibtex_pdf/Zucker&Mudrik_2019_Neuropsychologia.pdf
:NOTER_PAGE: 
:END:

*** a distinction between relations on one hand, and attributes and associations on the other
:PROPERTIES:
:NOTER_PAGE: (1 . 0.5594350725774814)
:END:

*** associations are more due to frequency of co-usage of words and less about their meaning (I disagree)
:PROPERTIES:
:NOTER_PAGE: (1 . 0.6586896822283249)
:END:

*** three ways to categorize relations - based on:

1. structure (=complexity) - 1st vs 2nd order relations.
   a 2nd order relation is a relations who's objects are other relations, e.g.
   cause[collide(x,y), strike(x,y)]
2. content - the type of meaning of the relation - spcaial relation, numerical,
   tempotral etc.
3. strength - strong medium or weak relation as subject subjectively determine
:PROPERTIES:
:NOTER_PAGE: (1 . 0.7489211455472735)
:END:

*** visual associations almost always imply semantic relation as well, since they are based on co-occurance in the real world
:PROPERTIES:
:NOTER_PAGE: (2 . 0.3792335115864528)
:END:

*** a new tyoe of visual relation to test: pictures that have an abstract semantic relation, but do not co-occure in life, such as babies and flower buds
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5432263814616756)
:END:

*** what's the difference between association and abstract relation? two options:
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5842245989304813)
:END:

- visual association relies on statistical learning while abstract relation
  requires proper semantic processing
- just a matter of greater semantic distance, but the mechanism is the same.

*** visual metaphors
:PROPERTIES:
:NOTER_PAGE: (2 . 0.8917112299465241)
:END:

*** metaphorical stimuli requires greater computational resources and/or additional mechanisms
:PROPERTIES:
:NOTER_PAGE: (2 . 0.16399286987522282)
:END:

*** astract processing (rules, relations, terms) seem to be done in more anterior regions along the caudal-rostral  axis. abstract concepts/meanings as well - "seed" as the begining of an idea, "seed" as the symbolizing the cycle of life etc.
:PROPERTIES:
:NOTER_PAGE: (2 . 0.338235294117647)
:END:

*** she's thinking up two possible underlying mechanisms, in a way that makes it possible later to tell the difference with an experiment. here one expanation would manifest as a deifference in the obsereved neuronal functioning, while the other would only manifest as a longer time from stimulus to understanding
:PROPERTIES:
:NOTER_PAGE: (2 . 0.496078431372549)
:END:

*** N400 response seems to be related to processing relations of various kinds:

it's stronger the weaker the connection and strongest in situations where a relation cannot be found: weak metaphors, unrelated images etc.
it may also be related to integration of new patterns or information (e.g. new relations betwen currently unrelated objects), or maybe to the effect of the violation of expectations, or to retrieval of information from LTM, or some combination of the above...
:PROPERTIES:
:NOTER_PAGE: (2 . 0.676470588235294)
:END:

*** again, she suggests an interpratation on un underlying mechanism (here - that abstract and associative are two ends of a spectrum), and deduces a way it would manifest experimentally
:PROPERTIES:
:NOTER_PAGE: (3 . 0.20294117647058824)
:END:

*** "late negativity" in the context of unexpected stimuli refers to brain activity immediately following th e N400 response
:PROPERTIES:
:NOTER_PAGE: (3 . 0.4074074074074074)
:END:

*** late negativity is taken to represent the reinterpretation effort related to the process of integrating the new information, and is also related to working memory load (=activity).
:PROPERTIES:
:NOTER_PAGE: (3 . 0.41975308641975306)
:END:

*** LPC (=late positivity component) in this context refers to a group of positive waves following the N400 response. It's taken to related to the integration effort itself in the face of new data that is out of line with our existing models about the world
:PROPERTIES:
:NOTER_PAGE: (3 . 0.6666666666666666)
:END:

*** So in this experiment they presented a series of images in three degrees of relatedness (unrelated, abstract relation, co-occurance relation), and expected to see a gradual change in the amplitude of the response. They also hoped to see a new effect, not gradual but different, for the case of abstract vs co-occurance, that would imply a deifferent mechanism was needed for semantic understanding/
:PROPERTIES:
:NOTER_PAGE: (3 . 0.18518518518518517)
:END:

