:PROPERTIES:
:ID:       20210627T195201.034669
:END:
#+TITLE: email to shimon marom

שלום פרופסור מרום,
אני מקווה שאני מוצא אותך בטוב בתקופה הזו.
סיימתי את התואר הראשון שלי בביואינפורמטיקה בטכניון לפני שלוש שנים בערך, והחלטתי
לאחרונה שאני רוצה לחזור לאקדמיה ולהתחיל מסלול שיוביל אותי לעסוק במחקר במדעי המוח. 

אני כותב לך כי קראתי חלק מהספר שכתבת על הדיאלוג האפשרי בין פסיכואנליזה
ונוירופיזיולוגיה והוא הדהד אצלי מאוד. שימח אותי למצוא אדם וחוקר שאני מזדהה עם
העמדה שלו לגבי האופן שבו נכון לשאול את השאלות שמעניינות אותי לגבי התודעה והנפש ולגבי האופן
שהן מתבטאות בו במוח, וחשבתי לבקש ממך עזרה כדי להכווין את עצמי לסוג הזה של
מחקר.

השאלות שמעניינות אותי קשורות לקיום ולמאפיינים של התודעה עצמה, לחוויה
הסובייקטיבית שלנו את העולם (והקיום שלנו כסובייקטים מלכתחילה), ולאופן שבו
המבנים הנפשיים שלנו והחוויה הפנימית שלנו אותם מתגבשים מתוך המציאות הניורוביולוגית. 
אני יודע שאלו שאלות גדולות מאוד, ואני יודע שהמחקר בפועל עוסק לרוב בשאלות קטנות
וממוקדות יותר, אבל הייתי שמח למצוא מעבדה ששמה לעצמה את השאלות האלה כמטרת-על, גם אם
היא רחוקה כרגע. 

קראתי את המאמר האחרון של מארק סולמס מ 2019, והלהיב אותי לגלות חוקר ששואל את השאלות
האלה, ומנסה בפועל לענות עליהן ישירות בכלים מדעיים.
המחקרים שלו, כמו גם המחקרים של קרהרט-האריס על חומרים פסיכדלים וה DMN, חשפו אותי לקיום
של מחקר כזה, אבל כמעט ולא מצאתי חוקרים בארץ ששואלים את הסוג הזה של שאלות. 
הייתה לי שיחה טובה מאוד עם אביבה ברקוביץ' מאונ' חיפה, אבל בגלל כל מיני נסיבות היא משתייכת למחלקה לחינוך שם, ואין להם אפשרות להציע מלגות שמתאימות למחקר במשרה מלאה.

אשמח לשמוע מה דעתך על התחום בארץ באופן כללי, ובאיזו דרך כדאי לעשות בו צעדים ראשונים,
וגם באופן ספציפי, אם אתה מכיר חוקרים בטכניון או במוסדות אחרים שיכול להיות רלוונטי
לדבר איתם.

