:PROPERTIES:
:ID:       20210627T195257.678145
:END:
#+title: 2020-12-29

* Ruth Kinchi lecture [[file:slip-box/2020-11-02-notes_on_colloquium_lectures.org][Notes on colloquium lectures]]
*** we need to organize the mosaic of light and color into coherent units - which we'll recognize as objects.
***** grouping - based on proximity, similarity, same movement direction & speed etc.
***** figure - ground separation
*** does perceptual organization require consciousness? --> actually what kinds of perceptual organization can happen, since there are many
*** clustering (what goes with what) vs shape formation (what's the appearance of the whole group of related objects)
*** checking the processing of the unconscious prime via the difference in response time to the visible image when they are congruent and incongruent to the prime.
*** in UC processing we get only local facilitation (large shape made up of smaller elements), and in C processing we get only the global facilitation.
*** conscious awareness is a limited resource, so we need UC processing to "chew" on the input, to preprocess, to decide "for us" what consciousness will be presented with and will have to decide about
