:PROPERTIES:
:ID:       20210627T195218.094738
:END:
#+TITLE: כתובה

* יונתן
** מה אני רוצה להבטיח לאילת?

אני אמשיך לטפח ולהשקות את האהבה שלי אליך
כשנריב אני אזכיר לעצמי את הכוונה העמוקה שלנו לקיים חיים שמחים ביחד, וושבבסיס אנחנו רק רוצים שיהיה לנו טוב
אני אסנדווץ' אותך כשתצטרכי
אני אעזור לך להתקדם ולהתפתח במקצוע שלך
כשיהיו לנו ילדים, אני אקח חלק שווה באחריות עליהם ובטיפול בהם
אני אדאג לך כשתהיי חולה
אני אדאג שלא תדעי מחסור, שתהיה לך קורת גג, אוכל טעים על השולחן ובגדים טובים ללבוש
אני אפתח את הלב שלי אליך
אני אתן לך מקום להתפתח ולהשתנות, אני לא אכבול אותך למה ואיך שאת כרגע
אני אתן לך ספייס
אני לא אקח אותך כמובנת מאלייך
אני אזכור שאת אדם נפרד ממני ושיש בך מסתורין ועומקים שאני עוד לא מכיר
אני אהיה כמה שיותר עצמי איתך, כמה שיותר כן ואמיתי
אני אסמוך עליך

** מה אני מאחל לנו לחיים המשותפים שלנו?

שנשמח הרבה, שנצחק הרבה
שלא תחסר לנו פרנסה, אבל שנדע להסתפק במועט
שיהיו לנו חיי משפחה עשירים, שיהיו מנהגים ומסורות ושפה שלנו
שנהיה בקשר טוב עם האחים והאחיות שלנו ועם ההורים וההורים וההורים וההורים שלנו
שנלמד להבין את העולם ביחד, שנחלוק את החוויות שלנו ונחשוב ונדבר עליהן
שיהיה לנו מלא מין טוב, ושהוא רק ילך וישתפר

* משותף

תמות: בית, מעיין, צמחים,מסע\דרך

אזכיר לעצמי את הכוונה העמוקה שלנו לקיים חיים שמחים ביחד, וושבבסיס אנחנו רק רוצים שיהיה לנו טוב גם כשנריב
אני אסנדווץ' אותך כשתצטרכי

אנחנו מתחייבים לאפשר אחד לשנייה הזדמנויות שוות להתפתח מקצועית ואישית בעולם, גם למול ובניגוד למבנים חברתיים וכו'
כשיהיו לנו ילדים, אני אקח חלק שווה באחריות עליהם ובטיפול בהם

אני אדאג לך כשתהיי חולה

אני אפתח את הלב שלי אליך

שלא תחסר לנו פרנסה, אבל שנדע להסתפק במועט
שנהיה בקשר טוב עם האחים והאחיות שלנו ועם ההורים וההורים וההורים וההורים שלנו
שנלמד להבין את העולם ביחד, שנחלוק את החוויות שלנו ונחשוב ונדבר עליהן
שיהיה לנו מלא מין טוב, ושהוא רק ילך וישתפר

מעיין של חיוניות שפע אמת קבלה וחמלה
שנדע לקחת את הזמן לעצור לנשום לחבק וגם לפעמים לרוץ קדימה ולפעול
שיהי לנו אומץ

** איזה מן בית יהיה לנו שנשמח הרבה, שנצחק הרבה

שבבית שלנו יהו צחוק שמה וקלילות
שנהיה בית פתוח מקבל מעים מארח ואוהב
שיהיו לנו חיי משפחה עשירים, שיהיו מנהגים ומסורות ושפה שלנו

** כנות כבסיס לקשר

אני אהיה כמה שיותר עצמי איתך, כמה שיותר כן ואמיתי
אני אעמיק את האמון שאני נותן בך
שהקשר יהיה מבוסס על פתיחות אמון ביטחון וגמישות

** חלק מקהילה

שנדע לערב חברים אהובים בחיים שלנו ובגידול של הילדים שלנו
שנבנה בית ומשפחה שיהיו חלק מקהילה, ומעגלים מתרחבים מסביב
שנלווה אחד את השני באירועים\תהליכים חשובים בחיים, שנגדל ילדים ביחד, החלטות כמו לגור קרוב, לחלוק תרבות משותפת, שפה משותפת, מנהגים.

להמשיך לטפח קשרים עם האנשים בקהילה
להסכים להתמך ע"י הקהילה

־ למצוא ניסוח יותר עמום אולי?

** להשקיע באהבה ובקשר

אני אמשיך לטפח ולהשקות את האהבה שלי אליך
לבחור כל פעם מחדש

** להיות בית אחד לשניה

בית תומך מחזק אוהב ובטוח
שנרגיש שהקשר שלנו נוא בית לחזור אליו ולהירגע בו
שהבית יהיה מקום שמזין אותנו באנרגיה ושנוכל לנוח בו כשנצטרך להיטען

** השתנות

אני אתן לך מקום להתפתח ולהשתנות, אני לא אכבול אותך למה ואיך שאת כרגע
 מוכנים להתפתח ללמוד להשתנות

** לא לקחת כמובן מאליו

 שנדע להעריך, לא לקחת כמובן מאליו את הצד השני ואת הקשר

אני לא אקח אותך כמובנת מאלייך
אני אזכור שאת אדם נפרד ממני ושיש בך מסתורין ועומקים שאני עוד לא מכיר

** להיות אנשים נפרדים

בית לחזור אליו אבל גם לצאת ממנו
שיהיה להו חדר משלנו בבית המשותף
אני אתן לך ספייס (כשתצרכי)
לכבד את הצורך המשתנה במרחב והקצב השונה של האדם השני
לכבד את המסע של כל אחד ואת המסע המשותף

* גם הצהרת כוונות
* טקסט, לשזור את הדברים. אולי הגיון בבניה ־ לקבץ לפי מטפורות, מהפנים אל החוץ, וכו'
* לשלוח טיוטא לדותן
* לקבוע שיחה על 7 ברכות
