:PROPERTIES:
:ID:       20210627T195239.387156
:ROAM_ALIASES: Attention_Schema_Theory
:END:
#+TITLE: AST
#+ROAM_ALIAS:
A theory proposed by Michael Graziano.

It's main claim is that waking consciousness/awareness is a model of our capacity for attention - the physical reality of which is what they refer to as [[file:2020-09-30-i_consciousness.org][i-consciousness]].
According to AST, our subjective consciousness (what they call [[file:2020-09-30-m_consciousness.org][m-consciousness]]) is a working model, quick-and-dirty and incomplete of that physical capability of the brain to attend to something and perform computations in relation to it.

It's reminiscent of [[file:20200507190753-mark_solems.org][ยง:Mark Solems]] ideas saying that [[file:2020-05-27-consciousness_is_affect.org][ยง:Consciousness is affect]]: it postulates that consciousness has developed in order to help us navigate/make sense of a highly complex environment in a way that's dynamic and accessible to us.

For some reason they seem to need to say that subjective experience doesn't actually exist - that we only claim/think that we have these experiences while in fact they're not real (in what sense?) (cf.[[file:2020-09-30-iit.org][IIT]])
So they're answer to [[file:2020-09-30-the_hard_problem_of_consciousness.org][the hard problem of consciousness]] is that the basic premise of the question (that there *is* something it is like to be someone) is not valid.

* Sources

- cite:grazianoStandardModelConsciousness2019
- cite:grazianoConsciousnessAttentionSchema2020
- [[file:grazianostandardmodelconsciousness2019.org][grazianoStandardModelConsciousness2019: Toward a standard model of consciousness: Reconciling the attention schema, global workspace, higher-order thought, and illusionist theories]]

