:PROPERTIES:
:ID:       20210627T195255.005811
:END:
#+TITLE: Notes on pyschotherapy lectures
:PROPERTIES:
:ID:       8277f1b5-b9d4-4df2-ab2e-d00d6b146d29
:END:
- tags :: [[file:../../../../../../../home/jonathan/google_drive/.notes/slip-box/2020-11-02-psychoanalysis.org][Psychoanalysis]]

* Nov 2 - Rachel Balas
*** Klein's view n love
***** radical?
***** klein as cold, unloving distant
***** she says love the whole story with klein in fact
***** love in 3 respects:
******* the life and working of man's soul
******* love in the act of healing
******* love as a consequence of healing
***** the "londonian" kleinian method
***** what's the subject matter of psychoanalysis?
***** the center is that a person doesn't want to know/acknowledge the reality of his inner state/life
******* something specific about ourselves that we refuse to acknowledge
******* any number of ways what we don't know/want to know distorts our view/handling of reality
***** we both want and don't want to go to therapy.
***** there's a part of us that wants to know, in spite of itself, in spite of not wanting to know.
***** we need psychoanalysis depending on how we digest these things about ourself that we don't acknowledge
***** when we don't want to see, we distort reality around it, and we create a breakage in our soul
***** the reason we don't want to know/see is because of love.
******* we care for people around us and we refuse to know that within us that may hurt another.
******* it's unbearable for us to be aggressive, to hurt.
***** the basis of the two-forces model. eros and the death drive. without there being two, there would not be a conflict
***** the basic premise is the Oedipal conflict/complex. why is it so important? what's the conflict actually?
***** the problem is that the child also loves his father, even as he wants to kill him to gain his mother's love completely
***** two solutions to the conflict of hurting a loved object:
******* deny the aggressive instinct
******* deny the love for the object
***** there's a hurting of the other in the very act of distorting reality
***** the depressive position at its base is feeling bad after acknowledging that I hurt someone else
***** the interesting thing is always what the person *doesn't* know rather than what he does
***** "knowing" in the sense of describing something about myself, is not the same as knowing in fact, in a deep sense.
******* either the person doesn't really know deeply what he says he knows or that there other things that he is unaware of.
***** at the basis of love is wanting reach out to an Other. that we are willing to sacrifice something for him
***** in a sense that Other is also inside me. (how?)
***** when we do something kind to another we are identifying internally with the good, parental object, and also identify as a child with the person we are being kind to.
******* in the same process we are also re-living love towards our parent
***** when a patient loves the therapist, idealizing him - it's because he can't stand his (the therapist's) flaws, he must ignore them.
***** "hate greed and aggression" /Joan Reviere (a colleague of klein)
******* why is it so hard for us to bear that we are dependent?
******* the baby wants the breast also purely because he loves it (apart from enjoyment and sustenance)
******* the horrible experience we have as babies - of hunger, of anger, of unfulfilled desires, when the entire world is devoid of all that is valuable and good - spawns the first feelings of love (in the form of need)
******* the baby's world is out of control - and it's because he loves and...
******* the basic state of the baby is love
******* the don juan -
********* when the relationship becomes better/closer he feels the beginning of frustration, of fear to hurt the loved one for his/her flaws. he begins to feel his aggression towards the object
********* there's hope of finding a good object, another good object instead of the one that was lost
******* dependence is not love
******* gratitude vs envy:
********* in gratitude there's acknowledgment in the good that's given to me, that I'm not alone in the world
******* we become so cynical towards our loved that we don't even acknowledge that we have love inside of us.
******* when we understand (which comes from tolerance to them!) these processes we become less afraid of them, then we are able to work with them.
******* we must acknowledge the inner struggle between the loving and destroying impulses. this inner conflict is imperative to really get to know, not through the mind, but experientially to really find a place in our soul to contain both of them and the struggle between them.
***** aversion to bolby's attachment theory
***** guilt becomes an important part of love, changing it.
***** the child cares for the parent - it's more than needing sustenance from him
***** there's an impulse to give, to care, to sacrifice for the well being the one that we destroyed and hurt in our fantasy. (the guilt is about the fantasy)
***** it's important to let the child feel guilt to some extent, too much indulging actually creates stronger, deeper feelings of guilt, the child needs to learn the possibility of sacrificing something/correcting for the damage in his fantasy in some way, so as to alleviate his guilt.
***** children who are spoiled too much grow up to be selfish adults, haunted by guilt, unable to give of themselves.
* Nov 20 - Rachel Balas cont.
:PROPERTIES:
:ID:       14b9507d-2726-4c45-9f4f-b63237c0e202
:END:

*** what makes a person want to know the unknowable?
*** to see the world, the other, himself as they are. to know the truth
*** the love of an object creates pathology (we don;t want to know about our impulse to hurt the impulse)
*** love also provides the drive to solve the conflict, to seek treatment
*** it's more ethical to start giving פירושים from the beginning - this way the subconscious is taking part in the process of deciding to start therapy
*** the struggles in our soul are hurting us, stopping us from being fully alive, to participate in life etc. this is why we want therapy in fact
*** the guilt we have towards the object shapes our love for it - TODO how?
*** when I so something good/kind to another person, I simultaneously identify with the internalized mother/caregiver and with the child that I was that experienced her giving
*** how to build trust with a patient?
***** the patient must see and realize that we are able and willing to be with him through the difficulties that rise out of his internal world. it's in our פירושים that we show the patient that we love him, and that we are there with him
*** aggression is good as an internal force. it's good to hate what is bad/evil
*** our pleasures as adults are all transformations of the pleasures we had from our mothers, and they depend on our ability to detach from her and allow ourselves  to find pleasures elsewhere
*** our ability to love ourselves (and then others in turn) comes from learning to be kind and loving to others in infancy, and if we are able to forgive our parents a least in part, and absolve their memory from feelings of wrong-doing towards us, we will be more equipped to love fully in our lives.
*** it's not always aggression that becomes hidden and unacknowlegable - sometimes it's love, that has been driven deep and can't be touched and used
*** the basic switch in kleinian psychology is that we need to give room to the aggressive side of the patient - that's what will bring relief to the anxiety that comes from the aggression being hidden. (she can't love me in truth because of what's in me, she's not smart enough to see it etc.)
*** מרחב ביניים
*** talking in 3rd person to a child males him think that there's something wrong with those things, that they can't be directly referred to.
*** less control gives more freedom to internal objects as well
*** help from the outside world can increase faith, and lessen the manic control, giving more freedom to internal objects (grieving woman example)
*** when we grieve, our internal objects (mother and father) can grieve with us.
*** transference is always there in the room, it's the color of what's being said rather than the contents

***

* Nov 30 - Rachel Balas cont. 2
*** theraputic process in the room
***** the main issue is the conflict between our aggression and the loved object we sometime direct that aggression towards.
***** we try to avoid that conflict by manipulating, distorting really, the world/reality
***** it's not enough to inform the patient about himself - it must be experiential.
***** that's why transference is the only way psychotherapy assists the person who is suffering,
***** how does that work?
******* it's a unique situation where the dynamics actually exist in the room, we can meet it.
******* the therapist's neutrality is paramount for the possibility of this to happen
******* the patient tries to bring to life his own dynamics in the room.
******* the therapist does not oblige this. (example - patient wants to be investigated)
******* instead we want to ask - why did the patient behave in this way, to make feel like that that?
******* by obliging, we rob the patient from meeting that part which "acted out" by trying to manipulate the therapist.
***** the therapist is "the expert" - she doesn't want a dialogue, a conversation.
***** it's the therapists role to find out what the patient lives but does not know. to listen to what the patient does in the room
***** it's not from a position of disrespect to the patient, that we don't want a conversation with him.
***** the interpretation sinks in, and the truth of it makes the patient free somehow, it lets him accept that part of himself that the interpretation touches upon.
***** so instead of asking questions (which is what the patient wants, inviting the therapist to play some role), we offer interpretations.
*** Narcissism
***** the antithesis to love - is narcissism.
***** it destroys the love for the separate object. the object is separate by its very nature.
***** three major concepts according to Klein:

      1. the person doesn't really care so much about the other. deep inside he feels he mortally hurt or killed a past object and now he fears that meeting a real object he will have to face the irreversible damage he has done or will eventually do.
         he is fake-nice, doesn't really attach, nothing happens in therapy. he feels that the object (therapist) is already dead. the relation is superficial. he can't receive healing/help - because he doesn't deserve it. the ones who need it truly are the dead objects inside of him.
      2. idealization/devaluation - the object is either amazing and perfect or worthless. these are both ways to deal with envy.
         this is the death instinct, the inability to accept the good, the urge to destroy/attack the good.
      3. fear of dependence. eliminate the dependence by eliminating the separation. if I and the object are the same, then I'm not dependent on it.
         this may come from my not believing the goodness inside of me, seeing mostly from fear that if the object knew me for who I am, he will not want to give to me. the more I know about my aggression, my jealousy, I am more afraid. this is why dependence is frightening.
         the solution: I and the object/other are one.

*** there's a strong connection between narcissism and death in all three concepts
*** projective identification
***** something that eliminates the distinction between me and other
***** the basic, more important, aspect of it is that the patient puts a part of himself in an object, and now identifies with this object because of this.
***** it's less about the way the object (sometimes therapist) feels about this (this appears in Byon, Ogden...).
***** both the projection of bad, hated parts (creating hated objects), and of good parts (creating idealized objects) into outside objects, weakens and impoverishes the self.
***** the projection of good parts can create the fear that we have lost the ability to love: we don't really love the idealized object, we love our good parts projected into that object, we love ourselves and not the object.
:PROPERTIES:
:ID:       8ec0cc76-5346-45dc-8861-d4f2618f2930
:END:

***** giving this interpretation frees the patient because he actually knows this in some deep level
*** the "correctness" of interpretations is "ongoing". there's always an attentiveness to the love and destruction that happens, a continuous interpretation of the what goes on and how the interpretation affects the mood of the patient.
*** schizoid defenses:
***** sometimes instead of directing aggression outwards, we direct it towards the part of ourselves that is aggressive in a way that is unacceptable to us.
