:PROPERTIES:
:ID:       20210627T195201.784593
:END:
#+TITLE: Notes: Feldenkrais Course segments
- tags :: [[id:20210627T195202.037575][Learning]][[file:2020-05-20-feldenkrais.org][, Feldenkrais]], [[file:2020-05-20-somatic_methods.org][somatic methods]] [[file:2020-07-25-פלדנקרייז.org][פלדנקרייז]]

* יולי 2021
*** The physiology of consciousness / Adelman
*** הקלטה של אהרון קציר ומשה
*** אינטואיציה זה משהו שאפשר לפתח רק בתחום שאנחנו ממש מקצועיים בו
*** לתת מקום למישהו אחר, להסכים לו להיות נוכח במרחב של התודעה שלי
*** פלדנקרייז ופסיכואנליזה:
***** שכיבה על הגב מאפשרת לשחרר יותר ולהתחבר למקומות עמוקים יותר
***** לא מסתכלים על האנליטיקאי\מורה ־ עוזר להתחבר לעכשוויות, מוריד את הצורך להתחבר או לקחת בחשבון את האחר. מפנה אותנו להתרכז בעצמנו
*** אפשר להשעין את הירך לתוך המפרק שלה, לתוך האגן, לתת לו לקחת את המשקל שלה, כשרוצים להרים את הרגל
*** בעמידת ראש ־ לדרוך עם העורף כמו עם עוד רגל
*** לא רוצים לעשות פלדנ כל יום כל היום ־ זה דבר שעושים כשהתנאים מתאימים, כשלא לחוצים, כשלא מנסים לפתור משהו קיומי
*** להפסיק לעשות עוד לפני שמתחילים להתאמץ
*** תמיד כדאי לנסות "ליפול" במקום, איפה שאנחנו, לתוך נקודות המשען הנוכחיות שלנו
*** מה נשען עכשיו? ומה עומד לבוא להשען ברגע הבא?
*** מה זה להעביר משקל מרגל לרגל (או בכלל לאיזו נקודה)? יותר טוב לחשוב על זה כלהעביר את כל עצמנו.
*** מה עושה הראש בשמן שמעבירים משקל מרגל לרגל (עולה ויורד), ואיך השכמות מחליקות על הגב?
*** לתת ערך לאינטואיציה שלנו ־ לתחושה שנדמה לנו שראינו משהו, או שמשהו קרה
*** כשצריך לפתור בעיה שהיא (או מרגישה כאילו היא) קיומית ממש ־ בדכ הכי טוב לעשות את מה שכבר יודעים. זה לא מצב שמתאפשר בו ללמוד משהו חדש, או להטמיע משהו חדש שלמדנו
*** הבעיה היא שהרבה פעמים מה שכבר יודעים לא פותר את הבעיה מספיק טוב ־ אז מה עושים?

    הכי טוב אם אפשר למצוא או לייצר תנאי ביניים ־ סיטואציה שהיא מספיק דומה, אבל לא מרגישה קיומית, שבה אפשר להתנסות.

*** להגדיר תנאי ביניים יכול להיות גם לזהות שהסיטואציה היא למעשה לא קיומית כמו שחשבתי
*** העיקר בשיטה הזאת הוא להרגיש בנוח עם להיות במצב של חוסר ידיעה, ולהסכים לתת לפתרונות לבוא ממקומות לא צפוים
*** מהלך של FI שעשינו:

    1. על הגב
    2. לבדוק שכמות
    3. לגלגל ראש
    4. לעבור לבטן ־ לשים גליל אם צריך
    5. לעבור על התעלה של עמוד השדרה
    6. לגלגל אגן
    7. להרים רגל ־ לתמוך מעל העקב
    8. לגלגל את הירך\ברך דרך השוק כשאוחזים בכף הרגל
    9. לחשוב פעם על ההישענות בברך ופעם על הגלגול של הירך עצמה
    10. מה שטבעי יותר הוא לתת לעקב "לצאת" או "לבלוט" יותר מהאצבעות לכיוון שאליו הרגל זזה ־ יותר ימינה כשהרגל הולכת ימינה
    11. לנסות גם הפוך ־ אצבעות קודם
    12. להרים את הרגל ל 90 מעלות
    13. לבדוק את הסיבוב פנימה והחוצה של כף הרגל ־ כמו למחיאת כף.
    14. לראות שהוא מתואם עם הסיבוב של השוקית (fibula) סביב השוקה (tibia)
    15. להחזיר רגליים
    16. לקפל ברך לכיוון החזה
    17. להרים את המרפק של היד המתאימה כשהמשקל עובר אל כף היד ואל הכתף ־ אולי להזיז את כף היד יותר למטה כדי שלשכמה יהיה יותר קל לתת למרפק להתרומם
    18. לתמוך במפרק הכתף מלמטה, כמעט בית השחי, ולהרים את הכתף עם השכמה, להשתהות שם כל פעם
    19. לבדוק את התנועה של השכמה בהרמה, לאיזה כיוון
    20. לבדוק את ההורדה של הכתף ־ לאן קל לה לרדת?
    21. לתמוך בכתף עם יד אחת, ואת השניה להניח על השכמה וללוות את התנועה
    22. לבקש להפנות את הראש מצד לצד, לראות איך הגב משתתף בין השכמות, לנחש איך החזה נשען
    23. לשים את הידיים על הצלע הראשונה קרוב לעצם החזה ־ קצת מתחת לעצם הבריח

* נקודות שעובדו:
*** רוצים להיות פתוחים להשלכות של תנועה על כל הגוף
*** מתחילים שיעור בהבאת תשומת לב לאיזור בגוף - נניח עקבים - כדי להביא את כל המיינד למצב של קשב דק יותר
*** מאי 2021

ונוכח, שבו אנחנו מעוניינים.
  זה מעניין לראות איך תשומת לב בעלת איכות כמו זו שמבקשים יכולה לשנות את כל המצב של הקשב שלנו לגוף (אולי לא רק?) באופן כללי.

*** יש צורך לתת לעצמך להנגע על ידי הדברים\אנשים אחרים ולהיות נוכח למגע שלהם ולאופן שהם בוחרים לפעול עליך
*** בפלדנ יש משהו שמעודד מצב שבו נותנים לדברים לדבר ולשחק אחד עם השני ולתת לקשרים להבנות. אולי יש יותר תשומת לב לחיבורים ולקיום שלהם מאשר להגדרות המדויקות של מה הם הדברים ובאיזה אופן בדיוק הם מתחברים
*** בהתפתחות, הדברים מתפתחים תמיד ביחד, מתהווים זה מזה, כאילו בתנועה אחת, בבת אחת ־ לכן צריך גם להתייחס אליהם ביחד, לפעול עליהם כיחידה אחת, או לפעול על היחסים בינהם
*** הדבר הזה עובד בכלל ־ כלומר, אפשר לחבר את כל החתיכות הקטנות שאנחנו שמים אליהן\מגלים לב לכדי משהו בעל משמעות ־ בגלל שאנחנו מחוברים באופן בסיסי וראשוני, מרגע שאנחנו נולדים
*** אנחנו מקווים, במקרה הטוב, שהבנאדם ירגיש יותר טוב מתוך העשייה שלו בשיעור ־ אבל זה לא "על" המורה. המורה לא שם כדי להציל אותו.
*** לא כדאי להתחיל שיחה עם תלמיד חדש בבירור של מה לא בסדר איתו ודורש התייחסות מיוחדת ־ גם כי זה מביא אותו להתרכז במה שלא עובד, וזה בדיוק הפוך ממה שאנחנו רוצים, וגם כי זה יוצר אולי ציפייה שאנחנו הולכים לתקן אותו.
*** (אם יש תלמיד עם תנועה שקשה\כואב לו לעשות) כדאי למצוא שיעור שיש בו הזדמנות לעשות תנועה דומה, קרובה, משהו מסביב ־ אבל לא אותה בדיוק
*** לא לעשות או לגרום לתלמידים לעשות יותר מ 20־25 פעמים את אותה תנועה ־ זה משעמם ומעייף שכלית, וגורם לעשייה עם פחות ופחות תשומת לב ועניין. במקום ־ לעודד אותם לעשות וריאציות, למצוא מיקומים אחרים לידיים\רגליים, לעשות בדמיון
*** איך יודעים שמישהו התחיחל להתחבר ולהתעניין? הוא מתחיל לעשות לאט
*** "בפלדנקרייז אנחנו לומדים להיות המורים של עצמנו"
*** כדי להסביר משהו למישהו הכי טוב למצוא דוגמא קונקרטית שקשורה אליו ולתנועה שלו כרגע שיש בה מן העניין שרוצים להסביר
*** זה ממש עקרוני לבוא אל המקום שבו האיש נמצא ואל מה שהוא עושה באופן טבעי וקל כרגע
*** לא להיות ביקורתיים כלפי כל הדברים שהוא עושה "לא טוב" ־ הם כנראה משמשים אותו יפה בסהכ רוב הזמן
*** להשתמש במה שהוא עושה בקלות כדי ללמד אותו על מה זו קלות ואיך היא מרגישה
*** לא לתת שיעורים עם פיתולים לאנשים עם פריצות דיסק בגב התחתון!
