:PROPERTIES:
:ID:       20210627T195159.121923
:END:
#+TITLE: Research questions
#+STARTUP:

* *What areas/topics interest me?
*** embodied self
*** a sense of self (e.g. vs the world, vs others subjects, what constitutes my "self").
*** intuition
*** psychosomatic phenomena
*** the opposite of psychosomatic - how body-experiences influence the mind
*** mind-body relationship - sense of ownership of one's body, the way we "recruit" our body for action, the sense of a unification of the body ("working as one")
*** the ego and the DMN
*** psychedelics and the "loosening" of the ego
*** presence (in the here and now)
*** Empathy as a component of enjoying a performance or something created with skills that we have some experience in in experience of famiar skills
* *what would I want to test/unravel most if I had unlimited resources?
**** what's the relation between the sense of self/ego and the sense of being aware/consciousness itself? when are they decoupled? what different patterns of neural activity set them apart?
*** what's the relation between attention and consciousness? what's the difference between willfully attending to something and having it "pop" into our awareness and grab our attention? what changes when we become more adapt at controlling our attention
*** what neural patterns underpin the sense of (narrative) self? how do they change in different mental conditions (depression, addiction), and moods (anxiety, fear, calm)
*** test the hypothesis that the "raw stuff of consciousness" resides somewhere in the brainstem
*** what differentiates between different moods/shades of consciousness - wide/narrow, light/heavy, clear/muddled etc. Do they represent changes to consciousness itself or are they external to it?
*** what is attention? how does it operate on the stimuli that enter the brain?
*** how do psychedelics affect the ability to form new mental patterns or break old ones - for example, in relation to depression, and creativity
*** what's creativity like in the brain? what happens when we create something new (either physical, or an original idea), how is it different from experiencing something that someone else has created?
*** *Chosen one: What's the effect of psilocybin on neural connectivity in people with depression*
* *Ideas that are relevant for Liad:*
*** fabrication - how is our conscious experience being continually fabricated?
***** visually - like the black and white peripheral vision experiment
***** emotionally - like with metta practice
*** relationship between consciousness and attention - we can be conscious of what our attention falls on, without choosing what that will be
*** NC of attention to body
*** NC of wide vs narrow attention/interoceptive vs exteroceptive?
*** Does consciousness depend on the body/emerge from the body? I think yes
*** effect of past experiences on perception  (like the )
* *Questions for liad*
*** what is interesting for you in free will/volition
*** what is interesting for you in UC processing
*** how much will I be able to read and think about other aspects of consciousness in the day to day outside of the subject of the thesis?
*** cooperation with roy mukamel? embodiment/attention and motor learning
*** cooperation with roy salomon? embodiment and self consciousness, embodiment and volition - "gut feeling" -
*** computational models around predictive coding
*** would be happy to have a computational aspect of some kind (statistical/ML, graph theory etc.)
*** something about the binding problem, how consciousness integrates all the different information into a single experience
*** the transience of phenomenal experience - or rather how it's so intermittent, and yet seems continuous. Like a temporal binding problem

***

* meeting notes: [[id:20210627T195251.857766][Meeting summaries]]
*** it's more important who's the supervisor, and what are the methods, than what's the subject
*** also to learn how to plan an experiment
*** john dylan hanes again
*** anil seth and karl friston, predictive coding & consciousness
*** binding problem?
* R. Salomon coop
*** heart rate and free will (biases decisions) with Roy salomon
*** inserted thoughts and source monitoring

    With two robots, inducing a sense of alien present, and reducing the heightened memory effect of self-generated words (may be said alter source monitoring of thoughts)

*** sensory noise affects agency - maybe also perception

    Shows that agency and metacognition are dissociated in a way

*** sensorimotor conflicts alter metcognitive and action monitoring
*** sense of reality and predictive coding
*** Interplay between Narrative and Bodily Self in Access to Consciousness: No Difference between Self- and Non-self Attribute

            Interesting! Tests UC processing of attribute that participants feel are relevant to themselves. Showed that acoustic stimuli that were sounded close to the body biased the responses participants gave in the 2AFC task of categorizing subliminial words as self related or not

*** Consciousness is more than meets the eye: a call for a multisensory study of subjective experience†

        Interesting! Cross-modal influences if perceived as belonging to the same object (sound from the direction matching a subliminal visual stimulus enhances its perception)
        Metagonition - what about effect of the perceived danger in the stimulus on the bias of estimation?

*** Bilateral Rolandic Operculum processing underlying heartbeat awareness reflects changes in bodily self -consciousness
*** mechanisms of neural response to heartbeat
*** Unconscious integration of multisensory bodily inputs in the peripersonal space shapes bodily self-consciousness
*** The Insula Mediates Access to Awareness of Visual Stimuli Presented Synchronously to the Heartbeat
* Mukamel Lab
*** motor cortex involvement in recognition of self produced kinematics?
