:PROPERTIES:
:ID:       20210627T195306.053698
:END:
#+TITLE: Class notes: Intro to psychology science

* פסיכולוגיה ומדע
*** רלקסציה מול טיפול בחשיפה
*** צריך כלי אבחוני מהימן ־ ה DSM ושאלונים מתאימים
*** לפי מחקר קליני חשיפה הרבה יותר יעילה + עוזרת לאורך זמן
*** צריך לשחזר את המחקר\ניסוי כדי לסמוך עליו ־ רפליקציה
* בהביוריזם
*** פסיכולוגיה בימינו  = חקר 1. ההתנהגות ו־ 2. התהליכים המנטליים
*** בזמנו ־ רק חקר הההתנהגות
*** האמינו שאפשר לחקור רק את מה שאפשר למדוד ישירות ־ רק את מה שאפשר לראות = התנהגות
*** פבלוב ־ התניה
***** תהליך למידה acquisition של קישור בין שני גירוים אחרי תקופה שבה הם נחווים ביחד
***** יוצר תגובה אוטומטית שמתאימה לגירוי השני ־ נקרא הגירוי הלא מותנה (כי לא דרושה התניה כדי ליצור את התגובה האוטומטית באמצעותו)
***** הגירוי הראשון נקרא הגירוי המותנה
***** פעמון = מותנה, אוכל = לא מותנה, ריור ־ תגובה אוטומטית
***** הכחדה extinction ־ אחרי כמה פעמים שבהם מצלצלים בלי לתת אוכל הריור פוחת
***** החלמה ספונטנית ־ הכחדה לא עובדת ב 100%, ככהנ ההתניה תמיד תישאר באיזושהי רמה ואפשר יהיה להפעיל אותה
*** ווטסון ־ התניית פחד
***** טען שאפשר להנדס את ההתנהגות של בני אדם באמצעות התניה באופן מוחלט
***** אין השפעה ליכולות מולדות
***** אלברטו הקטן המסכן והעכבר הלבן
***** צליל חזק עבר צימוד לנוכחות של עכבר לבן
***** הכללה לחיות פרוותיות לבנות אחרות כמו ארנבים
***** הבחנה ־ גירויים שהם לא מספיק דומים, כאלה שאלברט יודע להבחין בינהם לבין העכבר לא מעוררים פחד
***** PTSD כהתניית פחד
******* גירוי לא מותנה ־ החוויה הטראומטית המקורית
******* גירוי מותנה ־ הזיכרון של החוויה
******* התגובה הלא מותנית = התגובה המותנית = תחושת הפחד
******* הרבה חלקים של זכרונות מהחוויה המקורית עוברים הכללה ומעוררים את הפחד גם במנותק מהזיכרון הכולל של החוויה
******* PE זה בעצם תהליך של הכחדה
******* גם פה יש תהליך של recovery
*** סקינר ־ התנייה אופרנטית
***** יצירת התנהגות ־ למידה ־ ללא התניה של גירוי מותנה
***** למידה דרך פרסים ועונשים
***** התנהגות משתנה בעקבות התוצאות שיש לה עבורי
***** דרכים להגביר התנהגות:
******* חיזוק חיובי ־ מתן גירוי נעים\פרס
******* חיזוק שלילי ־ הפסקת גירוי לא נעים, כמו צפצוף של חגורת בטיחות
***** דרכים להפחית התנהגות
******* עונש חיובי ־  עונש במובן המקובל, גירוי לא נעים אחרי התנהגות לר רצויה
******* עונש שלילי ־ הפסקת או מניעת גירוי חיובי כל עוד ההתנהגות ממשיכה
***** shaping ־ לחכות עד שההתנהגות קורית בצורה טבעית בחיה, ואז לחזק אותה
***** למידת המנעות
******* שילוב בין התניית פחד והתניה אופרנטית
******* מייצרים התניית פחד בסיטואציה שהתנהגות רצויה תגרום להפסקת הגירוי הלא נעים:
******* אור שאחריו שוק חשמלי ־ אבל רק בצד אחד של הכלוב: אפשר לעבור לצד השני.
******* חיזוק שלילי
******* אי אפשר לגרום להכחדה ־ כי החיה נמנעת מלהמצא בצד של הכלוב אחרי האור, אז היא לא יודעת שהוא כבר לא מצומד לשוק.
******* כמו התנהגות של המנעות אצל בני אדם
*** מחיקת זכרונות (שגב ברק)
***** רה־קונסולידציה reconsolidation
***** זכרונות הם למעשה דבר פלסטי
***** כשזכרון עולה למודע הensemble שמהווה את הזכרון הזה נהיה "פגיע" לשינוי\עריכה
***** מצב "אקטיבי"
***** כשאין אינפורמציה חדשה, הזכרון מתחזק
***** חוזר למצב יציב אחרי 5־6 שעות
***** רה־קונסולידציה תלויה ביצירת חלבונים חדשים באיזורים מסוים ־ הזרקת איסומיצין
***** ע"י עיכוב של יצירת חלבונים באיזורים האלה במסגרת חלון הזמנים אפשר לפגוע בקונסולידציה ולמחוק את ההתניה בלי שתהיה אחכ חזרה ספונטנית.
***** עוזר לחולדות להגמל מהתמכרות לאלכוהול
*** טולמן ־ לחקור את מה שאי אפשר לראות
***** למידה סמויה ־ latent learning
***** חולדות ששהו במבוך בלי אוכל יצרו מפה מנטלית של המבוך גם בלי ההתניה האופרנטית של מזון בנק' כלשהי במבוך, הן למדו את המבוך. הוכחה: אחרי כמה ימים של הכרות עם המבוך ללא אוכל התחילו לשים אוכל בנק' קבועה והחולדות למדו להגיע אליו באותה יעילות של חולדות שלמדו את המבוך מלכתחילה עם מזון, אבל תוך יום אחד בלבד (לקבוצה השניה לקח שבוע)
*** גרסיה ־ taste aversion
***** יש התניות שלא דורשות צימוד מיידי בין הגירוים ־ כמו סלידה ממזון שעשה לנו בחילה רק כמה שעות אחרי שאכלנו אותו
***** מספיק רק צימוד אחד
***** יש מוכנות מולדת ללמוד צימודים כרלה בצורה מאוד יעילה וחזקה
*** מיניה וקוק ־ observational fear conditioning
***** אפשר ללמוד לפחד מלהסתכל על מישהו אחר חווה פחד מגירוי מסוים
***** אי אפשר לגרום לפחד מכל גירוי: הצליחו ללמד קוף לפחד מנחש, אבל לא מפרחים
* פסיכולוגיה קוגניטיבית
*** חקר של תפיסה, זכרון, מחשבות, קבלת החלטות, קשב, שפה וכו'
*** חייב להיות מרכיב מולד\תורשתי בהתנהגות
*** חומסקי ־ LAD, language acquisition device
*** לפיו אי אפשר להסביר אחרת את היכולת של ילדים לרכוש שפה, על המורכבות הרבה שיש בה, רק ע"י גירוים וגמולים מהסביבה.
*** ויכוח שעדיין לא נפתר
*** ג'ורג' מילר ־ זיכרון עבודה
*** כלים לברר דברים שקורים במיינד
***** באמצעות התניה פבלובית ־ לבדוק אם כלבים מבדילים בין צבעים מסוימים (מתנים עם צבע אחד ואז בודקים עם צבע שני)
******* כנל עם צורות
******* כנל עם פנים שונים
***** מדדים: 1. דיוק 2. זמן תגובה
***** lexical decision task ־ לבדוק זמן עד לזהוי משמעות המילה
******* בודק זמן שליפה של מילים
******* semantic priming ־ יותר מהר לשלוף "ענבים" אחרי שקראנו כבר "יין"
*** קשב ־ איזה מידע ייכנס לתודעה שלנו?
***** גירוים בולטים יותר
***** הפנייה מכוונת של קשב
***** מה קורה למידע שמגיע אלינו ולא מקבל קשב?
***** dichotic listening task
******* שומעים שני ערוצים שונים בשתי האזניים ומתרכזים רק באחד
******* יש מידע שאפשר לעבד גם בלי לשמוע אותו באופן מודע
******* יש בעיקר עיבוד של מאפיינים אודיטורים (קול של גבר\אישה\צליל אחר) ופחות משמעות
***** גירויים ויזואליים
******* valid\invalid cues (congruent/incongruent)z
******* invalid מעכב את התגובה הבאה גם אם לא "ראינו" את החץ
******* נראה שקשב יכול להיות מופנה לאיזורים במרחב, כמו פנס
***** ג'ון דנקן ־ קשב מופנה לאובייקטים ולא לאיזורים מוגדרים בחלל ("הפנס הקשבי")
******* מלבנים וקוים עם שני מאפיינים צורניים לכל צורה
******* זמן תגובה מהיר יותר בשאלות לגבי אותה הצורה מאשר בשאלות לגבי שתי הצורות
******* לפי תאורית הפנס, מכיוון ששתי הצורות באותו המקום לא אמור להיות הבדל בזמן התגובה
*** תפיסה ־ perception ־ ייצוגים של העולם במיינד
***** התמונה שנוצרת במיינד = גירוי חושי + פרשנות מנטלית, תלוית הקשר, תרבות, ציפיות וכו'
***** bottom up vs top down
***** הייצוג הוא בסוף שילוב של השניים
***** האם הייצוג הפנימי הוא דימוי ויזואלי, או שהוא המשמעות של הדבר?
******* קוסלין ־ הדימוי הפנימי משתמש באותם מנגנונים שנעשה בשהם שימוש בזמן התפיסה
******* פלישין ־ הדימוי הוא סימבולי, הוא מכיל משמעות, ידע מילולי
*** זכרון
***** לא מדויק, לא ממצה, יש פער בינו ובין החוויה המקורית
***** מושפע בקלות מההקשר ־ how fast was the car moving when it "hit" vs when it "smashed" into the wall
***** שאלות על האירוע משפילות על איך זוכרים אותו
***** שאלות יכולות לייצר זכרונות שתולים
***** נוטים לזכור חוויה לפי הסוף שלה ־ כאב בפרוצדורה רפואית
*** זיהוי עצמים\שיוך לסוג
***** הכללה מפרט לסוג
***** זיהוי פנים של אנשים מגזע אחר
***** חשיפה פסיבית לא עוזרת לחדד את יכולת ההבחנה שלנו ־ אחיות בבית יולדות לא מבחינות טוב יותר בין פנים של תינוקות מאשר אנשים רגילים
***** צריך חשיפה עם משמעות, עם אינטראקציה
*** חקר המודעות
*** חקר הזכרון
***** HM
***** היפוקמפוס ־ מעבר מזיכרון לטווח קצר לטווח ארוך, 'קונסולידציה'
***** איך פגיעה באינטליגנציה או באף יכולת אחרת
***** זכרון לא דקלרטיבי ־ כמו למידה מוטורית גם כן לא נפגע
***** התניית פחד גם אפשר ללמוד
***** להבדיל ־ בפגיעה באמיגדלה יהיה זיכרון של תהליך ההתניה, אבל ההתניה עצמה לא תתרחש
***** priming גם אפשרי
*** התפתחות ותקופות קריטיות להתפתחות
***** home sign אצל ילדים חירשים שההורים שלהם לא יודעים לסמן
******* בעלת מבנה דומה אצל ילדים בכל העולם
******* נוצרת ע"י הילד עצמו, לא מתוך למידה של תנועות הידיים של ההורים
***** ההבדל ביכולת ללמוד שפה בין ילדים למבוגרים כהראה יותר קשור לאופן הוראת השפה, האינטנסיביות של הלמידה, וירידה כללית ביכולות קוגניטיביות עם הגיל (בילדים שלא נחשפו לשפה מינקוצ)
******* לחשיפה מוקדמת כן יש יתרון מוחלט בחכולת לרכוש מבטא
***** מערכת הראיה ־ חסכים מוקדמים מייצרים נזק בלתי הפיך
******* פרויקט פרקאש ־ ניתוחי עיניים לילדים שהם עוורים מלידה ־ מראה אילו אספקטים של הראייה נשמרים כפוטנציאל לא ממומש, ואילו אובדים באופן לא הפיך
******* נראה שאפשר להגיע לביצועים טובים מאוד גם אצל אנשים שעברו ניתוח רק בגיל 30
*** חקר המיינד אצל תינוקות
***** שיטות בהן רואים הבדל בתגובה של תינוקות לגירויים שונים ־ משך ההסתכלות על הגירוי למשל
******* קצב הדופק
******* תדירות מציצה של מוצץ
******* מזהים את קול האם, את השפה, סיפור ששמעו בעודם ברחם
******* מרים העדפה לגירויים שנראים כמו פנים ישרים (ולא הפוכים) ־ גירוים בצורת  T הפוכה, מבחינת כתמים כהים ובהירים
***** הביטואציה
******* אחרי הרבה הצגות של אותו גירוי ־ תינוקות משתעממים ממנו ומסתעלים עליו הרבה פחות
******* מראים לתינוקות את אותו גירוי כמה פעמים, ואחרי שזמן ההסתכלות פוחת מחליפים אותו לגירוי אחר, ובודקים האם זמן ההסתכלות התארך
***** perceptual narrowing
******* עד גיל מסוים מבחינים בין כל הגירוים מסוג מסוים (פונמות, פנים), ואחרי כ 9 חודשים מאבדים רזולוציה, ולא מבחינים בהבדלים בין גירוים שלא קיימים בסביבה (פנים של אתניות אחרת, בעלי חיים אחרים, פונמות שלא בשימוש)
******* בא יחד עם ההתמחות בזיהוי הגירוים שכן נפוצים בסביבה
******* גם חשיפה מועטה לגירוים הלא נפוצים משמרת את היכולת להבחין בינהם
******* אבל זה עובד רק עם חשיפה דרך אדם אמיתי, ולא, נניח, דרך הטלוויזיה
*** מחקרי אנטליגנציה
***** ז'אן פיאז'ה
***** 4 שלבים התפחותיים בקוגניציה
******* סנסורי ־ מוטורי
******* פרה־אופרציונלי ־
********* מחשבה סימבולית, שפה,
********* אבל אין שימור מספר וחומר,
********* אין theory of mind (ניסוי ההר)
******* אופרציונלי קונקרטי ־ חסרה היכולת לחשוב בצורה היפותטית, להסיק מסקנות על דברים שלא קיימים באמת בעולם, חוקים מופשטים
******* אופרציונלי פורמלי
***** התינוק כמדען שחוקר את העולם ומגלה קשרים
***** התנסות יותר חשובה מידע מולד
*** Theory of mind
***** הניסוי עם סאלי ואן: אן שמה גולה בקופסה שלה והולכת, סאלי מעבירה אותה לקופסה שלה, ושואלים את הילדים איפה אן תחפש את הגולה כשהיא תחזור.
***** השוואה בין אוטיסטים עם אנטליגנציה תקינה, ילדים עם תיסמונת דאון ואנטליגנציה של ילדים בני 5, וילדים בני 5 רגילים
***** יש עדויות לכך שתינוקות צעירים מאוד, מגיל שנה אפילו, כבר יודעים הרבה על ההתנהלות הפיזית של העולם ועל מה המתרחש במיינד של אנשים אחרים ־ אבל קשה להיות בטוחים
* פסיכולוגיה חברתית
*** אפקט אוטוקינטי ־ נקודת אור בחדר חשוך נדמית כזזה. הערכה סובייקטיבית שונה
*** הניסוי של שריף ־ קונפורמיזם ־ אם ההערכה נעשית בנוכחות אנשים אחרים ההערכה של כולם מתכנסת
*** הניסוי של אש ־ קונפורמיזם  כשמדובר בשיפוט לגבי משהו אובייקטיבי
*** השפעה אינפורמטיבית ־ כשדעתם של אנשים אחרים גורמת לנו לשנות את דעתנו באמת
*** השפעה נורמטיבית ־ כשאנחנו אומרים שדעתנו השתנתה, אבל רק מתוך לחץ וכלפי חוץ
*** bystander effect ־ אם יש קבוצה של אנשים שעדים לאדם בצרה\מקרה חירום כלשהו יש פחות סיכוי שמישהו מהם יעזור. למה?
***** diffusion of resposibility -  כל אחד חושב שהאחרים יעשו את זה, ושהם אולי יותר מוכשרים לזה ממנו,
***** Pluralistic ignotance שמניחים שאם האחרים לא פועלים אז כנראה אין באמת סכנה, כי הם בטח יודעים יותר טוב.
***** מבוכה
*** הניסוי של מילגרם
***** ציות להוראות, העברת אחריות "למפקד"
***** סמכותיות הנסיין משפיעה ־ התפקיד שלו ביחס להקשר
***** המרחק הפיזי מהנסיין ־ אם זה בטלפון או באותו חדר
***** המרחק הפיזי מהשחקן ("התלמיד")
***** מרד של משתתף נוסף\הסכמה של משתתף נוסף
***** בדקו גם עם שאלוני אישיות ־ אין השפעה לסוג האישיות על הצייתנות
* קוגניציה חברתית
*** איך אנחנו שופטים ומעריכים אנשים אחרים
*** בעצם סטריאוטיפים
*** "האם האדם שבתמונה מחזיק אקדח" ־ אם האדם שחור סבירות גבוהה יותר להגיד שכן
*** גם בקרב שחורים וגם בקרב לבנים
*** הערכת ההתאמה של גברים מול נשים למשרות באקדמיה בתחום המדעים ־ אותם קורות חיים עם שם שונה
*** גברים דורגו כמתאימים יותר והוצע להם שכר גבוה יותר
*** גם בקרב נבדקים גברים וגם בקרב נשים
*** IAT - implicit association test ־  נועד לבדוק את התפיסות הסטריאוטיפיות המובלעות שלנו, שאנחנו לא מודעים אליהן
***** מהירות תגובה בקישור בין (לדוגמא) מגדרים שונים לבין תכונות אופי או מקצועות שונים
***** מודעות לזה שאנחנו שופטים לפי סטריאוטיפים היא חשובה כי היא מאפשרת לנו לשנות את דעתנו
*** רושם ראשוני ־ הרבה פעמים באמת נכון. דירוגים של מרצים לפי קליפ של 30 שניות בלי קולתאמו לדירוגי סטודנטים
*** דירוגי תכונות לפי תמונות פנים ־ לאו דווקא מדויקים, אבל כן עקביים בין אנשים שונים
*** בעיקר לגבי דומיננטיות ואמינות
*** steriotype content model ־ תופסים קבוצות לפי שני צירים: קומפיטנטיות (סטטוס, כוח, יכולת, אמביציה) וחברתי־מוסרי (חום, יושר, אמינות, נחמדות וכו')
*** סטריאוטיפים הם לרוב משלימים ־ קומפלימנטריים:
***** קבוצות שנתפסות כלא קומיפטנטיות יתפסו כיותר מוסריות או יותר נחמדות כפיצוי (סטריאוטיפ פטרנליסטי ־ מזרחים וקשישים למשל)
***** סטריאוטיפ קנאי ־ קבוצה שנתפסת כמוכשרת יותר תתפס גם כלא מוסרית או קרה (אנטישמיות למשל)
*** steriotype threat ־ המאמץ שלא להתפס כמותאמם לסטריאוטיפ שיש עלי גוזל ממני משאבים וגורם לי לתפקד פחות טוב
***** אם נאמר מראש שנשים וגברים מצליחים במבחן במתמטיקה באותה מידה בד"כ, נשים יצליחו בו כמו גברים, לעומת מצב נייטרלי בו ביצועיהן נפגעים
***** כנ"ל לגבי מבחני אנטליגנציה לשחורים
***** כנ"ל לגבי מצב שבו עושים priming לנבדקים לחשוב יותר על פן בזהות שלהם שבו יש עליהם סטריאוטיפ שלילי לעומת פן שבו אין כזה
* להוריד טקסט של יחידות 7 & 8
