:PROPERTIES:
:ID:       20210627T195315.592044
:ROAM_REFS: cite:grazianoStandardModelConsciousness2019
:END:
#+TITLE: grazianoStandardModelConsciousness2019: Toward a standard model of consciousness: Reconciling the attention schema, global workspace, higher-order thought, and illusionist theories
#+ROAM_KEY:- tags ::
- keywords ::

* Toward a standard model of consciousness: Reconciling the attention schema, global workspace, higher-order thought, and illusionist theories
:PROPERTIES:
:Custom_ID: grazianoStandardModelConsciousness2019
:URL:      
:AUTHOR:   Graziano, M. S. A., Guterstam, A., Bio, B. J., & Wilterson, A. I.
:NOTER_DOCUMENT: /mnt/c/Users/Jonathan/Google Drive/.notes/.bibliography/bibtex_pdf/Graziano_etal_2019_AST.pdf
:NOTER_PAGE: 
:END:

*** deviding consciousness into 2 types: information and "mysterious"
:PROPERTIES:
:NOTER_PAGE: (3 . 0.13717693836978131)
:END:

*** i-consc. is about a stimulus achieving a level of attention that makes it into "something we remember" a bundle of information available to the brain as a whole
:PROPERTIES:
:NOTER_PAGE: (3 . 0.1066931742876077)
:END:

*** says that the aspect of consc. that has to do with retrieval of information exists in practice, but that the "other" type, what we feel we have that is "extra" is just a partial model of the first (information) type
:PROPERTIES:
:NOTER_PAGE: (3 . 0.28959575878064947)
:END:

*** referes to Nagel and chalmers - easy problem cs hard problem of consciousness is the same as explaining i-consc. vs m-consc.
:PROPERTIES:
:NOTER_PAGE: (4 . 0.12193505632869452)
:END:

*** unlike the ideas of the mind as energy that can affect objects in our sourrounding and move in space outside our bodies - the idea of a consciousness that accumulates information isn't easy to test and refute
:PROPERTIES:
:NOTER_PAGE: (5 . 0.8899637243047158)
:END:

*** the basic premise of the hard problem (that there is such a thing as a consciousness inside us) is actually wrong, and that's why it's so hard to find an an answer (to "how does the brain produce subjective experience/qualia)
:PROPERTIES:
:NOTER_PAGE: (5 . 0.40326481257557434)
:END:

*** these mental models - who exactly is there to model them and access these models? if there's no subject who's there to be mislead?
:PROPERTIES:
:NOTER_PAGE: (5 . 0.5006045949214026)
:END:

*** doesn't say that there's no such thing as consc. but that in fact there's only i-consc. which mistakes itself for being m-consc.
:PROPERTIES:
:NOTER_PAGE: (5 . 0.8343409915356711)
:END:

*** attention - in the sense of dedicating computational resources to a stimulus - has been shown to be possible without awareness to that stimulus
:PROPERTIES:
:NOTER_PAGE: (7 . 0.5711689884918232)
:END:

*** awareness is a model for attention
:PROPERTIES:
:NOTER_PAGE: (7 . 0.8358570563294972)
:END:

*** so awareness/consciousness is just the brain's way to represent the "fight for attention" that's forever happening between the stimuli we encounter.
:PROPERTIES:
:NOTER_PAGE: (7 . 0.4318594791035736)
:END:

*** it doesn't have to be accurate - we don't want different consc. for different types of stimuli - a general unified model is good enough to drive behavior
:PROPERTIES:
:NOTER_PAGE: (7 . 0.5154451847365233)
:END:

*** the information about a subjective experience must be based on information that exists within the brain - that information is a sort of model for the self  - information that describes the self.
:PROPERTIES:
:NOTER_PAGE: (8 . 0.5711689884918232)
:END:

*** since attention is so closely correlated with awareness - then it must be attention that is the physical aspect of the self that awareness is meant to model.i
:PROPERTIES:
:NOTER_PAGE: (8 . 0.7244094488188977)
:END:

*** that is such a stupid question. he seems to miss the point that a subjective experience is qualified exactly by the "feeling that we're having one"
:PROPERTIES:
:NOTER_PAGE: (8 . 0.44579043004239854)
:END:

*** tries to draw a parallel between body-schema and attention-schema, saying they're both very useful for us
:PROPERTIES:
:NOTER_PAGE: (10 . 0.39006662628709876)
:END:

