:PROPERTIES:
:ID:       20210627T195316.442510
:END:
#+TITLE: Literature notes: Mudrik 2010, ERP congruity

* General notes
:PROPERTIES:
:NOTER_DOCUMENT: /mnt/c/Users/Jonathan/Google Drive/.notes/.bibliography/bibtex_pdf/Mudrik_et_al_2010_Neuropsychologia.pdf
:END:

*** ERP = Event Related Potential
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** incongruent objects (incongruent to a specific scene)  = objects which are not likely to be seen in that context.
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** incongruent objects are identified more slowly and less accurately
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** inc. objects also induce earlier eye contact (also more frequent and prolonged)
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** a seeming paradox: if they take longer to be identified, how can they induce earlier eye contact - which implied the brain recognizes that something is off?
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** a model to explain the paradox: the brain does a first rough pass to get the gist of the scene, and later returns for for more detail - in the first pass it recognizes that something is off, and in the second pass it dwells longer on the object to figure out what it is
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** generally humans can identify scenes and categorize objects very quickly -  on the order of 20ms - but to realize that an object is incongruent you need to understand more precisely what the object is and calculate the probability that it would be in that scene...

Literature is devided on whether that can happen in the early stages of perception
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** three models about perception that say that the scene is understood first and that understanding prompts further investigation of objects for details.

"object model selection" and "matching models" add that the scene also primes
recognition of certain (congruent) objects, so that the brain needs less
information before deciding that it recognized a certain object. - Top down processing
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** Ganis and Kutas found some ERP effect lasting ~200ms after an (unrelated but not incongruent perse) object appeared in the scene, when subject were asked to identify it. larger effecet for incongruent cs congruent. they suggested that means that the context (=scene) affects only the semantic analysis of the viewed object.
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2762402088772846)
:END:

*** The results from ganis and kutas may also represent subjects' expectations being subverted (since they expected something guessable to appear in the cued location) and/or their need to change the response (identifying the object) they had ready along with expectation.
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6851174934725849)
:END:

*** the paper aims to reproduce the same effect but without the possible artifacts.  also a faster rsponse time in case of congruent objects
:PROPERTIES:
:NOTER_PAGE: (3 . 0.08407310704960835)
:END:

*** they did a follow-up experiment to test the effect of the photoshopping the incongruent images (they are clearly doctored) - asking naive subjects if the images were doctored or not
:PROPERTIES:
:NOTER_PAGE: (5 . 0.46840731070496083)
:END:

*** more accurate responses and shorter response times for congruent
:PROPERTIES:
:NOTER_PAGE: (5 . 0.5404699738903395)
:END:

*** more negativity (what does that mean?) for incongruent vs congruent scenes (300-500ms after the image)
:PROPERTIES:
:NOTER_PAGE: (5 . 0.7926892950391645)
:END:

*** brain region activity is correlated with congruity, and the laterality of the signal is also correlated with congruity
:PROPERTIES:
:NOTER_PAGE: (5 . 0.8527415143603133)
:END:

*** why 300-500ms? what the reference time?
:PROPERTIES:
:NOTER_PAGE: (6 . 0.9127937336814621)
:END:

