:PROPERTIES:
:ID:       20210627T195316.676612
:ROAM_REFS: cite:mudrikERPEvidenceContext2010
:END:
#+TITLE: mudrikERPEvidenceContext2010: ERP evidence for context congruity effects during simultaneous object\textendash scene processing
#+ROAM_KEY:- tags ::
- keywords ::

* ERP evidence for context congruity effects during simultaneous object\textendash scene processing
:PROPERTIES:
:Custom_ID: mudrikERPEvidenceContext2010
:URL:      
:AUTHOR:   Mudrik, L., Lamy, D., & Deouell, L. Y.
:NOTER_DOCUMENT: /mnt/c/Users/Jonathan/Google Drive/.notes/.bibliography/bibtex_pdf/Mudrik_et_al_2010_Neuropsychologia.pdf
:NOTER_PAGE: 
:END:

*** ERP = Event Related Potential
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** incongruent objects (incongruent to a specific scene)  = objects which are not likely to be seen in that context.
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** incongruent objects are identified more slowly and less accurately
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** inc. objects also induce earlier eye contact (also more frequent and prolonged)
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** a seeming paradox: if they take longer to be identified, how can they induce earlier eye contact - which implied the brain recognizes that something is off?
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** a model to explain the paradox: the brain does a first rough pass to get the gist of the scene, and later returns for for more detail - in the first pass it recognizes that something is off, and in the second pass it dwells longer on the object to figure out what it is
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** generally humans can identify scenes and categorize objects very quickly -  on the order of 20ms - but to realize that an object is incongruent you need to understand more precisely what the object is and calculate the probability that it would be in that scene...

Literature is devided on whether that can happen in the early stages of perception
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** three models about perception that say that the scene is understood first and that understanding prompts further investigation of objects for details.

"object model selection" and "matching models" add that the scene also primes
recognition of certain (congruent) objects, so that the brain needs less
information before deciding that it recognized a certain object. - Top down processing
:PROPERTIES:
:NOTER_PAGE: 1
:END:

*** Ganis and Kutas found some ERP effect lasting ~200ms after an (unrelated but not incongruent perse) object appeared in the scene, when subject were asked to identify it. larger effecet for incongruent cs congruent. they suggested that means that the context (=scene) affects only the semantic analysis of the viewed object.
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2762402088772846)
:END:

*** The results from ganis and kutas may also represent subjects' expectations being subverted (since they expected something guessable to appear in the cued location) and/or their need to change the response (identifying the object) they had ready along with expectation.
:PROPERTIES:
:NOTER_PAGE: (2 . 0.6851174934725849)
:END:

*** the paper aims to reproduce the same effect but without the possible artifacts.  also a faster rsponse time in case of congruent objects
:PROPERTIES:
:NOTER_PAGE: (3 . 0.08407310704960835)
:END:

*** they did a follow-up experiment to test the effect of the photoshopping the incongruent images (they are clearly doctored) - asking naive subjects if the images were doctored or not
:PROPERTIES:
:NOTER_PAGE: (5 . 0.46840731070496083)
:END:

*** more accurate responses and shorter response times for congruent
:PROPERTIES:
:NOTER_PAGE: (5 . 0.5404699738903395)
:END:

*** more negativity (what does that mean?) for incongruent vs congruent scenes (300-500ms after the image)
:PROPERTIES:
:NOTER_PAGE: (5 . 0.7926892950391645)
:END:

*** brain region activity was correlated with congruity, and the laterality of the signal is also correlated with congruity
:PROPERTIES:
:NOTER_PAGE: (5 . 0.8527415143603133)
:END:

*** why 300-500ms? what the reference time?
:PROPERTIES:
:NOTER_PAGE: (6 . 0.9127937336814621)
:END:

*** congruity was significantly correlated with activity in the left hemisphere and midline, but not with activity on the right hemisphere
:PROPERTIES:
:NOTER_PAGE: (7 . 0.19753086419753085)
:END:

*** Notes for page 7
:PROPERTIES:
:NOTER_PAGE: (7 . 0.20987654320987653)
:END:

*** NOTE What is vector-scaling normaliztion?
:PROPERTIES:
:NOTER_PAGE: (7 . 0.30864197530864196)
:END:

*** the effect of seeing something incong. is independent of the effort of understanding the surrounding scene (in the experiment that this paper replicates the context was presented first, and the incong. object "popped" into the scene, but still the time frame of the neural response was the same)
:PROPERTIES:
:NOTER_PAGE: (8 . 0.32098765432098764)
:END:

*** there may be two separate effects seen for incong. scenes: one ~270-600ms, and the other - which has a distinict spatial distribution - from 650-800ms
:PROPERTIES:
:NOTER_PAGE: (7 . 0.14814814814814814)
:END:

*** it's supported by ANOVA tests correlating time with the other measures (of laterality, congruity and region)
*** Nice. they show that subjects couldn't recognize the pasted images better than "chance"
:PROPERTIES:
:NOTER_PAGE: (8 . 0.6172839506172839)
:END:

*** the response in this paper is characterized by:
:PROPERTIES:
:NOTER_PAGE: (8 . 0.6666666666666666)
:END:

*** a good summary of the article: in general, understanding a scene is very complex computationally. we use prior knowledge and expectations to narrow down the number of possible interpretations, and this makes understanding faster. In line with this - when something in the scene defies our expectations, we decifer the scene more slowly, and this is evident in the Event Related Potentials seen in EEG for incongruent images.
:PROPERTIES:
:NOTER_PAGE: (8 . 0.7160493827160493)
:END:

*** they propose that the response  they saw in the 300-600 range is an overlay of two responses - one related to perception and one to processing of already-understood stimuli
:PROPERTIES:
:NOTER_PAGE: (8 . 0.8518518518518519)
:END:

*** this effect (this specific negativity in ERP) is known as N300, and it's generally thought to be related to matching (external, perceived) objects with their semantic meaning
:PROPERTIES:
:NOTER_PAGE: (9 . 0.13580246913580246)
:END:

I

*** Specifically, it seems to occur in situaltions where there's confusion/uncertaintny about the object, such as it being incongruent with the scene, generally unidentifiable, or semantically unconnected with a previously seen object.
:PROPERTIES:
:NOTER_PAGE: (9 . 0.3333333333333333)
:END:

