:PROPERTIES:
:ID:       20210627T195318.809190
:END:
#+TITLE: Literature notes: zhao19_graph_theor_model_baby_brain_network

:PROPERTIES:
:NOTER_DOCUMENT: ../.bibliography/bibtex_pdf/zhao19_graph_theor_model_baby_brain_networ.pdf
:END:

*** network topology
***** global (network architecture) vs nodal topological properties
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** segregated vs integrative topologies
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** segregation: a measure of the ability of localized area to perform computation - influenced by the degree of interconnectedness inside clusters
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** "modularity" = the existence of dense clusters, which are sparsely connected to each other
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** densely linked communities/clusters -> localized specialization in information processing
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** intra-cluster connections speak to segragration, inter-cluster to integration
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** integration: high "network efficiency" = low avg. shortest path
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** small world network is a good balance of segragation and intergration, provides smallish shortest path, and largish clustering coefficient
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** distribution of node-degrees is a meaure of rubustness
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** rich-club: interconnectedness of high-degree nodes
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** edge classification

- rich-club (in between major hubs), feeder connections (connecting into major hubs), local connections (within modules)
- core vs non-core based on BC

:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** hub classification
:PROPERTIES:
:NOTER_PAGE: 6
:END:

- provincial - the hub of a "module"
- connector - a hub connecting different modules to each other.
-

***** to measure small-worldness, you take the ratio between *normalized*  avg. shortest path, and *normalized*  clustring coefficient of a graph. *normalized* = divided by thath  of a random graph.

ratio should me much greate than 1

:PROPERTIES:
:NOTER_PAGE: 6
:END:

*** development
***** mostly using preterms babies as a model for fetuses, or postmortem of fetuses
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** earliest small world found - 20 weeks
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** modular organization and rich-club - 30 weeks
***** increase in modularity (clustering coefficient), reduced shortest path, increased local and global efficiency with age (term vs preterm neonates)
***** in the fetal stage the network develops more in the direction of clusters and modules, and not so much in integration - shown by a rising clustering coefficient with a stable shortest path.
***** hubs in the adult brain are mostly in the following areas:
:PROPERTIES:
:NOTER_PAGE: 6
:END:

superior and medial frontal, superior
parietal, sensorimotor and posterior-medial cortices

***** short distance links between areas develop faster than long range ones. e.g. intra-hemospheric, links betwenn the sensorymotor cortex and the occipital cortex (visual)

:properties:
:NOTER_PAGE: 6
:END:

***** at birth age hubs develop in more areas - the insula and the inferior frontal cortex, and they develop fast there, in terms of BC and efficiency
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** Q: what does PMW stand for? A: Post-Manstural Week
:PROPERTIES:
:NOTER_PAGE: 7
:END:

***** also before birth:

  - strengthening of all connections
  - a rapid proliferation of feeder connections, connecting more and more periferial/modular nodes into a major hub, thus shortening the distance into the "highway"
  - rapid proliferation of "core" nodes - that have a high BC

***** the above all mean that the development inside the modules occurs fast in prenatal stages, and they say in face faster than the development of the "highway" connections between the hubs.
***** also before birth:

  - strengthening of all connections
  - a rapid proliferation of feeder connections, connecting more and more periferial/modular nodes into a major hub, thus shortening the distance into the "highway"
  - rapid proliferation of "core" nodes - that have a high BC

***** the above all mean that the development inside the modules occurs fast in prenatal stages, and they say in face faster than the development of the "highway" connections between the hubs.
*** constructing a network
***** there are parcellations based on function, and others based on anatomical structures, and yet others based on a random algorithm
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** important to validate research using another ,different, parcellation methods
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** edge weight can be the number of physical connections between areas, or the diffusion index
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** for edges based on functional data, we'd usually use temporal correlation (pearson's correlation or syncornization likelyhood)  of activity between regions
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** the egdes that we get through the above methods need to be pruned by setting some threshold on the weights of the edges: either an aboslute cutoff, or by taking the N strongest connections in each subject (i.e. N strongest in the entire brain)
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** Q: what's an advantage of using a relative cutoff in creatiung a brain-network?
***** A: it means that all subjects have the same number of edges in their network, and so that factor doesn't impact the analysis of network topolgies
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** Q: what's a possible problem with edge weight thresholding in creating a brain network?
***** A: studies have shown that there are some real, valuable connections that show up as weak in terms of edge weight, and thrsholding will ignore them.
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** Q: what are two possible ways to mitigate the problem created by thersholding of edge weights (brain-network)?
***** A: 1. using several different thresholds, and checking if the analysis is robust to these changes. 2. using all edges without thersholding - but this is only aplicable to structural networks, because they're not fully connected to begin with
:PROPERTIES:
:NOTER_PAGE: 4
:END:

*** general
***** before birth - neuron creation and migration, and many connections (axon growth)
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** after birth - pruning of the many connections, prolonged myelination, "consolidation phase"
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** structurally, brain networks develop from limbic to association corteces, functionally - from primary to higher level functions
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** there's a process of *refinement* - separate regions start out separately, and gradually combine to enable more complex functions
:PROPERTIES:
:NOTER_PAGE: 2
:END:

***** different methods of parcellating the brain into ROIs can create very different parellations, and very different measures of attributes of the brain as a network
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** you can use d(iffusion)MRI to rconstruct the nerve pathways, and use them to define nodes
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** Q: what does fNIRS stand for? A: functional near infrared spectography
:PROPERTIES:
:NOTER_PAGE: 2
:END:

***** Q: what does dMRI stand for? A: diffusion MRI
:PROPERTIES:
:NOTER_PAGE: 4
:END:

***** Q: what does sMRI stand for? A: structural MRI
:PROPERTIES:
:NOTER_PAGE: 4
:END:

* Tasks
*** TODO read Basll et al. 2014, van den heuvel et al. 2015 about node degree distribution bein exopnentially truncated power law.
