* Notes on heuvel18_hubs_human_fetal_brain_network
:PROPERTIES:
:NOTER_DOCUMENT: bibtex_pdf/heuvel18_hubs_human_fetal_brain_networ.pdf
:ID:       20210627T195317.904786
:END:

* cerebellum
***** they saw some hubs only in younger fetuses and some only in older ones. the ones in the cerebelum were evident in both.
:PROPERTIES:
:NOTER_PAGE: (5 . 0.342117872544322)
:END:

***** hubs in the cerebellum are found also in children and teenagers - are they also found in adults or do they disappear?
:PROPERTIES:
:NOTER_PAGE: 6
:END:

* ROIs
***** they define ROIs bottom up - looking at adjacent voxels, and merging them according to similarity behavior (mximizing in-cluster and minimizing out-of-cluster dimilarity) - like k-means algorithm
:PROPERTIES:
:NOTER_PAGE: (3 . 0.3135838150289017)
:END:

***** why is it important for the ROIs to be similarly sized? we don't expect functional brain regions to be of similar size...
:PROPERTIES:
:NOTER_PAGE: (4 . 0.24149496885481553)
:END:

***** they assess development by dividing the fetuses into two groups, by age, and then comparing the hubs they found
:PROPERTIES:
:NOTER_PAGE: (3 . 0.16099664590321036)
:END:

* about this study
*** this study asks whether these hubs are operational before birth

but doesn't really answer the question, I think.
:PROPERTIES:

:PROPERTIES:
:NOTER_PAGE: (2 . 0.7485549132947976)
:END:

* myelination
***** more rapid myelination in left hemisphere, also other studies confirm more hubs there
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** a large proportion of the hubs are in the cerebellum - which is the earliest area to myelinate, also all the cortical hubs are in areas knwon to myelinate early
:PROPERTIES:
:NOTER_PAGE: (3 . 0.8150455198850024)
:END:

***** this makes sense I think, sense myelination makes for more efficient nerve operation and transmition of information - so we *would* like the areas that are critical for the growing connectivity of the developing brain to be the first to develop this attribute.
:PROPERTIES:
:NOTER_PAGE: (3 . 0.8351701006229038)
:END:

***** other studies have not found hubs in the cerebellum, they claim because others haven't looked there
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** there is evidence that neuonal activity stimulates the formation of myelin (ahown in mice)
:PROPERTIES:
:NOTER_PAGE: 6
:END:

*** interesting to ask about the connection between myleniation, spontaneous firing and hub formation, though I think that it's more interesting in a mechanistic sort of way.. it does make sense that areas that are meant to hubs would create an invironment of more efficient nural connectivity and also of a kind of experimental firing that would encourage new connections
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6641111643507427)
:END:

* Controls
***** it's important to control for the effect of using different thersholds when defining anything that uses thersholds (here - the top 10 hubs in the network)
:PROPERTIES:
:NOTER_PAGE: (4 . 0.39242932438907524)
:END:

***** also important to control for weighted vs binary (not weighted) calculation
:PROPERTIES:
:NOTER_PAGE: (4 . 0.39242932438907524)
:END:

* asymmetry
***** hubs are often symmetrical - appearing in the same regions in both hemispheres
:PROPERTIES:
:NOTER_PAGE: (3 . 0.855294681360805)
:END:

***** more hubs on he left (7) than on the right (5)
:PROPERTIES:
:NOTER_PAGE: (3 . 0.855294681360805)
:END:

* done
***** asks - do adult hubs start to develop in utero?
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** N = 105
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** connectivity metrices
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** visual and motor, esp. in cerbral parts found to have emergin hubs
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** hubs in associaltion cortex, close to the adult fusiform area
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** association cortices are brain areas that integrate sensory information from sevral other areas
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** they computationally played with the network structure and found the network efficiency decreased a lot more when deleting hubs
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** they deduce that hubs are important for functional organization before birth as well
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** also note that these are vulenrable areas in brain development
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** these hubs are critical for efficient signalling because the enable shorter paths betwenn many areas
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** in adult brains, hubs are found in areas that have considerable overlap with subregions of the DMN (ventral and dorsal precuneus, posterior and anterior cin- gulate gyrus, ventromedial frontal cortex, and interior parietal brain regions)
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** generally postulated that hubs support integration of information -> the basis for complex cognitive functions
:PROPERTIES:
:NOTER_PAGE: 1
:END:

 **

**

***** indeed hubs are implicated in psyciatric and neurologcal disorders  even those that have a late onset (as adults, after 2 years of age)
:PROPERTIES:
:NOTER_PAGE: 2
:END:

**

***** hubs are vulenrabilties of the network architecture
:PROPERTIES:
:NOTER_PAGE: 1
:END:

***** hubs have been long known in infants
:PROPERTIES:
:NOTER_PAGE: 2
:END:

***** looks like hubs are primarily in sensory and motor areas, but recently also found in other areas (such as the subcortical limbic-paralimbic area)_
:PROPERTIES:
:NOTER_PAGE: 2
:END:

***** they're trying to "prove" that are actually hubs in utero
:PROPERTIES:
:NOTER_PAGE: 2
:END:

***** an immature DMN is found in 2 week old babies, the [[file:../slip-box/2020-08-01-pcc.org][PCC]] being it's major hub
:PROPERTIES:
:NOTER_PAGE: 2
:PROPERTIES: 
:NOTER_PAGE: 2:NOTER_PAGE: 2
:END:

***** so some hubs exist in the infant brain, but do they exist before birth as well?
:PROPERTIES:
:NOTER_PAGE: (2 . 0.2570621468926554)
:END:

***** using hub developent as an indirct way to asses and refer to prenatal brain development
:PROPERTIES:
:NOTER_PAGE: (2 . 0.4315697420201137)
:END:

***** it's more and more understood that neurodevelopmental disorders are related to pre-birth conditions and events
:PROPERTIES:
:NOTER_PAGE: (2 . 0.3559322033898305)
:END:

***** studies in neonates show existence of hubs, and that they are highly connnected to other regions at birth
:PROPERTIES:
:NOTER_PAGE: (2 . 0.44993441189331)
:END:

***** the above about rich-club and hub existence is from studies about premature birth, and it's hard to generelize to normal birth because in that situation there's early exposure to all the stimuli in the outside world, and deprivation of hormones that are usuallyu preset in late prgnance s.e IGF-1 etc.
:PROPERTIES:
:NOTER_PAGE: (2 . 0.5488308115543329)
:END:

***** BC is the sum of lengths of all shortest paths that go through that node (i.e. that use that node as a hub)
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** measuring nodes by degree (=strength) and "betweenness centrality (BC)
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** strength is the sum of (weighted (by what)) connections of that node to other noded
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** list of sensory and motor areas (found hubs in all of them): left and right cere- bellum, left precentral gyrus, and right primary visual cortex
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** also found hubs in association cortices (left and right inferior temporal gyrus, angular gyrus, and medial temporal lobe)
:PROPERTIES:
:NOTER_PAGE: 3
:END:

***** they determine network efficiency as the (inverse of the) mean path length from every node to every other node
:PROPERTIES:
:NOTER_PAGE: (3 . 0.2817441303306181)
:END:

***** They suggest/think that some of the hubs they found overlap with areas that are kown as inportant centers in the adult brain (fusiform facial area and Wernicke’s area)
:PROPERTIES:
:NOTER_PAGE: (3 . 0.7647340680402491)
:END:

***** all the hubs found in this study are similar to ones found in other studies done with newborns and pre-term newborns except for the insula. This seems to point to the insula taking a more central place in the developent that occurs after birth. wonder why? what connection does the insula have with outside stimuli?
:PROPERTIES:
:NOTER_PAGE: (5 . 0.6238620028749401)
:END:

***** wenickes area has to do with language, also the lefy hemisphere in general
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** I think I'm actually more interested in newborn brain development, 0-2 years. more than in utero [[file:../slip-box/2020-08-05-unanswered_(research)_questions.org][Unanswered (research) questions]]
:PROPERTIES:
:NOTER_PAGE: 5
:END:

***** hubs are more vulenrable in the fetal brain than in early childhood (2 yrs) - the topology of the network changes so that there are maybe more bypasses and redundancy
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** they measure the strength of the hubs they find by *computationally* removing/hurting them and then checking the effect on the network they modelled

:END:

***** does it even make sense to look at the brain as a network/graph like this? isn't it too simplistic? even if there is a "path" between two nodes, we know nothing of the modulation of the signal aloing the path. we don't know how indibidul neurons are wired to receive current from other neurons along the path, of their internal neuronal computation etc. [[file:../slip-box/2020-08-05-unanswered_(research)_questions.sync-conflict-20200805-132316-DDBHED7.org][§:Unanswered (research) questions]]
:PROPERTIES:
:NOTER_PAGE: 6
:END:

***** there are new studies on RSFC in fetuses that show long range, cross-, and intra-hemisferic connectivity becoming stronger with the age of the fetus.
:PROPERTIES:
:NOTER_PAGE: (6 . 0.6641111643507427)
:END:

***** connections between the hemispheres become more numerous with age of fetus
:PROPERTIES:
:NOTER_PAGE: (6 . 0.14087206516530906)
:END:

