:PROPERTIES:
:ROAM_REFS: @giosubaggioSemanticUnification
:ID:   20211221T121358.798097
:END:
#+title: Notes on hagoort giosu baggio, Semantic Unification
* summary and short reference
This article (chapter?) lists some of what's currently known about semantic unification - the integration with existing context of new information as it is being received.
The main ERP component that relates to this function is the N400 component, and they list several things that seem to affect it, such as ease of lexical access in semantic context, and information structure, and also several distinct functions that (may) make it up: inferring the truth value of a statement according to our world knowledge, asserting it's semantic validity, integrating new information with information that is implicit in the context.
They  list several fMRI studies in an attempt to localize these functions, and come to the conclusion that that there is a sort of unification hub in the LIFC, and other related areas in the left superior and middle temporal lobe.
They end by suggesting a distinction between integration - combining multi-modal information to retrieve some known memory/concept - and unification - the reconciliation of new information with existing information to create new knowledge/understanding, and cite a paper that supports this view by showing activation in different areas for incongruent animal - sound pairs and for congruent ones.

I think it would be interesting to continue this line of questioning, teasing apart unification and integration. For example, testing patients with semantic dementia, or applying TMS to the ATL to create difficulties in naming objects or animals - if I understand their view correctly, this should reduce effects related to integration and semantic retrieval (e.g less activation for familiar stimuli couples), but not affect N400 effects such as increased response semantic (in)validity of different kinds.
Separating integration from unification
patients?
    SD - semantic dementia ATL. If they don't recognize animals so well, will there be an N400 for semantic incongruency? For syntactic? Also TMS to ATL
    Patients with lesions in brocha's area - will they still have semantic N400? Will they have problems with integration?


* general notes
*** ERP studies:
***** N400 is about integrating the current word into the context
***** the more fitting the word - the smaller the response
***** some think it's also related to the ease of lexical access - so it can tell us something about how words are organized in memory, and is affected by how many cues there are in the current context for the current word
***** information structure: what information is accented and which is deaccented. N400 stronger for new information which is accented than for new information which is deaccented
***** N400 for "an" instead of "a" when it excludes the most probable continuation (supports lexical semantic retrieval)
***** R vs L hemispheres: maybe lexical retrieval is specifically a LH attribute (oranges<apples<carrots N400)
***** possible roles/processes of N400 response:
******* world knowledge
********* they say that  based on their experiment (yellow trains), semantic validity, and truth value of a sentence are done at the same time, and thus they are part of the same process, and not two sequential processes
******* silent meaning processing
********* semantic processing can change based on the context, even for very basic properties like being animate/inanimate ("the peanut was in love")
********* semantic processing of information that is implicit in the sentence and depends on our knowldege of the world ("the journalist started the article")
******* integration of pragmatic information
********* same  for information that's related to the information we have about the speaker: we get an N400 (rather than later) effect for words that create a meaning that conflicts with what we know
******* syntax-semantics interface
********* P600 effect for syntactic violations
********* where syntax is correct but semantics are wrong in some basic sense, or the other way around - we'll get either N400 or P600 depending on which modality imposes a stronger constraint in that context: if semantics is too far off, even though syntax is alright we'll get an N400
*** fMRI studies = localization
***** LIFC: same areas were active for semantic anomalies as for sentences that had ambiguous words, they say it shows that these areas are related to semantic unification - they work harder in both cases.
***** "In short, the semantic unification network seems to include at least LIFC, left superior/middle temporal cortex, and the (left) inferior parietal cortex."
***** ILFC as a hub of unification?
***** story comprehension: 4 sentences, the last either easiy connected or requiring more inference - harder sentences required more IFC, MTG (middle temporal) and MFG (middle frontal) activation
***** ILFC as "semantic selection"/ "controlled retrieval" (generalizing from language area )
******* more ativated when generating verbs for a noun that has many optional verbs (i.e harder to choose among options) than for a noun with a single associated verb scissors vs wheel
******* unification often *but not always* implies/requires selection: among different meanings of the same ambiguous word - *unification is a broader account of ILFC role*
***** integration vs unification;:
******* the examples they give: why wouldn't there be also a unification attempt? Like an N400 for integrating the wrong animal sound
********* apparently it's more so in the LIFC for mismatches, and there's more activity for congruent =recollection stimuli in the STG(superior temporal)
* see also (notes, tags/ other papers):
