:PROPERTIES:
:ID:       20220515T175949.626248
:ROAM_REFS: @graftonEvidenceDistributedHierarchy2007
:END:
#+title: Notes on Grafton, de C. Hamilton, Evidence for a Distributed Hierarchy of Action Representation in the Brain

* summary and short reference
They describe three [[id:20220516T192509.026000][Repetition supression (fMRI)]] experiments:
1. dissociating the goal-object (the object which you are reaching for) from the trajectory (lef/right of the midline)
2. dissociating the object from the grasp type /aperture (wide/narrow)
3. dissociating the object from the goal of the movement - what they call outcomes - (open/close  a drawer)

They find that the left aIPA is sensitive to the object identity, the lateral occipital area is sensitive to the lower kinematic  features like grasp aperture and trajectory, and for outcomes in bilateral IPL and IFG

*** They refer to a three-level hierarchy of movement generation/perception:
      - Kinematics
          + Reach trajectory. RS at this level is related to the detection of how an agent is approaching an object.
          + Grip configuration. This level is defined by the specific hand-object interaction, such as a power or precision grip.
          + Means. This encompasses several features, including dynamic interactions based on object weight and the specific transport or manipulation of an object.
      - Goal-object. This is defined by the identity and function of the grasped object
      - Outcome. This is defined by the physical consequences of an action, for example altering the position or configuration of objects in the world

* Annotations(5/15/2022, 5:58:36 PM)
*** intro
“the Theory of Event Coding, the notion of a sensory to motor transformation for guiding behavior is rejected. Instead, this model emphasizes the existence of a common outcome-based frame of reference that is accessible to both perceptual features as well as to motor commands (Hommel, Musseler, Aschersleben, & Prinz, 2001;Mechsner, Kerzel, Knoblich, & Prinz, 2001). This harkens back to Bernstein's proposition that the action is organized in terms of its effect on the external world”

“All of these theories envision motor control as a refinement of information processing from a distant goal (‘light the cigarette’) to a more detailed motor plan (‘lift the match, strike the match’) to a precise specification of the reaching and grasping actions required to achieve each motor plan, and finally the activation of specific muscles in a coordinated sequence and the associated coarticulation that emerges at this level of organization.”

“IPL localization”

“is always in the left hemisphere whether the task is to be performed with the left or right hand”

“show a decoupling between hand preference and action retrieval, with praxis localized to the left side”

“There have been no functional brain imaging studies of planning purposeful movements that are based specifically on the chaining of motor elements to accomplish a motor goal in normal participants”

“Grafton and de C. Hamilton Page 8 Hum Mov Sci. Author manuscript; available in PMC 2008 August 1.”

“execution processes by means of go, no-go tasks (Johnson-Frey, Newman-Norlund, et al., 2005;Kawashima et al., 1996;Tunik, Schmitt, & Grafton, 2007”

“it is not clear that imagined movement is sufficiently similar to natural motor planning”

“there is a strong overlap between areas recruited for imagined and executed movements, so that a neuroanatomical hierarchy based on imagined action is not sufficient on its own”

“Grafton and de C. Hamilton Page 9 Hum Mov Sci. Author manuscript; available in PMC 2008 August 1.”

“et al., 2001). As such, mirror neurons are strong evidence for the existence of action representation in terms of a goal that is at a supraordinate level relative to perception or execution”

“These data have been interpreted in terms of neural coding for performed and observed intentions in the IPL”

“identification of mirror neurons in monkeys clearly demonstrates a representational hierarchy for action that is closely related to hand-object interactions”

“are there many types of mirror neurons that vary as a function of the levels of complexity from simple movements like grasping to complex action sequences?”

“how action chaining is organized in this circuit.”

“If the MNS is recruited similarly for both action execution and observation, then it becomes practical to characterize action hierarchies with observation tasks alone using an enormous variety of action movies and, thus, bypassing the physical limitations of trying to execute complex actions in the scanner.”

“Despite these criticisms of the MNS, it remains an important framework for determining the organization of action representation in humans.”

“A basic question that we have been interested in is whether areas that are active during action observation and part of the MNS operate as a functionally uniform network or whether it is possible to detect functional gradations within the circuit depending on the level of action being processed. Such a gradient across the functional anatomy would suggest that there are multiple levels of representation for action understanding at a cognitive level and similar levels likely exist for performed action organization.”

“if we can show that different brain areas are recruited for different kinds of action observation, then the human MNS may need to be broken into component processes at both a cognitive and anatomical level”

“7.1 Repetition suppression We recently employed a method to distinguish levels of action representation based on a phenomenon called repetition suppression (RS). RS has been extensively used in studies of visual representations (Kourtzi & Kanwisher, 2000;Grill-Spector & Malach, 2001), where it is sometimes referred to as fMRI-adaptation. Repetition suppression is based on reduced physiologic responses to repeated stimuli. Fig. 2 is an example of an RS paradigm from one of our fMRI studies. The phenomenon is not unique to fMRI and is also observed at the level of single neurons. There are three major advantages to the RS approach. First, it allows us to identify changes within a class of stimuli or a level of the hierarchy rather than between classes. In this way, different levels of representation for the same stimulus can be analyzed independently. Second, it can be associated with behavioral correlates, such as reaction time priming (Maccotta & Buckner, 2004;Wig, Grafton, Demos, & Kelley, 2005), although we do not make use of this behavioral consequence here. Third, RS data can usually be interpreted as an effect related to neuronal population coding, because suppression occurs when two successive stimuli are represented in the same neural population, and release from suppression occurs when two successive stimuli are represented in different populations.”

“This interpretation of RS data depends on two simple assumptions.”

“First is the assumption of population coding within brain regions, for which there is extensive evidence in many parts of the cortex”

“Second, the population response must change when the same stimulus feature is repeated.”

“Despite these different causes at the neuronal level, the observation of population suppression to repeated stimuli is not in doubt and the principle of measuring RS in order to infer neuronal population coding appears to be sound”

“A final issue that arises when using RS in motor studies is the assumption that the phenomenon occurs consistently across the neocortex. The vast majority of studies have examined RS in visual regions such as the lateral occipital complex and fusiform face area (Henson et al., 2003).”

“This plurality suggests that it should also be effective for studying action representation.”

“In all our experiments we used a one-back RS design, where each stimulus is defined as novel or repeated relative to the one stimulus before it. This approach is motivated by the fact that RS is largest on a single repeated trial immediately following the prime stimulus and the amount of suppression does not increase after approximately 8 stimuli”

*** RS experiments
“In our initial experiment we measured repetition suppression for which one of two possible objects was grasped, and for the trajectory used to grasp the object. Participants watched brief movie clips of a hand reaching and grasping one of two objects, such as a cookie or a computer diskette as shown in Fig. 2. Each of the objects was positioned to the right or left of midline, so that trajectory could be independently manipulated with respect to which object was grasped. The actor used a similar grip to take each object, then lifted it and transported it to the midline and the trial ended. Thus, there was no change in the grip or in the means or outcome of the hand object interaction between movies. Only the identity of the grasped object was manipulated. In this experiment, the essential goal of the task is grasping the object. Thus, the key RS effect is at the level of a goal as defined by object identity. The main finding was a strong RS effect in the left anterior intraparietal sulcus (aIPS) when the same object was grasped, irrespective of trajectory, Fig. 3, top right. aIPS was not sensitive to trajectory. Instead, RS effects for trajectory were observed in left lateral occipital sulcus and right superior precentral sulcus, Fig. 3, top left. This result provided clear evidence for an action hierarchy during observation that is based on differences between reach kinematics and the goal of the action defined by the grasped object.”

In the second experiment, referred to as the wine drinkers task, participants watched an actor
reach out and grasp either a wine bottle or a dumbbell placed on end (Fig. 2). The trial ended
after the object was lifted and placed in a new location. Two levels of action representation
were localized using RS (Hamilton & Grafton, in press). First, we varied whether they saw a
grasp of the dumbbell or wine bottle, thus allowing an independent replication of the goalobject
RS effect determined in experiment 1. Second, we manipulated how the hand grasped
the object. A wine bottle and dumbbell each have a thin part and thick part. In a given trial, for
example, the wine bottle would be grasped either by the body or the neck. With this
manipulation we could test if aIPS responses are related to a higher order goal-object process
or to local kinematic features of how the hand is interacting with the object, or both.
RS effects for goal-object effects were again localized to left aIPS extending into the adjacent
IPL as well as the right aIPS

The main RS effect of how the object was grasped (Fig. 3, left middle) identified three clusters
in the inferior and middle occipital regions, a single cluster in the IFG

“Taken together, the results of experiment 1 and 2 provide strong evidence for multiple levels of grasp related action representation in the brain”

“lateral occipital regions contribute to a visual analysis of hand-object kinematics for both how the hand approaches an object, the specific grip on the object and the subsequent movement of the object”

“the inferior frontal region is sensitive to the local kinematic features of how an object is gripped.”

“we can assert that the role of aIPS, based on two RS experiments, is at the level of representing an object as a goal for the hand”

“The final RS experiment considered physical outcomes of actions”

“(Hamilton & Grafton, 2007).”

“Depending on the starting position of the lid, the outcome of the movement was to either open or close the box. Using RS, we could independently manipulate the outcome (open or close the box) from the means to accomplish the outcome (push or pull the lid).”

“An RS effect for outcomes was found in the bilateral IPL and the IFG”

“Analysis of the responses to each of the individual sets of movies indicated that the RS effects for outcome in parietal and frontal areas were not driven by a single action or outcome, but generalized across a wide variety of actions.”

“grasping a particular object could be considered a type of low-level outcome in the sense that the final goal-object interaction was the purposeful movement”

“To test for this, a region of interest analysis was performed in the aIPS using the localization of experiment 1 and 2. Within this region of interest, significant suppression for repeated outcomes was detected, supporting a model in which aIPS is involved in goal representation for tasks spanning a range of complexity.”

“7.5 Potential pitfalls of the RS method”

“The results of the RS experiments do not exclude the existence of shared processing across action levels”

“Given the tight coupling between kinematics and goals, a second question is whether RS effects for outcome are actually due to more subtle differences of kinematics rather than the outcome itself”

“However, if this were the case, we would expect to see similar RS for both the subtle kinematic effects for different outcomes and also for kinematic differences irrespective of outcomes.”  either I didn't understand, or I'm just not persuaded: why would there be RS effects for "subtle kinematics" of different goals? if the kinematics and goals are so tightly coupled...

“grasps, goals and outcomes”  the three levels of the hierarchy they look at

“The three brain imaging experiments of action observation based on the RS method identify a distributed set of brain regions that are differentially activated as a function of the complexity of motor behavior in relationship to the final outcome of a movement”

“we studied spanned three levels of behavioral complexity and stopped at the level of action outcome.”

“relevant for defining a functional-anatomic hierarchy involved in understanding intentionality”

“the manipulated object defined the outcome of an action”

“It will be critical in future studies to determine how the incorporation of a tool into an action scheme would be represented in this hierarchy.”

“We found that detection and analysis of the outcome of a movement, such as the opening or closing of a box, recruited a right inferior frontal, biparietal network”

“This localization was different from the detection of areas sensitive to evaluating goal-object interactions, which were most prominent in the left aIPS”

“Finally evaluation of lower level kinematics, such as how a hand grasps an object (rather than what is grasped), and arm trajectory including reach and transport, all engaged visual association areas”

“These areas are all interconnected, and in a hierarchical model such as this it does not make sense to conclude that any one region makes an exclusive contribution towards action understanding. Instead, this set of brain regions can be viewed as supporting a cascade of processing, much like the early visual areas do for vision.”

“Our current RS experiments have only examined observed behavior, and an equivalent set of studies for imagined or executed behaviors have not yet been conducted”  future study?

“if the general principle of mirroring applies throughout the action resonance system, then our results predict that the action control hierarchy should match the action understanding hierarchy. That is, it should be possible to identify regions within the distributed motor control system that differentially encode kinematics, goal-objects and outcomes.”

“Critically, the left inferior frontal cortex did not demonstrate significant RS effects for outcomes or hand-object interactions. Instead, the right IFG and parietal cortex were maximally engaged. In contrast, in imaging studies of goal oriented action planning with pantomime of tool use (Johnson-Frey, Newman-Norlund, et al., 2005) or lesion localization of apraxia patients (Haaland et al., 2000) the left hemisphere premotor and parietal cortex is maximally engaged. This implies a functional-anatomical discontinuity of observation and planning at the outcome level and that is not consistent with the principle of mirroring.”

“parietal and premotor cortex between observation and execution. This would suggest that the overlap for observation and execution, i.e., the MNS, is maximal for mid-level control processes including what is grasped and how the hand grasps the object.”

“The implication is that for representation of distal goals or intentions, there may not be a common neuronal substrate for execution and observation. The way to resolve these conflicting conclusions is to obtain additional studies combining observation and execution tasks in the same participants. The RS method is particularly well suited for this”  0future study?

“RS can be applied to action planning where repetition of different aspects within a planning hierarchy could be compared.”  future study?

#+print_bibliography:

* see also (notes, tags/ other papers):
