:PROPERTIES:
:ROAM_REFS: @greenFamiliarInteractingObject2006
:ID:   20211123T173834.951790
:END:
#+title: Notes on Green, Hummel, Familiar Interacting Object Pairs Are Perceptually Grouped.
* main points
* findings
* methods
* summary and short reference
* general notes

*** object recognition is facilitated by context understanding

*** how is visual information from the scene influence object recognition?
*** Maybe the functional relationship between objects is part of how we represent a scene (hierarchy of meaning) and also helps recognition of objects (objects that are congruent with the relations they are in will be recognized faster? )

*** The schema hypothesis: the proposal that visual information makes rapid contact with high-level representations of scenes and that these high-level representations affect subsequent perceptual processing
*** extracting the gist
*** object identities from geons - *is it right to look at it as high level "otherwise ambiguous" object? Maybe it's more about abstraction/representation (in this way of representation this is a how a teapot looks like)*

*** evidence that we don't maintain a representation rich with all the details of the scene
        e.g we don't notice  small changes happening during a saccade.
        So we keep the general high level information but not the details
        things we recall better are more consistent with the schema - *in the grimes experiment, maybe it's just that the changes are physically/visually smaller, and a matter of their semantics?*
        directional relationships (facing to/away)

*** they say that the information is retained because it's _functional_

*** their idea: groups of objects form units of meaning in the scene
*** they have their own representations in the perceptual system
*** these units of representation are what information flow used to comprehend the scene is centered on
*** prediction: object perception will be modulated by it being a part of a functional group

*** functional information helps patients with visual neglect to find objects more quickly
*** patients that can only recognize one object at time  can recognize two objects if they are in interaction  $\Rightarrow$ objects in interaction form one unit in some respect
*** but is it the same for healthy subjects? And what's the mechanism - this paper is about this.

*** exp1
*** is an object matching the label shown as the 2nd object?
*** they found better RT if distractor object is functionally related to 2nd object 
*** also better than when target was interacting with 
*** *why one after the other and not as natureal scene?*

* see also (notes, tags/ other papers):
