:PROPERTIES:
:ROAM_REFS: @pattersonWhereYouKnow2007
:ID:   20211101T135513.996264
:END:
#+title: Notes on Patterson, Nestor, Rogers, Where Do You Know What You Know? The Representation of Semantic Knowledge in the Human Brain

* summary and short reference
    This review paper is aimed at supporting the idea that the integration of semantic information is through a centralized architecture, where sensory, motor, and other data are processed by a hub located at the anterior temporal lobe.
    They support this claim mainly through case studies of patients with semantic dementia (SD) of which ATL damage is a hallmark, and is characterized by severe deterioration of semantic knowledge - little deterioration of episodic memory and functional knowledge. They compare SD with other brain diseases and lesions with different etiologies and symptoms, and rely on conclusions from machine learning to demonstrate the advantage of this kind of "distributed + hub" architecture.

    I enjoyed the paper and found their idea compelling - but I think that some of their reasoning and interpretations are not solid enough:
*** in the recognition tasks given to SD patients they want to claim that less specific categorization is less damaged by showing that the "typical" exemplars are better recognized, but does it really make sense to claim that most vegetables are green, and most animals have small ears?
*** in the same vain, I didn't understand why the ATL being related to better classification of more specific exemplars (as opposed to basic categories) supports their thesis - maybe it's just responsible כםר recognizing finer details, and for deeper integration of information.
*** I think the way that they propose the gated mechanism would work is somewhat arbitrary - they say that pear and banana wouldn't be associated because they don't share color, shape and name, so there won't be an activation of shared neural substrate - but why can't we postulate a fruit area that both of them would connect to, like in the "zones" theory which would be activated for both and make the association? (if we have a cell for Jeniffer...)
*** last, in the way they describe the sort of generalization that each architecture affords, it seems to me they're assuming what they want to show - saying that the convergent architecture is "not dominated by similarities expressed in any individual modality" and that they "can capture the 'deep' structure of concepts".

* main points
Semantic knowledge deterioration + focal damage in ATL = proof of hub?
* findings
* methods
* general notes
* see also (notes, tags/ other papers):
