:PROPERTIES:
:ROAM_REFS: @songRepresentationContextuallyRelated2013
:ID:   20211213T225549.319966
:END:
#+title: Notes on Song, Luo, Li, Xu, Liu, Representation of Contextually Related Multiple Objects in the Human Ventral Visual Pathway
* summary and short reference
In this paper the authors presented subjects with either disembodied heads, headless bodies, normal complete figures, and "scrambled" figures (head under the body) and tested the activation in the face and body related areas in the fusiform gyrus (FFA and FBA).
They found that that when viewing complete figures, activation in more posterior areas was roughly proportional to the combined activation while seeing bodies alone and faces alone. In contrast, activation in more anterior areas was significantly greater than the same combined activation.
In addition, when decoding the viewed image from the fMRI data, they found that in the right hemisphere they could differentiate the whole figures witha high success rate, but not so in the left FFA, where whole figures were miscategorized as either bodies or faces with equal probability.

They interpreted the results to be a (first) support for the idea that the brain represents objects in context in an hierarchical manner - where more posterior areas represent objects in isolation, and more anterior representations include a facilitating effect of context, and the right FFA specifically integrates an object with it's context in some way as a single entity.

I  disagree with the way the present the context of their findings: they refer to the stimuli they show as "multiple objects which are contextually related", but to my mind it's clear that a complete human figure is much more than several related objects, as it constitutes an especially meaningful object in its own right. In this light, an alternative explanation would be that the more anterior areas and the right FFA are just more specialized in responding to the human figure.
It would've also been interesting (better?)  to use more ecological stimuli that present just faces or just bodies - such as a scene where the body is hidden by an object in a natural way. I wonder how this kind of stimulus would compare in terms of brain activation - since the complete figure is implied in such a strong way that one could say it's almost perceived to be there.


* methods
*** locallizer
*** experiment blocks for all 4 conditions (heads, bodies, FB, and scrambled )
*** 1-back task (recognize when any of the parts repeats twice in a row)
* general notes
*** fMRI
*** looking at the ventral stream
*** looking at how we represent visual scenes, and objects therein
*** bodies and faces - either separately or together
*** in posterior regions: body+face activation was the average of face and body alone
*** in frontal ares : body+face was stronger than the average (facilitated activation)
*** in R fusiform: body+faces represented as one unit
*** they say that this shows an hierarchical representation system - in the dorsal area we see the more discrete members (face alone, body alone, both together is a ~sum of the individual representations) and more frontally we have the higher members of the hierarchy - where the combination has it's own representation
*** ****** the stimuli are a little strange - when do we encounter just bodies like that? Would be better if it were low angle shots of people or something
*** ****** why only in the R FFA?
*** the better classification for FB was *not* because of mutual neurons on the FFA (faces) and FBA (bodies) - when they removed those voxels the classification results were the same
*** classification was much better from just the FFA than just the FBA - so they figure the joint success is due to the mostly to the FFA
*** ****** the whole notion of contextually related "objects" is strange here - FBs are clearly one object..
* see also (notes, tags/ other papers):
